[Form] New translation_parameters option
symfony/symfony-docs pull request #10065
Opened 2018-07-13 13:52 UTC by webnet-fr

Documenting symfony/symfony#27775

2019-02-13 07:22 UTC, fabpot requested changes

2019-02-13 07:22 UTC, fabpot commented on reference/forms/types/button.rst
> +**type**: ``array`` **default**: ``array()``
We are now using `[]` for arrays. This should be changed everywhere in this pull request.

2019-02-13 07:22 UTC, fabpot commented on reference/forms/types/button.rst
> +Note that `label_translation_parameters` of buttons are merged with those of its
double "`" are needed in ReST.

2019-03-06 08:34 UTC, merged

2019-03-06 08:35 UTC, javiereguiluz commented
@webnet-fr thanks a lot for contributing these docs and I'm sorry for taking us so long to merge it. This is finally merged. Thanks!