Method should be static. Encourage use of const
symfony/symfony-docs pull request #10308
Opened 2018-09-10 00:45 UTC by trsteel88

Function should be static and we should also encourage the use of constants

2018-09-10 00:48 UTC, trsteel88 commented
Sorry, it shouldn't be static as that method comes from Doctrine and differs to Symfony's event subscriber. Updated that and just kept the constants.

2018-09-10 08:28 UTC, javiereguiluz commented
@trsteel88 thanks for this contribution! However, I think the new code is different than the existing code. Is this a bug fix, an improvement or both? We'll need help from Doctrine experts to verify this proposal. Thanks!

2018-11-14 23:08 UTC, ndench requested changes
@javiereguiluz this doesn't change the existing code. You can see from the [doctrine source](https://github.com/doctrine/doctrine2/blob/4d49b7778c9395941812bf28460dd7f36d57d196/lib/Doctrine/ORM/Events.php) that event constants are the same as the original strings.

Also the [doctrine documentation](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/events.html#lifecycle-events) recommends using the event constants:

```
<?php
use Doctrine\ORM\Events;
echo Events::preUpdate;
```

2018-11-14 23:08 UTC, ndench commented on doctrine/event_listeners_subscribers.rst
> +                \Doctrine\ORM\Events::postUpdate => 'postUpdate',
I think we should import `Doctrine\ORM\Events` and use `Events::postPersist` and `Events::postUpdate` here instead.

2018-11-15 09:18 UTC, xabbuh commented
Thank you for this change @trsteel88. I have merged your changes into the `2.8` branch (from where it will be merged up to all maintained branches) and made some small tweaks in 88939dea3de24c8d24bbbf1b5f9a0e75db4c76bd.

2018-11-15 09:18 UTC, closed without merging

2018-11-15 23:18 UTC, trsteel88 commented
No worries. Sorry I fell off the face of the earth. Been a bit hectic.