Document the port
symfony/symfony-docs pull request #10359
Opened 2018-09-18 10:15 UTC by roukmoute

2018-10-04 04:01 UTC, fabpot requested changes

2018-10-04 04:01 UTC, fabpot commented on security/access_control.rst
> +    It could be usefull for localhost:8080 by example.
useful

2018-10-04 04:01 UTC, fabpot commented on security/access_control.rst
> +    It could be usefull for localhost:8080 by example.
localhost:8080 should be quoted IMO

2018-10-04 04:01 UTC, fabpot commented on security/access_control.rst
> +
one extra blank line to be removed

2018-10-05 18:01 UTC, chalasr requested changes

2018-10-05 18:01 UTC, chalasr commented on security/access_control.rst
> +                - { path: ^/admin, roles: ROLE_USER_IP, ip: 127.0.0.1, port:8080 }
missing space before `8080`

2018-10-11 06:56 UTC, javiereguiluz commented
Thanks for implementing this feature and for providing the docs for it!

2018-10-11 07:02 UTC, merged