[MESSENGER] Async emails
symfony/symfony-docs pull request #10465
Opened 2018-10-10 07:22 UTC by Guikingone

Small addition in order to explain how the messenger can be used in order to send emails asynchronously using a message broker.

Need to be reviewed for syntax and sentences.

Thanks to @sroze for the help 😄

2018-10-10 20:37 UTC, OskarStark commented
Hmm, not sure its worth to have such a big block of text, just for deactivating the spool...
It could be done using a note block

2018-10-16 17:35 UTC, Guikingone commented
@OskarStark Yep, I'm gonna correct this asap.

2018-10-21 13:52 UTC, sroze approved these changes

2018-10-21 15:11 UTC, OskarStark commented on messenger.rst
> +    The first thing to change is the SwiftMailer configuration:
You talk about first but no second one 🤔

2018-10-21 16:55 UTC, Guikingone commented
@OskarStark Fixed with the second block about the message 😃

2019-02-11 16:46 UTC, Guikingone commented
Ok, a small update has been made about the `first` usage as signaled by @OskarStark.

2019-02-11 19:52 UTC, Lyrkan requested changes

2019-02-11 19:52 UTC, Lyrkan commented on messenger.rst
> +                    <!-- Other keys expect the spool one -->
```suggestion
                    <!-- Other keys except the spool one --> 
```

2019-02-11 19:52 UTC, Lyrkan commented on messenger.rst
> +                  // ... Other keys expect the spool one.
```suggestion
                  // ... Other keys except the spool one.
```

2019-02-11 19:52 UTC, Lyrkan commented on messenger.rst
> +    If you need to send asynchronous emails, it could be usefull to deactivate
```suggestion
    If you need to send asynchronous emails, it could be useful to deactivate
```

2019-02-11 19:52 UTC, Lyrkan commented on messenger.rst
> +        Then time to send your message which contain the email content:
```suggestion
        Then time to send your message which contains the email content:
```

2019-02-12 09:42 UTC, Guikingone commented
@javiereguiluz It seems that SfCloud fails to deploy the actual revision, normal situation?

2019-02-12 09:47 UTC, javiereguiluz commented
@Guikingone it's not normal ... so let's ping @tucksaun to see if he can take a look. Thanks!

2019-02-12 10:41 UTC, tucksaun commented
@Guikingone this PR is quite old so this branch does not contain the required files for SymfonyCloud. Try to rebase onto the latest 4.1 commit and it should work.

2019-06-28 10:03 UTC, javiereguiluz commented
I'm closing this old pull request because we recently added something like this for the new mailer component. See https://symfony.com/doc/current/mailer.html#sending-messages-async  Thanks.

2019-06-28 10:03 UTC, closed without merging