Added description for the "validation_groups" option
symfony/symfony-docs pull request #10514
Opened 2018-10-18 14:33 UTC by naitsirch

As requested in #4401 a description of the "validation_groups" option of the base ``FormType`` has been added.

2018-10-19 05:33 UTC, OskarStark commented on reference/forms/types/options/validation_groups.rst.inc
> +the option. Symfony then will pass the form when calling it::
```suggestion
the option. Symfony will then pass the form when calling it::
```

2018-10-19 05:34 UTC, OskarStark commented on reference/forms/types/options/validation_groups.rst.inc
> +    use Symfony\Component\Form\FormInterface;
```suggestion
    use Symfony\Component\Form\FormInterface;
    use Symfony\Component\OptionsResolver\OptionsResolver
```

2018-10-21 09:30 UTC, xabbuh reviewed
IIRC we also have a dedicated article about this feature. I think we should add a link to it.

2018-10-21 09:30 UTC, xabbuh commented on reference/forms/types/options/validation_groups.rst.inc
> +**type**: ``array``, ``string``, ``callable`` or ``null`` **default**: ``null``
The groups can also be a `GroupSequence` instance, can't they?

2018-10-21 09:33 UTC, xabbuh commented
These are the articles we should probably link to:

* https://symfony.com/doc/current/form/validation_groups.html
* https://symfony.com/doc/current/form/validation_group_service_resolver.html
* https://symfony.com/doc/current/form/data_based_validation.html
* https://symfony.com/doc/current/form/button_based_validation.html

2018-10-21 11:01 UTC, naitsirch commented
I'll have a look at it when I'm back from holidays ;-)

2018-11-10 17:40 UTC, nicolas-grekas commented
back? :)

2018-11-13 15:14 UTC, naitsirch commented
I have extended the documentation with the hints you gave (@OskarStark and @xabbuh). This was harder than I thould it would be, when I picked the issue ^^ but I hope it contains all needed information, now.

2018-11-13 19:16 UTC, OskarStark requested changes
Great work 👍🏻

2018-11-13 19:16 UTC, OskarStark commented on reference/forms/types/options/validation_groups.rst.inc
> +In some cases, you want to validate your groups by steps. To do this, you
groups step by step

2018-11-14 10:23 UTC, xabbuh approved these changes
with some minor comments

2018-11-15 13:47 UTC, naitsirch commented on reference/forms/types/options/validation_groups.rst.inc
> +                return $entity->getValidationGroups();
Yes this would reduce the lines of doc and shows the needed details :+1:

2018-11-15 13:53 UTC, naitsirch commented
@OskarStark and @xabbuh thanks for your improvements. I've updated the PR again.

2018-11-16 07:55 UTC, xabbuh approved these changes
I like this a lot. Great work!

2018-11-30 08:10 UTC, xabbuh commented
Thank you @naitsirch.

2018-11-30 08:11 UTC, closed without merging