min and mix can be integer or string
symfony/symfony-docs pull request #10807
Opened 2018-12-23 21:44 UTC by wuestkamp

When using this with `DateTime` the min and max can be strings.

2018-12-26 13:06 UTC, HeahDude requested changes
Thank you for proposing this change! But I would suggest to be even more explicit.

2018-12-26 13:06 UTC, HeahDude commented on reference/constraints/Range.rst
> +**type**: ``mixed``
Mixed could be anything, I would prefer to explicit both cases, something like:
```rst
**type**: ``int`` or ``string`` (date format)
```

2018-12-30 16:17 UTC, wuestkamp commented
updated.

2019-01-01 13:09 UTC, HeahDude approved these changes
Thank you!

2019-01-01 14:28 UTC, closed without merging