[Docs] use php bin/console instead of bin/console
symfony/symfony-docs pull request #10828
Opened 2019-01-02 11:38 UTC by OskarStark

2019-01-02 13:05 UTC, ghost approved these changes

2019-01-02 14:05 UTC, javiereguiluz requested changes
Oskar, thanks for this. As we discussed on Slack, we agree with this change.

However, I'm "blocking" this PR so it doesn't get merged before we fix a pending merging issue we have in 3.4 branch after having merged #10817. We're discussing about this in the Slack channel for the doc team. Thanks!

2019-01-02 14:35 UTC, OskarStark commented
Fair enough, thank you for the feedback 👌🏻

2019-01-03 11:34 UTC, javiereguiluz approved these changes

2019-01-03 11:35 UTC, javiereguiluz commented
Thank you Oskar.

2019-01-03 11:35 UTC, merged