Add docs for the Mime component
symfony/symfony-docs pull request #10886
Opened 2019-01-15 19:34 UTC by fabpot

docs for symfony/symfony#29896

2019-01-15 21:02 UTC, pborreli commented on components/mime.rst
> +    $mimeType = $mimeTypes->guessMimeType('/some/path/to/image.gif);
miss the ending quote after `gif`

2019-01-15 21:05 UTC, Pierstoval requested changes

2019-01-15 21:05 UTC, Pierstoval commented on reference/dic_tags.rst
> +class that implements :class:`Symfony\\Component\\MimeType\\MimeTypes`, register
```suggestion
class that implements :class:`Symfony\\Component\\Mime\\MimeTypeGuesserInterface`, register
```

2019-01-15 21:07 UTC, pborreli commented on reference/dic_tags.rst
> +class that implements :class:`Symfony\\Component\\MimeType\\MimeTypes`, register
same line 24

2019-01-15 21:07 UTC, Pierstoval commented on components/mime.rst
> +            // return true when the guesser is supported (might depend on the OS for instance)
What about adding this?
```suggestion
            // Return true when the guesser is supported (might depend on the OS, dependencies or PHP extensions for instance)
```

2019-01-15 21:07 UTC, Pierstoval commented on components/mime.rst
> +            // return a mime type based on the content of the file stored in $path
```suggestion
            // Return a mime type based on the content of the file stored in $path.
```

2019-01-15 21:07 UTC, Pierstoval commented on components/mime.rst
> +            // you MUST not use the filename to determine the mime type.
```suggestion
            // You MUST not use the filename to determine the mime type.
```

2019-01-15 21:08 UTC, Pierstoval commented on components/mime.rst
> +The :class:`Symfony\\Component\\MimeType\\MimeTypes` class manipulates the relationships
```suggestion
The :class:`Symfony\\Component\\Mime\\MimeTypes` class manipulates the relationships
```

2019-01-16 06:46 UTC, fabpot commented on components/mime.rst
> +    $mimeType = $mimeTypes->guessMimeType('/some/path/to/image.gif);
fixed

2019-01-16 06:47 UTC, fabpot commented on reference/dic_tags.rst
> +class that implements :class:`Symfony\\Component\\MimeType\\MimeTypes`, register
fixed

2019-01-16 06:48 UTC, fabpot commented on components/mime.rst
> +            // you MUST not use the filename to determine the mime type.
I like it this way

2019-01-16 06:48 UTC, fabpot commented on components/mime.rst
> +The :class:`Symfony\\Component\\MimeType\\MimeTypes` class manipulates the relationships
fixed

2019-01-18 15:08 UTC, OskarStark approved these changes

2019-01-19 22:09 UTC, tony-tran commented on components/mime.rst
> +You can register your own MIME type guesser by creating a class that extends
Maybe you can change `extends` by `implements` ? WDYT ?

2019-01-19 22:09 UTC, tony-tran commented on reference/dic_tags.rst
> +class that implements :class:`Symfony\\Component\\Mime\\MimeTypes`, register it
Is it `MimeTypesInterface` ?

2019-01-20 18:36 UTC, thewilkybarkid commented on components/mime.rst
> +    guessing the MIME type of a given file.
If the scope of the component is just media types rather than MIME as a whole, could it be named as such instead?

2019-02-17 09:39 UTC, OskarStark commented
Looks like the code was merged, can we merge this too and announce this new component?

2019-04-04 09:59 UTC, javiereguiluz commented
Closing because we've added all these contents to #11280, which documents the entire Mime component.

2019-04-04 09:59 UTC, closed without merging