Added a note about N+1 problem and form collections
symfony/symfony-docs pull request #11019
Opened 2019-02-20 09:57 UTC by javiereguiluz

Fixes #3374 and #4323.

2019-02-27 09:31 UTC, OskarStark requested changes

2019-02-27 09:31 UTC, OskarStark commented on reference/forms/types/entity.rst
> +    fetch related entities. This is know as the *"N + 1 query problem"* and it
s/know/known/

2019-02-27 09:31 UTC, OskarStark commented on reference/forms/types/entity.rst
> +    can be solved :ref:`joining related records <doctrine-associations-join-query>`
s/solved/solved by/ ?

2019-02-28 15:38 UTC, wouterj commented
Please note that while joining seems like a performance optimalization, it makes hydration of doctrine way more complex for *..n relations. This often reduces performance instead of optimizing it: https://tideways.com/profiler/blog/5-doctrine-orm-performance-traps-you-should-avoid

2019-04-25 07:51 UTC, javiereguiluz commented
@wouterj I read the article you linked, but decided to merge this anyways. You can see that even the article contradicts itself because in (2) they recommend to not use joins ... but in (5) they recommend to use joins.

This is a tricky issue ... but at least we now display a warning message about this so people can investigate on their own. Thanks.

2019-04-25 07:52 UTC, closed without merging