Update "Ignoring Attributes"
symfony/symfony-docs pull request #11067
Opened 2019-02-28 00:49 UTC by brucep

The `setIgnoredAttributes()` method has been [deprecated](https://github.com/symfony/serializer/blob/4.2/Normalizer/AbstractNormalizer.php#L181).

2019-02-28 06:31 UTC, OskarStark approved these changes

2019-03-06 09:24 UTC, dunglas approved these changes

2019-03-30 04:51 UTC, OskarStark requested changes
I left some minor comments 👍🏻

2019-03-30 04:51 UTC, OskarStark commented on components/serializer.rst
> +key in the ``context``` parameter of the desired serializer method::
Please use only 2 ‘ around context, currently you have 3 ‘ after “context”

2019-03-30 04:51 UTC, OskarStark commented on components/serializer.rst
> +.. versionadded:: 4.2
Please use the newly introduced deprecated directive:

.. deprecated:: 4.2

2019-04-05 14:57 UTC, javiereguiluz commented
@brucep very nice contribution! Thanks for taking care of this ... and congrats on your first Symfony Docs contribution!

2019-04-05 14:57 UTC, closed without merging