Encore (advanced): add documentation for `configureLoaderRule()` method
symfony/symfony-docs pull request #11075
Opened 2019-03-01 18:32 UTC by Kocal

Hey,

This PR add a new entry in the advanced configuration of Webpack Encore, which explains how to use the new method `configureLoaderRule()`.

Ref: https://github.com/symfony/webpack-encore/pull/509

2019-03-06 13:24 UTC, Lyrkan requested changes
Some (really minor) suggestions :)

2019-03-06 13:24 UTC, Lyrkan commented on frontend/encore/advanced-config.rst
> +The method ``configureLoaderRule()`` provide a clean way to configure Webpack loaders rules (``module.rules``, see `Configuration <https://webpack.js.org/concepts/loaders/#configuration>`_).
```suggestion
The method ``configureLoaderRule()`` provides a clean way to configure Webpack loaders rules (``module.rules``, see `Configuration <https://webpack.js.org/concepts/loaders/#configuration>`_).
```

2019-03-06 13:24 UTC, Lyrkan commented on frontend/encore/advanced-config.rst
> +This is a low-level method. Any of your modifications will be applied just before pushing the loaders rules to Webpack.
```suggestion
This is a low-level method. All your modifications will be applied just before pushing the loaders rules to Webpack.
```

2019-03-06 13:24 UTC, Lyrkan commented on frontend/encore/advanced-config.rst
> +It means that you can override configuration provided by Encore, so maybe you will break things. Be careful when using it.
```suggestion
It means that you can override the default configuration provided by Encore, which may break things. Be careful when using it.
```

2019-03-06 13:24 UTC, Lyrkan commented on frontend/encore/advanced-config.rst
> +    // Before
```suggestion
    // Manually
```

2019-03-06 13:24 UTC, Lyrkan commented on frontend/encore/advanced-config.rst
> +    // After
```suggestion
    // Using Encore.configureLoaderRule()
```

2019-03-06 19:02 UTC, Kocal commented
Thanks, that's better like this! :)

2019-03-25 23:16 UTC, weaverryan commented
Thank you @Kocal!

2019-03-25 23:16 UTC, merged