Documented the new Unique constraint
symfony/symfony-docs pull request #11247
Opened 2019-03-29 09:29 UTC by javiereguiluz

Documents https://github.com/symfony/symfony/pull/30706

2019-03-29 09:38 UTC, OskarStark requested changes
Thank you Javier, great work again.

I left 2 minor comments

2019-03-29 09:38 UTC, OskarStark commented on reference/constraints/Unique.rst
> +This constraint can be applied to any property of type array or ``\Traversable``.
```suggestion
This constraint can be applied to any property of type ``array`` or ``\Traversable``.
```

2019-03-29 09:38 UTC, OskarStark commented on reference/constraints/Unique.rst
> +
```suggestion

```

2019-03-29 09:40 UTC, OskarStark commented
> Documents symfony/symfony#30706

I think you mixed some things up, and you meant: https://github.com/symfony/symfony/pull/26555

2019-03-29 10:50 UTC, OskarStark approved these changes

2019-03-29 16:55 UTC, javiereguiluz commented
Travis is failing with this:

```
/home/travis/build/symfony/symfony-docs/reference/constraints/Unique.rst:: 
WARNING: document isn't included in any toctree
```

But the new file is included in:

https://github.com/symfony/symfony-docs/pull/11247/files#diff-5c99f0007238ae4a681869aa8713c3fdR40

I'm lost :neutral_face:

2019-03-30 04:45 UTC, OskarStark commented
I think you need to include it here

https://github.com/symfony/symfony-docs/blob/master/reference/constraints.rst

Your linked file is just an include but not an include in a toctree

2019-04-01 07:00 UTC, javiereguiluz commented
You are right Oskar! Thanks a lot. I've fixed the missing reference.

2019-04-01 07:41 UTC, OskarStark approved these changes

2019-04-01 10:11 UTC, closed without merging