[HttpClient] improve doc again
symfony/symfony-docs pull request #11650
Opened 2019-06-03 14:03 UTC by nicolas-grekas

Fixes all todos and more :)

fixes #11530.

2019-06-03 14:35 UTC, javiereguiluz approved these changes
Very nice 👏  I left some minor comments. Thanks!

2019-06-03 14:35 UTC, javiereguiluz commented on components/http_client.rst
> +A timeout can happen when e.g. DNS resolution takes to much time, when the TCP
`to much time` -> `too much time`

2019-06-03 14:35 UTC, javiereguiluz commented on components/http_client.rst
> +content pauses for too long. This can be configured by the ``timeout`` request
`configured by` -> `configured with` ?

2019-06-03 14:35 UTC, javiereguiluz commented on components/http_client.rst
> +.. tip:
Minor RST syntax issue. The `tip` directive must end with two colons.

2019-06-03 14:35 UTC, javiereguiluz commented on components/http_client.rst
> +.. note:
Same here with the `note` directive.

2019-06-03 15:26 UTC, nicolas-grekas commented on components/http_client.rst
> +A timeout can happen when e.g. DNS resolution takes to much time, when the TCP
fixed thanks

2019-06-03 17:21 UTC, wouterj approved these changes

2019-06-03 17:21 UTC, wouterj commented on components/http_client.rst
> +Dealing with network timeouts
```suggestion
Dealing with Network Timeouts
```

(title case)

2019-06-03 17:21 UTC, wouterj commented on components/http_client.rst
> +Dealing with network errors
```suggestion
Dealing with Network Errors
```

2019-06-03 17:21 UTC, wouterj commented on components/http_client.rst
> +                // do something with $response
```suggestion
                // ... do something with $response
```

2019-06-03 17:54 UTC, nicolas-grekas commented on components/http_client.rst
> +Dealing with network timeouts
fixed thanks

2019-06-04 01:33 UTC, andreia requested changes
Thanks a lot for documenting this :)
( I just made some tweaks to the cheat sheet also based on your update, thank you! :) )

2019-06-04 01:33 UTC, andreia commented on components/http_client.rst
> +Network errors (broken pipe, failed DSN resolution, etc.) are thrown as instances
```suggestion
Network errors (broken pipe, failed DNS resolution, etc.) are thrown as instances
```

2019-06-04 01:33 UTC, andreia commented on components/http_client.rst
> +including progress monitoring, DSN pre-resolution, timeout, SSL parameters, etc.
```suggestion
including progress monitoring, DNS pre-resolution, timeout, SSL parameters, etc.
```

2019-06-04 01:33 UTC, andreia commented on components/http_client.rst
> +    Timeouts control how long one is willing to wait *while the HTTP transation
```suggestion
    Timeouts control how long one is willing to wait *while the HTTP transaction
```

2019-06-04 01:33 UTC, andreia commented on components/http_client.rst
> +responses to monitor. As mentionned :ref:`previously <http-client-streaming-responses>`,
```suggestion
responses to monitor. As mentioned :ref:`previously <http-client-streaming-responses>`,
```

2019-06-04 01:33 UTC, andreia commented on components/http_client.rst
> +The option can be overriden by using the 2nd argument of the ``stream()`` method.
```suggestion
The option can be overridden by using the 2nd argument of the ``stream()`` method.
```

2019-06-04 01:33 UTC, andreia commented on components/http_client.rst
>  to ref:`choose a specific service <services-wire-specific-service>`. Each client
```suggestion
to :ref:`choose a specific service <services-wire-specific-service>`. Each client
```

2019-06-04 01:33 UTC, andreia commented on components/http_client.rst
> +    about the response. Some of them might not be know yet (e.g. ``http_code``)
```suggestion
    about the response. Some of them might not be known yet (e.g. ``http_code``)
```

2019-06-04 07:08 UTC, merged

2019-06-04 07:08 UTC, javiereguiluz commented
Nicolas, thanks a lot for contributing these improvements. Thanks to reviewers too, specially Andréia ... I fixed all the typos you reported while merging. Thanks!

2019-06-04 15:49 UTC, andreia commented
Thank you Javier! :)