Revamped the main configuration file
symfony/symfony-docs pull request #11690
Opened 2019-06-06 15:50 UTC by javiereguiluz

The main configuration file is a mess and looks outdated. This PR revamps everything and merges the main 4 config files into a single reference file. This unique file explains 80% of what you need to know about config:

* The config/ structure
* The config/packages/ files
* Config formats
* Config parameters
* Config Environments
* Env Vars
* The multiple .env files

2019-06-08 10:20 UTC, wouterj requested changes
Great work! Did a quick review, it's to big to review very thoroughly :)

2019-06-08 10:20 UTC, wouterj commented on configuration.rst
> +transforms all of them into PHP before running the application, so there's not
"transforms and caches" maybe, as transforming sounds like a performance impact?

2019-06-08 10:20 UTC, wouterj commented on configuration.rst
> +configuration file using a special syntax: wrap the parameter name with two
```suggestion
configuration file using a special syntax: wrap the parameter name in two
```

2019-06-08 10:20 UTC, wouterj commented on configuration.rst
> +            <some-package email-address="%app.admin_email%">
This is never valid XML, let's do something like this:

```xml
<some-package:config email-address="%app.admin_email%">
    <!-- ... -->
</some-package:config>
```

2019-06-08 10:20 UTC, wouterj commented on configuration.rst
> +```bash
whoa, markdown syntax 😉

2019-06-08 10:20 UTC, wouterj commented on configuration.rst
> +Configuration Environments
I think somewhere in this article, we'll have to explain that all configuration does is actually configuring the services in Service Container. And by configuring the services, all framework behaviour can be changed. This, imo, makes the user understand configuration and environments better (also in combination with service parameters explained above).

2019-06-08 10:20 UTC, wouterj commented on configuration.rst
> +   those files;
Maybe add a tip that, if the configuration is equal to some other env, using symlinks is a great idea? I.e. in our staging environment, almost everything is production settings, except from `framework.debug` and monolog. So all other `config/packages/prod/*.yaml` are symlinked to `config/packages/staging/*.yaml`

2019-06-08 10:20 UTC, wouterj commented on configuration.rst
> +once per request, to not impact performance).
I'm against putting this recommendation (or even hinting at doing stuff like this) in the documentation. Using env vars to store sensitive options is a *bad* idea (see i.e. https://www.webfactory.de/blog/storing-secrets-for-symfony-applications ).

Instead: Env vars shine for settings that change per environment, e.g. a DATABASE_URL (which isn't sensitive).

We can then add a section explaining some of the env var processors (i.e. `file:` or `json:`) to show a better practice to store sensitive data.

2019-06-08 10:20 UTC, wouterj commented on configuration/front_controllers_and_kernel.rst
> +            xmlns:doctrine="http://symfony.com/schema/dic/doctrine"
```suggestion
            xmlns:twig="http://symfony.com/schema/dic/twig"
```

2019-06-11 15:20 UTC, javiereguiluz commented
Wouter, thanks for your review. I think you were right at everything, so I made some fixes and improvements.

2019-06-12 14:37 UTC, wouterj approved these changes
Looks great!

2019-06-12 15:53 UTC, merged