Don't mention the Symfony Standard edition in the contributing docs
symfony/symfony-docs pull request #11712
Opened 2019-06-10 13:05 UTC by javiereguiluz

Fixes #11692.

2019-06-10 13:34 UTC, boite commented on contributing/community/reviews.rst
> +   problem on a clean project created with the Symfony skeleton (or website
```suggestion
   problem on a clean project created with the `Symfony skeleton`_  or `Symfony
```

2019-06-10 13:35 UTC, boite commented on contributing/community/reviews.rst
> +   skeleton) and try to understand why it exists. If the linked issue already
```suggestion
   website skeleton`_ and try to understand why it exists. If the linked issue already
```

2019-06-10 13:36 UTC, boite requested changes
:+1: but change to links a couple more mentions of the skeletons

2019-06-10 14:56 UTC, javiereguiluz commented
We usually only show the link the first time something is included in the article ... but these "skeletons" are still not well-known by lots of people, so let's include the links always. Thanks.

2019-06-10 15:13 UTC, boite requested changes
Whoops! Sorry for making you do more work; one more change for the sake of consistency.  I've read through the document in full this time. Looks great! Thank you @javiereguiluz.

2019-06-10 15:13 UTC, boite commented on contributing/community/reviews.rst
> +   create one based on one `Symfony skeleton`_.
```suggestion
   create one based on the `Symfony skeleton`_ (or the `Symfony website skeleton`_).
```

2019-06-11 07:18 UTC, javiereguiluz commented on contributing/community/reviews.rst
> +   create one based on one `Symfony skeleton`_.
Added too. Thanks.

2019-06-11 10:30 UTC, boite approved these changes

2019-06-11 14:24 UTC, merged