More updates related to Symfony configuration
symfony/symfony-docs pull request #11803
Opened 2019-06-21 11:28 UTC by javiereguiluz

This makes several changes related to config.

1) Now that the TOC is displayed so prominently, it's easy to spot things to improve in the article hierarchy. So, I've made the following changes (left: before, right: after):

![image](https://user-images.githubusercontent.com/73419/59919547-03828980-9428-11e9-8d2f-2890c75b6ae1.png)

2) the multiple ".env" files section has been reworded and now it follows the same structure as the comments of the associated recipe, which I think are better.

3) The main Confgi article now explains the different kinds of params you can define ... so we've deleted the service_container/parameters.rst article which is no longer needed.

4) The main Config article adds a new section to explain how to get config values in services and controllers.

With these changes I considered finished the main Config article. Thanks.

2019-06-29 14:02 UTC, weaverryan requested changes
Nice work! Looking at the new table of contents:

* merge keep going and learn more 
* configuration formats and importing configuration seem to high up on the article. It means there’s a lot of xml and boring format stuff to start this article.

Cheers!

2019-07-02 20:48 UTC, noniagriconomie commented on configuration.rst
> +the only mandatory file and each file overrides all the previous ones:
Each file content overrides the previous one

2019-07-02 20:48 UTC, noniagriconomie commented on configuration.rst
> +* **YAML**: simple, clean and readable, but requires using a dedicated parser.
Agreed, this can make yaml being not used
Also with ide integrations yaml have also completion

2019-07-02 20:48 UTC, noniagriconomie commented on service_container.rst
> +    You can only set a parameter before the container is compiled: not at run-time.
What about replacing : by ,

2019-07-02 20:48 UTC, noniagriconomie commented on configuration.rst
> +    env vars created by the ``.env`` files.
Defined instead created ?

2019-07-02 20:48 UTC, noniagriconomie commented on configuration.rst
> +    The real environment variables defined in the server always win over the
Take precedence instead of win ?

2019-07-02 20:48 UTC, noniagriconomie commented on configuration.rst
> +                    $contentsDir: '%app.contents_dir%'
What about also showing an example without binding ? With direct injection

2019-07-29 08:25 UTC, javiereguiluz commented
I've made most of the suggested changes, so I think this is ready for the final review. Thanks.

2019-07-31 08:08 UTC, merged