[Process] allow writing "prepared" command line.
symfony/symfony-docs pull request #11802
Opened 2019-06-21 07:25 UTC by Simperfit

This documents the re-pushed prepared command line with a new style of writing it that does not break anything.

2019-06-21 07:39 UTC, OskarStark commented on components/process.rst
> +Using the prepared command lines
„Using a Prepared Command Line“

2019-06-21 07:39 UTC, OskarStark commented on components/process.rst
> +  $process->run(null, array('name' => 'elsa'));
Please use short array syntax

2019-06-21 07:39 UTC, OskarStark commented on components/process.rst
> +Which means that you can use placeholder in order to have a process that can be changed only with the values and without changing the php code. The component will not escape the characters, you are r
2 spaces before the last word

2019-06-21 07:39 UTC, OskarStark commented on components/process.rst
> +Which means that you can use placeholder in order to have a process that can be changed only with the values and without changing the php code. The component will not escape the characters, you are r
I would put the whole text parts before the Code example and not talk again about „the component“

2019-06-26 07:27 UTC, fabpot commented on components/process.rst
> +--------------------------------
should the same length as the title itself to be valid

2019-06-26 07:28 UTC, fabpot requested changes

2019-06-26 07:28 UTC, fabpot commented on components/process.rst
> +This component also provides a way to use the process command with prepared using the double brackets notations:
missing word after `with prepared`

2019-06-26 07:28 UTC, fabpot commented on components/process.rst
> +This component also provides a way to use the process command with prepared using the double brackets notations:
double bracket notation

2019-06-26 07:28 UTC, fabpot commented on components/process.rst
> +Which means that you can use placeholder in order to have a process that can be changed only with the values and without changing the php code.
use a placeholder?

2019-06-26 07:28 UTC, fabpot commented on components/process.rst
> +Which means that you can use placeholder in order to have a process that can be changed only with the values and without changing the php code.
PHP

2019-08-01 10:09 UTC, OskarStark commented
@Simperfit do you find some time to finish this PR? 😃

2019-08-06 12:51 UTC, Simperfit commented
Ill do it asap ;)

2019-08-15 10:03 UTC, OskarStark commented
Thanks for your work on this new feature!

2019-08-15 10:13 UTC, closed without merging

2019-08-16 11:12 UTC, Simperfit commented
Thanks @OskarStark

2019-08-26 11:41 UTC, xabbuh commented on components/process.rst
> +This component also provides a way to use the process command with prepared using the double brackets notations:
What does "double bracket notation" mean?