feature: add docs for extra fields
symfony/symfony-docs pull request #11814
Opened 2019-06-23 09:47 UTC by Simperfit

Fix #11810

2019-06-23 10:34 UTC, OskarStark commented on security/ldap.rst
> +
Maybe a note on how it behaves if an extra field isn’t available? Will it be null or does it throw an exception?

2019-06-28 18:35 UTC, weaverryan requested changes

2019-06-28 18:35 UTC, weaverryan commented on security/ldap.rst
> +This is the custom fields to pull from the LDAP server. If the fields does not
Defines the custom fields...

... If any field does not exist, an Invalid... will be thrown.

2019-07-02 06:55 UTC, merged

2019-07-02 06:56 UTC, javiereguiluz commented
Thanks Hamza for this contribution! I made Ryan's suggested changes while merging and I also added the missing "versionadded:: 4.4" directive.

2019-07-02 06:57 UTC, Simperfit commented
Thanks Javier, I forgot about Ryan's suggestion.