[PhpUnitBridge] Add docs for ClassExistsMock
symfony/symfony-docs pull request #11903
Opened 2019-07-07 08:10 UTC by ro0NL

fixes https://github.com/symfony/symfony-docs/issues/10528

2019-07-07 13:53 UTC, OskarStark requested changes
Nice addition to the docs, thank you Roland 👍🏻👌🏻

2019-07-07 13:53 UTC, OskarStark commented on components/phpunit_bridge.rst
> +            // ...
This could be removed IMO

2019-07-07 13:53 UTC, OskarStark commented on components/phpunit_bridge.rst
> +classes, interaces and/or traits for the code to run::
interfaces

2019-07-07 13:53 UTC, OskarStark commented on components/phpunit_bridge.rst
> +are installed during tests) looks like::
... would look like::

2019-07-07 13:53 UTC, OskarStark commented on components/phpunit_bridge.rst
> +    class MyTest extends TestCase
class MyClassTest

2019-07-07 13:53 UTC, OskarStark commented on components/phpunit_bridge.rst
> +    use PHPUnit\Framework\TestCase;
Please add use statement for the MyClass

2019-07-07 13:53 UTC, OskarStark commented on components/phpunit_bridge.rst
> +            $result = $class->hello(); // "The dependency bahavior."
Could you please use an assertion here? Otherwise the code example is not valid when someone copies it, thank you

2019-07-07 13:53 UTC, OskarStark commented on components/phpunit_bridge.rst
> +    class MyTest extends TestCase
class MyClassTest

2019-07-07 13:53 UTC, OskarStark commented on components/phpunit_bridge.rst
> +            $result = $class->hello(); // "The default bahavior."
Please an assertion

2019-07-07 13:53 UTC, OskarStark commented on components/phpunit_bridge.rst
> +            // ...
Could be removed

2019-07-07 13:57 UTC, OskarStark commented on components/phpunit_bridge.rst
> +            $result = $class->hello(); // "The dependency bahavior."
Hmm I saw here 
https://github.com/symfony/symfony-docs/pull/11904#pullrequestreview-258628191
that we didn’t use an assertion here. But I would prefer using one in the other examples too.

WDYT @javiereguiluz

2019-07-07 14:05 UTC, ro0NL commented
@OskarStark thanks for review, i'll left the remaining points open for consistency with the other examples. I think the intend is clear ...

2019-07-07 18:25 UTC, OskarStark approved these changes

2019-07-30 15:46 UTC, xabbuh approved these changes

2019-07-31 06:37 UTC, OskarStark commented
Thank you Roland.

2019-07-31 06:37 UTC, merged