Add docs on NamedAddress::fromString
symfony/symfony-docs pull request #12128
Opened 2019-08-09 11:48 UTC by gisostallenberg

See https://github.com/symfony/symfony/issues/33086

2019-08-09 12:05 UTC, OskarStark requested changes
Nice addition, can you please apply my suggestions?

2019-08-09 12:05 UTC, OskarStark commented on mailer.rst
> +A NamedAddress can be created from a string
```suggestion
A ``NamedAddress`` can be created from a single string::
```

2019-08-09 12:05 UTC, OskarStark commented on mailer.rst
> +    // ...
```suggestion

```

2019-08-09 12:05 UTC, OskarStark commented on mailer.rst
> +    //
```suggestion
    // ...
```

2019-08-09 12:05 UTC, OskarStark commented on mailer.rst
> +    ->from(NamedAddress::fromString('Fabien <fabien@example.com>'))
```suggestion
        ->from(NamedAddress::fromString('Fabien <fabien@example.com>'))
```

2019-08-09 12:12 UTC, gisostallenberg commented
> Nice addition, can you please apply my suggestions?

Sure, done

2019-08-09 12:28 UTC, OskarStark commented on mailer.rst
> +    // ...
```suggestion
        // ...
```

2019-08-09 12:29 UTC, OskarStark commented on mailer.rst
> +    // ...
just one minor comment :)

2019-08-22 09:19 UTC, gisostallenberg commented
@OskarStark updated this according to https://github.com/symfony/symfony/pull/33091

2019-08-22 09:35 UTC, OskarStark commented
Can you please apply my comment and fix the one mentioned by `DOCtor-RST`? Thanks.

2019-08-23 07:06 UTC, gisostallenberg commented
> Can you please apply my comment and fix the one mentioned by `DOCtor-RST`? Thanks.

@OskarStark done

2019-08-23 07:06 UTC, OskarStark approved these changes

2019-09-02 11:10 UTC, merged

2019-09-02 11:11 UTC, javiereguiluz commented
Giso, thanks for adding the docs for this feature that you also contributed. Congrats on your first Symfony Docs contribution!