Update cache.rst
symfony/symfony-docs pull request #12181
Opened 2019-08-15 23:48 UTC by pavelmaca

*Using Cache Tags* section has invalid example. Should use TagAwareCacheInterface.

2019-08-16 05:42 UTC, OskarStark commented
@Nyholm could you please verify this docs change? Thank you 😃

2019-08-16 06:35 UTC, OskarStark approved these changes
Thanks @pavelmaca for the change and @Nyholm for the review 👍

2019-08-16 06:36 UTC, Nyholm commented
Oh wait

2019-08-16 06:54 UTC, Nyholm requested changes
Hey, 
Thank you for this PR. The `TagAwareCacheInterface` is an interface for the cache adapter. What we get passed to our function is a cache item.

2019-08-16 06:56 UTC, Nyholm commented
:-1: (to be clear)

2019-08-16 07:00 UTC, OskarStark commented
@pavelmaca can you explain a bit why you did this change or which error do you have?

2019-08-16 07:53 UTC, Nyholm commented
I did find a bug when testing this out. Maybe that was what @pavelmaca experienced?

https://github.com/symfony/symfony/issues/33201

2019-08-16 08:10 UTC, Nyholm commented on cache.rst
> +    $value0 = $pool->get('item_0', function (TagAwareCacheInterface $item) {
It is the `$pool` that should be a `TagAwareCacheInterface`. 

@pavelmaca could you update this PR a little? Could you wrap this code into a function or a class and make sure `$pool` is a `TagAwareCacheInterface`?

2019-08-16 08:44 UTC, Nyholm commented
More info here: https://github.com/symfony/symfony/issues/33201

2019-08-16 10:04 UTC, pavelmaca commented
@Nyholm Your findings are correct in symfony/symfony#33201

Updated doc with function and autowired $pool

2019-08-16 10:05 UTC, OskarStark commented on cache.rst
> +    // using autowiring
```suggestion

```

2019-08-16 10:39 UTC, Nyholm requested changes
Oscar, what do you think? Should we create a class and use constructor injection or is that overkill?

It would be more clear since injection to a function is generally only used with controllers.

2019-08-16 10:39 UTC, Nyholm commented on cache.rst
> +    public function listProducts(TagAwareCacheInterface $pool)
Update `$pool` to `$myCachePool` to match the config below.

2019-08-16 10:39 UTC, Nyholm commented on cache.rst
> +    public function listProducts(TagAwareCacheInterface $pool)
Maybe use a more generic name than `listProducts`. Maybe `foo`?

2019-08-20 07:04 UTC, OskarStark commented
> Oscar, what do you think? Should we create a class and use constructor injection or is that overkill?

I think this would make sense in this case, otherwise this must be a tage with controller arguments tag 👍 

👍 for a class + injection

2019-10-01 14:30 UTC, javiereguiluz commented
I tried to merge this but I couldn't fix the conflicts ... so I created in #12398 a new pull request with these changes and all the other changes requested by Tobias. @pavelmaca I kept your original commit, so you'll get credit for this contribution. Thanks.

2019-10-01 14:30 UTC, closed without merging