[Messenger] Adds a note InMemoryTransports will be reset in tests
symfony/symfony-docs pull request #12224
Opened 2019-08-22 09:21 UTC by smoench

2019-08-22 09:40 UTC, OskarStark requested changes

2019-08-22 09:40 UTC, OskarStark commented on messenger.rst
> +        All ``in-memory`` transports will be reset automatically after each test method
```suggestion
        All ``in-memory`` transports will be resetted automatically after each test method
```

2019-08-22 09:40 UTC, OskarStark commented on messenger.rst
> +        which test class is based on the ``Symfony\Bundle\FrameworkBundle\Test\KernelTestCase``.
```suggestion
        which extends :class:`Symfony\\Bundle\\FrameworkBundle\\Test\\KernelTestCase`.
```

2019-08-22 09:54 UTC, OskarStark requested changes

2019-08-22 09:54 UTC, OskarStark commented on messenger.rst
> +        All ``in-memory`` transports will be reset automatically after each test **in** test classes based on the
```suggestion
        All ``in-memory`` transports will be reset automatically after each test **in**
```

2019-08-22 09:54 UTC, OskarStark commented on messenger.rst
> +        ``Symfony\Bundle\FrameworkBundle\Test\KernelTestCase`` or ``Symfony\Bundle\FrameworkBundle\Test\WebTestCase``
```suggestion
        test classes extending :class:`Symfony\\Bundle\\FrameworkBundle\\Test\\KernelTestCase`
        or :class:`Symfony\\Bundle\\FrameworkBundle\\Test\\WebTestCase`.
```

2019-08-23 07:03 UTC, smoench commented on messenger.rst
> +        All ``in-memory`` transports will be reset automatically after each test **in** test classes based on the
Done

2019-08-23 07:03 UTC, smoench commented on messenger.rst
> +        ``Symfony\Bundle\FrameworkBundle\Test\KernelTestCase`` or ``Symfony\Bundle\FrameworkBundle\Test\WebTestCase``
Done

2019-08-23 07:06 UTC, OskarStark approved these changes

2019-08-24 08:41 UTC, OskarStark commented
Thank you Simon.

2019-08-24 08:42 UTC, merged

2019-08-24 08:46 UTC, smoench commented
Thank you, @OskarStark!