Add docs for DateTimeZoneNormalizer
symfony/symfony-docs pull request #12271
Opened 2019-09-05 07:25 UTC by williamjehanne

2019-09-05 07:47 UTC, OskarStark commented
This PR must target 4.3 branch, but don't worry, we can do this while merging

2019-09-05 07:48 UTC, OskarStark approved these changes

2019-09-25 10:37 UTC, xabbuh requested changes

2019-09-25 10:37 UTC, xabbuh commented on components/serializer.rst
> +    By default, it uses the `RFC3339`_ format.
Is this true? If I don't miss anything the identifiers used by PHP are not based on an RFC, right?

2019-09-26 14:21 UTC, merged

2019-09-26 14:23 UTC, javiereguiluz commented
@williamjehanne thanks for this contribution!

@xabbuh you are right. I removed the RFC reference while merging. Thanks.