Section about configuring Circular Reference Handler
symfony/symfony-docs pull request #12431
Opened 2019-10-05 16:05 UTC by pskt

Added section about enabling Circular Reference Handler in Symfony framework app.
It wasn't so obvious for me that Circular Reference Handler can be defined app-wide in configuration, so I think this section should help other people with that.

2020-10-27 15:03 UTC, Matts requested changes

2020-10-27 15:03 UTC, Matts commented on serializer.rst
> +The use of :ref:`circular reference handler <component-serializer-handling-circular-references>` service can be defined
```suggestion
The use of the :ref:`circular reference handler <component-serializer-handling-circular-references>` service can be defined
```

2020-10-27 15:03 UTC, Matts commented on serializer.rst
> +in the configuration using :ref:`circular_reference_handler <reference-serializer-circular_reference_handler>` option.
```suggestion
in the configuration using the :ref:`circular_reference_handler <reference-serializer-circular_reference_handler>` option.
```

2020-10-27 15:03 UTC, Matts commented on serializer.rst
> +The service has to implement magic ``__invoke($object)`` method, like in example::
```suggestion
A circular reference handler service has to implement magic ``__invoke($object)`` method, like in example:
```

2020-10-30 15:21 UTC, Matts approved these changes

2020-10-30 15:22 UTC, Matts commented
Hey @pskt, LGTM 🚀

2025-07-01 19:43 UTC, OskarStark commented
Thank you for your contribution\! We're closing this PR as it's from 2019 and hasn't seen recent activity or interest. If this documentation is still needed, please feel free to open a new PR against the current version of the docs.

2025-07-01 19:43 UTC, closed without merging