[Form] Added docs for alpha3 option in CountryType and LanguageType
symfony/symfony-docs pull request #12441
Opened 2019-10-07 15:27 UTC by creiner

Here are the documentation parts for the PR: 
https://github.com/symfony/symfony/pull/33791
Hope I didn't make any mistakes.. :-)

2019-10-08 07:47 UTC, OskarStark requested changes

2019-10-08 07:47 UTC, OskarStark commented on reference/forms/types/options/alpha3.rst.inc
> +~~~~~~~~~~~~~~~~~~~~~~~~~
Please make the underline the same length as the headline itself

2019-10-08 20:28 UTC, OskarStark approved these changes

2019-10-09 07:17 UTC, merged

2019-10-09 07:19 UTC, javiereguiluz commented
@creiner thanks a lot for this contribution! You did it great ... but we added some minor tweaks while merging to add the `versionadded:: 4.4` directive and add some links to the Wikipedia lists of 2-letter and 3-letter codes.

Congrats on your first Symfony Docs contribution!

2019-10-10 06:46 UTC, ro0NL commented
@javiereguiluz `alpha3` option is currently documented for CountryType (https://symfony.com/doc/4.4/components/intl.html#country-names) but is wrong for LanguageType which uses ISO 639 (https://symfony.com/doc/4.4/components/intl.html#language-and-script-names)

so https://symfony.com/doc/4.4/reference/forms/types/language.html#alpha3 is wrong currently

2019-10-10 07:02 UTC, javiereguiluz commented
I'm sorry but I don't understand your comment. This is about the Form component ... but you are linking to Intl, so I'm confused:

Should this be documented only in Intl but not in Form?  Only in Form but not in Intl? In both but differently? Thanks.

2019-10-10 07:10 UTC, ro0NL commented
i mean both LanguageType and CountryType refer to  ISO 3166, whereas LanguageType should refer ISO 639

2019-10-11 09:42 UTC, javiereguiluz commented
@creiner this PR is already merged, so a new one should be created. I'm sorry!