[Serializer] Document new `cast_primitive_types` context option
symfony/symfony-docs pull request #12471
Opened 2019-10-14 04:15 UTC by bkotos

I needed a way to cast data to the expected type for each corresponding property.  For my specific use case, I was querying data from MySQL via PDO, which only returns arrays of `string` values.

2019-11-02 13:49 UTC, OskarStark requested changes

2019-11-02 13:49 UTC, OskarStark commented on components/serializer.rst
> +corresponding property's type::
```suggestion
corresponding property types::
```

2019-11-02 13:49 UTC, OskarStark commented on components/serializer.rst
> +    $obj = $serializer->denormalize(
```suggestion
    $car = $serializer->denormalize(
```

2019-11-02 13:49 UTC, OskarStark commented on components/serializer.rst
> +            'isInsured' => '0'
```suggestion
            'isInsured' => '0',
```

2019-11-02 13:49 UTC, OskarStark commented on components/serializer.rst
> +    dump($obj);
```suggestion

    dump($car);
```

2019-11-02 13:49 UTC, OskarStark commented on components/serializer.rst
> +         */
```suggestion
         /** @var string */
```

2019-11-02 13:49 UTC, OskarStark commented on components/serializer.rst
> +         */
```suggestion
         /** @var int */
```

2019-11-02 13:49 UTC, OskarStark commented on components/serializer.rst
> +         */
```suggestion
         /** @var float */
```

2019-11-02 13:49 UTC, OskarStark commented on components/serializer.rst
> +         */
```suggestion
         /** @var bool */
```

2019-11-02 13:49 UTC, OskarStark commented on components/serializer.rst
> +         */
```suggestion
         /** @var bool */
```

2020-10-16 07:24 UTC, xabbuh commented
closing here as the related code PR has been closed

2020-10-16 07:24 UTC, closed without merging