Add new WeekType Documentation
symfony/symfony-docs pull request #12584
Opened 2019-11-03 14:45 UTC by dFayet

Documents new https://github.com/symfony/symfony/pull/32061 feature

2019-11-06 22:06 UTC, OskarStark requested changes

2019-11-06 22:06 UTC, OskarStark commented on reference/forms/types/week.rst
> +==================
Please shorten this underline to the length of the headline

2019-11-06 22:06 UTC, OskarStark commented on reference/forms/types/week.rst
> +    The ``WeekType`` Type was introduced in Symfony 4.4.
Type -> type

2019-11-06 22:06 UTC, OskarStark commented on reference/forms/types/week.rst
> +ISO 8601 week number  (e.g. ``1984-W05``).
Please make ISO 8601 a link to:
https://en.m.wikipedia.org/wiki/ISO_8601

Please remove one whitespace before „(„

2019-11-08 10:21 UTC, OskarStark approved these changes

2019-11-09 14:45 UTC, merged

2019-11-09 14:46 UTC, wouterj commented
Thanks a lot for taking care of documenting your new feature! This is great documentation. I've now merged it and only did a few very very minor tweaks in 76076cfde.

Hope to see you back in the future with more contributions!