[Cache] Custom pool
symfony/symfony-docs pull request #12904
Opened 2020-01-09 10:21 UTC by Guikingone

Hi everyone 👋 

It seems that when defining a custom pool, the documenation is talking about an array adapter when the used one is the filesystem, the question is, do we need to reword it as filesystem in the text of change the code? 🤔 

Thanks for the feedback 🙂

2020-01-30 11:00 UTC, OskarStark commented
@Nyholm could you please give a review here? Thanks 🙏

2020-01-30 12:50 UTC, Nyholm requested changes
Hey. 

Thank you for finding this mistake. I agree that it should be changed. 
Maybe update the text instead of the config. 

I also see that you introduce a cache chain here. That is not relevant for section.

2020-01-30 12:50 UTC, Nyholm commented on cache.rst
> +            app.my_cache_chain_adapter:
There is no need to introduce a cache chain here. It i explained later.

2020-03-12 16:45 UTC, javiereguiluz commented
Guillaume, thanks for this ... but at the end we decided to follow Tobias suggestion and change instead the text description and keep the original code. Thanks!

2020-03-12 16:45 UTC, closed without merging

2020-03-12 16:49 UTC, Guikingone commented
No problem @javiereguiluz, sorry for the delay, I was working on something else and I've forgot this PR, really sorry 🙁