Update setup.rst
symfony/symfony-docs pull request #12933
Opened 2020-01-10 20:10 UTC by xlefebure

2020-01-12 12:35 UTC, javiereguiluz commented
Xavier, thanks for this contribution. Personally I'm not sure about this change because the version constraint is usually defined next to the dependency ... but let's wait for more opinions.

2020-01-12 12:40 UTC, xlefebure commented
Hi,

I tried the command in the documentation but it wasn't work for me.
The new command worked.
Let's see if other people have this problem too.

2020-01-15 18:19 UTC, HeahDude requested changes

2020-01-15 18:19 UTC, HeahDude commented on setup.rst
> -    $ composer create-project symfony/website-skeleton:^4.4 my_project_name
There is indeed a confusion with the `require` argument syntax, could you please keep the minor version though?

2020-03-12 16:51 UTC, javiereguiluz commented
I don't know what to do here:

I've run these two commands and both worked perfectly:

```
composer create-project symfony/website-skeleton:^4.4 my_project_name

composer create-project symfony/website-skeleton:"^4.4" my_project_name
```

I'm using macOS. I remember some issues in the past with Windows. @xlefebure maybe you were using Windows when running the command?

2020-03-12 16:54 UTC, xlefebure commented
@javiereguiluz Yes, I was on Windows 10 at this moment.

2020-03-12 16:55 UTC, javiereguiluz commented
Can you try if this command works for you? (note the quotes around the number version):

```bash
composer create-project symfony/website-skeleton:"^4.4" my_project_name
```

2020-03-20 13:56 UTC, xlefebure commented
Hi,

It's working !

ᐧ

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le jeu. 12 mars 2020 à 17:55, Javier Eguiluz <notifications@github.com> a
écrit :

> Can you try if this command works for you? (note the quotes around the
> number version):
>
> composer create-project symfony/website-skeleton:"^4.4" my_project_name
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/symfony/symfony-docs/pull/12933#issuecomment-598297560>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFZAGE4KTHEUG5IN2XKD46TRHEHZDANCNFSM4KFMWSMA>
> .
>

2020-09-09 18:11 UTC, merged

2020-09-09 18:11 UTC, javiereguiluz commented
Thanks for confirming that the quotes make this problem disappear. We did that change while merging. Thanks!