Added documentation for the priority access decision strategy
symfony/symfony-docs pull request #12956
Opened 2020-01-18 14:00 UTC by aschempp

fixes https://github.com/symfony/symfony-docs/issues/12830

2020-01-18 14:26 UTC, HeahDude requested changes
Thanks for your contributions., looks good!

2020-01-18 14:26 UTC, HeahDude commented on components/security/authorization.rst
> +``priority``
We also need a `versionadded` directive

2020-01-18 14:27 UTC, HeahDude commented on components/security/authorization.rst
> +``priority``
You can see how here https://symfony.com/doc/current/contributing/documentation/format.html#new-features-behavior-changes-or-deprecations

2020-01-20 11:02 UTC, aschempp commented
I have added the versionadded directive

2020-01-20 11:37 UTC, OskarStark commented on components/security/authorization.rst
> +    The priority version strategy was introduced in Symfony 5.1.
```suggestion
        The priority version strategy was introduced in Symfony 5.1.
```

2020-01-20 11:37 UTC, OskarStark commented on components/security/authorization.rst
> +
```suggestion

```

2020-01-20 11:38 UTC, OskarStark commented on security/voters.rst
> +    The priority version strategy was introduced in Symfony 5.1.
```suggestion
        The priority version strategy was introduced in Symfony 5.1.
```

2020-02-04 20:10 UTC, HeahDude approved these changes

2020-02-04 20:38 UTC, OskarStark approved these changes

2020-02-05 05:58 UTC, OskarStark commented
Thanks for your work on this new feature!

2020-02-05 05:58 UTC, merged