Update authentication.rst
symfony/symfony-docs pull request #13072
Opened 2020-02-07 15:12 UTC by MaharishiCanada

I think we do not have to implement the ListenerInterface anymore in the example class SomeAuthenticationListener.

2020-02-07 15:17 UTC, MaharishiCanada commented
OK, it's the same as  #13069 .

2020-02-08 13:56 UTC, ghost reviewed
> I think we do not have to implement the ListenerInterface anymore

Correct. It was deprecated in `4.4` and removed in `5.0`. The [upgrade guide](https://github.com/symfony/symfony/blob/master/UPGRADE-5.0.md#security) suggests extending to `AbstractListener` but in the Slack community I have seen a few posts in support about making them callables:

```php
use Symfony\Component\HttpKernel\Event\RequestEvent;

class MyListener
{
    public function __invoke(RequestEvent $event)
    {
        // code
    }
}
```

WDYT?

2020-02-09 11:23 UTC, HeahDude requested changes
Thank you for that PR!
Could you check other places mentioned in #13069 as well?
I also agree that we should use `__invoke` in examples (https://github.com/symfony/symfony-docs/pull/13072#pullrequestreview-355548983), the PR should target 4.4 though, so devs starting projects on the LTS don't use deprecated code. Thanks!

2020-02-09 11:28 UTC, HeahDude commented
Forget my comment, we can close here in favor of #13083.

2020-02-10 19:29 UTC, HeahDude commented
Closing since #13083 has been merged. Thanks!

2020-02-10 19:29 UTC, closed without merging