Non-standard adder/remover methods
symfony/symfony-docs pull request #13137
Opened 2020-02-14 17:15 UTC by Korbeil

Will add documentation about non-standard adder/remover methods for PropertyAccessor.

Related to #13023 and https://github.com/symfony/symfony/issues/9336

2020-10-22 11:47 UTC, wouterj commented
Fyi: Marked as "waiting code merge" as I think it depends on https://github.com/symfony/symfony/pull/38515

2020-10-22 11:49 UTC, Korbeil commented
@wouterj I does not depends on that PR, it was dependant on https://github.com/symfony/symfony/pull/30704 which I finished a long time ago ^^

2020-10-22 12:00 UTC, wouterj commented
Oh, I'm sorry. I thought that PR only did changes to PropertyInfo and missed the big changes to the PropertyAccessor.

2020-10-22 12:06 UTC, wouterj requested changes
Thank you @Korbeil! I've proposed some changes to slightly improve the code example.

Can you please also add a versionadded directive like:

```rst
.. versionadded:: 5.1

    Support for non-standard adder/remover methods was introduced in Symfony 5.1.
```

And at last, please rebase this PR on the 5.1 branch (using `git rebase --onto origin/5.1 origin/master`).

If you don't have time to work on these changes (or something is unclear), please tell me and I'll finish this PR.

2020-10-22 12:06 UTC, wouterj commented on components/property_access.rst
> +*adder* and *remover* methods. But sometimes theses methods doesn't use the standard ``add`` and ``remove`` prefix::
I think we can reduce this to: ```Sometimes, adder and remover methods don't use the standard ``add`` or ``remove`` prefix, like in this example::```

2020-10-22 12:06 UTC, wouterj commented on components/property_access.rst
> +        }
```suggestion
        // ...
```

I would propose to reduce this code example a bit and only focus on the important things: the custom method names

2020-10-22 12:06 UTC, wouterj commented on components/property_access.rst
> +    $propertyAccessor->setValue($person, 'peoples', ['kevin', 'wouter']);
Please add the necessary use statements for these classes (to make it more clear that they are in different components).

2020-10-22 12:06 UTC, wouterj commented on components/property_access.rst
> +Instead of call ``add<SingularOfThePropertyName>()`` and ``remove<SingularOfThePropertyName>()``, the PropertyAccess
```suggestion
Instead of calling ``add<SingularOfThePropertyName>()`` and ``remove<SingularOfThePropertyName>()``, the PropertyAccess
```

2020-10-23 11:46 UTC, Korbeil commented
@wouterj I made all requested changes

2020-10-23 11:48 UTC, wouterj approved these changes
Thank you for the quick response @Korbeil!

2020-10-25 14:59 UTC, maxhelias approved these changes

2020-10-31 23:28 UTC, wouterj commented
Hi @Korbeil. I was about to merge this PR but I'm lost in all the core commits and PRs again.. This PR has got the "4.4" milestone, which makes me think it should be merged in 4.4. But it appears like the feature is introduced in 5.1. Can you please confirm which version should be used?

2020-11-01 20:37 UTC, Korbeil commented
@wouterj, As you can see in related PR: https://github.com/symfony/symfony/pull/30704 It was firstly tagged in `v5.1.0-BETA1`

Or maybe it's my github enhanced addon that shows it ? 
![image](https://user-images.githubusercontent.com/944409/97814832-5f028f80-1c8a-11eb-8e6c-312843df55ac.png)

2020-11-01 21:26 UTC, wouterj commented
Oh, I don't have that feature. That seems extremely useful :smile: 

![image](https://user-images.githubusercontent.com/749025/97815811-1a2e2700-1c91-11eb-9fc4-27781b253f21.png)

You probably submitted this PR when 4.4 was in development, causing a doc team member to flag it as `4.4` a bit too quickly. I'll merge in 5.1 then, thanks for confirming.

2020-11-05 14:35 UTC, merged

2020-11-05 14:35 UTC, wouterj commented
Yay, and finally it is merged. Thanks for your patience & contributions @Korbeil!