Add an opcache preload warning (7.4+)
symfony/symfony-docs pull request #13189
Opened 2020-02-19 23:18 UTC by JKapitein

As someone who spent a few hours trying to get preloading working on a large/complex project, I feel like a warning might be helpful to some since the docs currently advertise it as "working out of the box".

Current version is noted as 7.4.3 since that version was tagged 1.5 days ago as of this PR, and I spent time with both 7.4.2 (where I hit the opcache.preload_user bug) and a self-built version of 7.4.3 (where it just segfaulted until I commented specific vendor code, and once it did run it was a lot slower than without preloading since I was forced to use the default vendor and cache folders to get it working)

Considering the actual release of 7.4.3 should be today, I will test again with those binaries and close this PR if needed.

2020-02-20 07:21 UTC, OskarStark requested changes
Prevent merge, until we get feedback from your side (based on 7.4.3)

2020-02-23 15:03 UTC, JKapitein commented
> Prevent merge, until we get feedback from your side (based on 7.4.3)

Still not working on release version from Surý's Ubuntu build. At this point I'd say it's safe to add the warning and re-evaluate on the next patch release.

To add to my original post, it wasn't just commenting vendor code, I also had to make some changes to the [Preloader class](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/DependencyInjection/Dumper/Preloader.php) before it worked.

2020-02-24 07:11 UTC, OskarStark commented
What do you think @nicolas-grekas?

2020-02-24 07:15 UTC, nicolas-grekas commented
I think we shouldn't merge this: it's more scary than informative, and won't be true soon (hopefully). Doc should be about stable facts, this isn't to me.

2020-02-24 07:17 UTC, nicolas-grekas commented
Note that anything we find to reproduce the crash should be reported to bugs.php.net

2020-02-25 10:14 UTC, JKapitein commented
To me it was more about reflecting the fact that preloading is still often broken, including in the latest PHP release. Currently the Symfony docs present it as a thing you can enable on your (prod) environment as long as you have PHP 7.4, which for many may not be the case.

Maybe a "softer" color for the notice, like yellow? I believe `caution` was red.

If you disagree, you may close this PR @nicolas-grekas , we're just waiting on PHP anyway

2020-03-12 16:14 UTC, javiereguiluz commented
I agree with Nicolas, let's close this for now. It's true that this PHP feature is buggy ... but it's quickly improving with each new version release. Thanks.

2020-03-12 16:14 UTC, closed without merging