LoginFormAuthenticator example updated
symfony/symfony-docs pull request #13306
Opened 2020-03-04 22:04 UTC by carlcasbolt

RouterInterface has been replaced with UrlGeneratorInterface

2020-03-05 01:48 UTC, skmedix commented on security/form_login_setup.rst
> +
```suggestion

```

2020-03-05 01:53 UTC, skmedix requested changes

2020-03-05 01:53 UTC, skmedix commented on security/form_login_setup.rst
> +
Please remove extra line

2020-03-05 10:51 UTC, carlcasbolt commented on security/form_login_setup.rst
> +
fixed

2020-03-05 10:51 UTC, carlcasbolt commented on security/form_login_setup.rst
> +
fixed

2020-03-12 14:14 UTC, javiereguiluz commented
The proposed changes are correct according to https://github.com/symfony/maker-bundle/blob/master/src/Resources/skeleton/authenticator/LoginFormAuthenticator.tpl.php. Thanks  @carlcasbolt.

2020-03-12 14:15 UTC, merged