Add name property to the stopwatchEvent
symfony/symfony-docs pull request #14000
Opened 2020-07-27 12:04 UTC by AhmedRaafat14

Q | A
-- | --
Branch? | master for features
Bug fix? | no
New feature? | yes
Deprecations? | no
Tickets | Fix symfony/symfony#37627

2020-07-27 20:39 UTC, noniagriconomie commented on components/stopwatch.rst
> +    $event->getName();      // returns the name of the event
```suggestion
    $event->getName();       // returns the name of the event
```

:)

2020-08-11 10:21 UTC, noniagriconomie approved these changes
you should probably as well update the PR desc to also mentioned `fix https://github.com/symfony/symfony-docs/issues/14051`
:)

2020-08-11 10:25 UTC, AhmedRaafat14 commented
@noniagriconomie  Updated thanks :)

2020-08-14 10:30 UTC, OskarStark requested changes
Please add a versionadded directive 👍🏻

2020-09-12 13:55 UTC, javiereguiluz commented
Ahmad, thanks and congrats on your first Symfony Docs contribution! It was a nice issue number too --> #14000

@OskarStark I added the versionadded directive while merging.

2020-09-12 13:56 UTC, merged