Update framework.rst
symfony/symfony-docs pull request #14326
Opened 2020-10-03 19:36 UTC by ThomasLandauer

Fixing `headers` format to be consistent with the code block at https://symfony.com/doc/4.4/reference/configuration/framework.html#http-client

2020-10-05 06:29 UTC, xabbuh commented
This looks confusing to me. I think someone reading the docs would not expect to have some random config example in YAML. If there is clarification needed, we should rather add proper code blocks for the different formats IMO.

2020-10-08 16:45 UTC, Nyholm requested changes
Hm.. Im not sure this is more helpful.

2020-10-08 17:24 UTC, ThomasLandauer commented
Uhm, sorry guys, the point is that the existing `['header-name' => header-value, ...]` is **just not working** cause it's the wrong syntax. So what's your plan? Leave it as is?

2020-10-08 17:27 UTC, Nyholm commented
I think it is the correct syntax for the normalized PHP value. It is also meant to show that it should not be `['header-name' => ['header-value']]`. 

Could you add `'` around "header-value" and I would be happy with that to be the only change.

2020-10-08 18:31 UTC, ThomasLandauer commented
> Could you add `'` around "header-value" and I would be happy with that to be the only change.

Do you mean in the yaml or the php syntax?

The entire page is in yaml syntax...

2020-10-09 11:10 UTC, closed without merging