[RateLimiter] Added the docs for the new component
symfony/symfony-docs pull request #14370
Opened 2020-10-07 14:30 UTC by javiereguiluz

I'd like to merge this soon, so we can later iterate the docs with the changes done in RateLimiter during the stabilization phase before Symfony 5.2 release. Thanks!

Some questions for @wouterj:

* Is the `strategy` config option mandatory? If yes, could we assign a default value to it to lower the learning curve?
* I'm a bit lost with the "burst" behavior and the "limit" options. I don't fully understand them.
* What's the purpose of the top level `interval` option? Is the same as the `rate.interval` option?

2020-10-07 15:27 UTC, wouterj commented
Basically there are 2 "Sets" of configuration:

```
framework:
  rate_limiter:
    some_window_limited_limiter:
      strategy: fixed_window
      interval: 1m
      limit: 5

    some_token_bucket_limiter:
      strategy: token_bucket
      limit: 5
      rate: { interval: 1m, amount: 1 }
```

In short explanation:

A *fixed window* can be represented by "time windows". They start at the first hit and then allow a maximum number of hits (`limit`) in a window from that start time (`interval`). After that interval, the number of hits is reset and you can start registering hits again. Etc.

A *token bucket* can be represented as a real bucket. It's initially filled with `limit` tokens. Each hit takes a token out of this bucket. When the bucket is empty, hits are rejected. The bucket is filled using `rate` as fill rate (e.g. 1 token every minute). The bucket's maximum fill capacity is `limit`.

2020-10-08 08:21 UTC, javiereguiluz commented
Thanks for your comments! It's more clear now, so I've updated the docs.

About the config ... I prefer the current format instead of the other one proposed below.

I still have a question about the `interval` option. Which are the possible formats/syntax of this parameter? Thanks!

2020-10-08 16:36 UTC, wouterj commented
> I still have a question about the interval option. Which are the possible formats/syntax of this parameter? Thanks!

This is a bit difficult to explain, but it's everything that PHP's `DateTime` object supports after `+`. So `+1 minute`, `+1 min`, `+5 hours`, etc. but then without the `+` prefix. A formal list can be found here in the `unit` definition: https://www.php.net/datetime.formats.relative

```
unit    := (('sec' | 'second' | 'min' | 'minute' | 'hour' | 'day' | 'fortnight' | 'forthnight' | 'month' | 'year') 's'?) | 'weeks' | daytext
daytext := 'weekday', 'weekdays'
```

2020-10-08 17:04 UTC, wouterj requested changes
Sorry for the many comments. There have been 2 major refactorings after the main PR was merged, so quite a few things have changed.

2020-10-08 17:04 UTC, wouterj commented on rate_limiter.rst
> +maintain their availability.
I think the cool thing about the very abstract functionality inside the component is that it can be used for both inbound and outbound.

E.g. you can use it to limit inbound requests (HTTP requests, login attempts, etc), but also your outbound requests or internal processes (e.g. limit your application to process at most 5 messages at the same time).


```suggestion
A "rate limiter" controls how frequently some event (e.g. an HTTP request or a
login attempt) is allowed to happen. Rate limiting is commonly used as a
defensive measure to protect services from excessive use (intended or not) and
maintain their availability. This can also apply to internal or outbound processes,
for instance limiting the number of simultaneously processed messages. 
```

2020-10-08 17:04 UTC, wouterj commented on rate_limiter.rst
> +(possibly overloading the server) and do nothing for the rest of the hour.
An every bigger problem here is that a user can do 1 request and then 4,999 after 55 minutes and then 5,000 at the next hour. That means that within a 6 minute window, 9,999 calls have been made (covering 2 rate limiting windows).

2020-10-08 17:04 UTC, wouterj commented on rate_limiter.rst
> +every 15 minutes.
```suggestion
This is the simplest technique and it's based on setting a limit for a given
interval of time. For example: 5,000 requests per hour or 3 login attempts
every 15 minutes. The interval starts at the first requests instead of on
fixed moments in time.
```

Not sure if this is the best proposal, but a traditional fixed window limiter starts at fixed moments (e.g. at exactly `12:00`, `13:00`, `14:00`, etc). This "variable" fixed window limiter is a better alternative and used by the component. If the first request is made at `12:13`, the window will be reset at `13:13` and not `13:00` (traditional).

2020-10-08 17:04 UTC, wouterj commented on rate_limiter.rst
> +* A bucket is initially created with zero or more tokens;
```suggestion
* A bucket is initially created with an initial set of tokens;
```

Zero tokens will never allow any requests. The bucket starts filled at maximum capacity.

E.g. in login terms, this means that a token bucket with `limit: 5, rate: 1 per 15 minutes` means that you can try to login 5 times and only once every 15 minutes after that.

2020-10-08 17:04 UTC, wouterj commented on rate_limiter.rst
> +    // src/Controller/LuckyController.php
```suggestion
    // src/Controller/ApiController.php
```

2020-10-08 17:04 UTC, wouterj commented on rate_limiter.rst
> +            anonymous_api_limiter:
```suggestion
            anonymous_api:
```

2020-10-08 17:04 UTC, wouterj commented on rate_limiter.rst
> +            }
```suggestion
        // the variable name must be the exact same as the rate limiter name + "limiter" (can be camelCased)
        public function index(Limiter $anonymousApiLimiter, Request $request)
        {
            // create a limiter based on the client's IP address (or any other unique key, e.g. an API key)
            $limiter = $anonymousApiLimiter->create($request->getClientIp());
            
            // the argument of consume() is the number of tokens to consume
            // and returns a Limit instance
            if (false === $limiter->consume(1)->isAccepted()) {
                throw new TooManyRequestsHttpException();
            }
            
            // or use the ensureAccepted() method - which throws a RateLimitExceededException
            // if the limit has been reached
            //$limiter->consume(1)->ensureAccepted();
```

2020-10-08 17:04 UTC, wouterj commented on rate_limiter.rst
> +            $authenticated_api_limiter->reserve(1)->wait();
```suggestion
            $authenticated_api_limiter->consume(1)->wait();
```

`reserve()` only works for token bucket at the moment (I'm going to submit a PR improving this soon-ish)

2020-10-08 17:04 UTC, wouterj commented on rate_limiter.rst
> +                lock: 'app.rate_limiter_lock'
```suggestion
                # the value is the name of any cache pool defined in your application
                cache_pool: 'app.redis_cache'
                # or define a service implementing StorageInterface to use a different
                # mechanism to store the limiter information
                storage_service: 'App\RateLimiter\CustomRedisStorage'
                # the value is the name of any lock defined in your application
                lock: 'app.rate_limiter_lock'
```

2020-10-08 17:54 UTC, javiereguiluz commented on rate_limiter.rst
> +every 15 minutes.
Yes, this is great ... but it's explained later in the article, so I prefer to not add this here.

2020-10-08 18:07 UTC, javiereguiluz commented
Wouter, thanks for your amazing review 😍   I did all the requested changes!

2020-10-08 18:20 UTC, wouterj requested changes
Sorry, second round. Thanks for your quick reactions!

This doc PR has revealed quite some good improvements, I'll follow up with a PR on the code repository.

2020-10-08 18:20 UTC, wouterj commented on rate_limiter.rst
> +                rate: { interval: '1 hour', amount: 5000 }
```suggestion
                rate: { interval: '15 minutes', amount: 500 }
```

It's more realistic for the fill rate to not fill the whole bucket in one go. If that's your use-case, you should use the fixed window limiting instead. The token bucket is ideal in cases you want to manage bursts, by slowly allowing more new requests after a massive burst.

2020-10-08 18:20 UTC, wouterj commented on rate_limiter.rst
> +        public function index(LimiterInterface $anonymousApiLimiter)
```suggestion
    use Symfony\Component\RateLimiter\Limiter;

    class ApiController extends AbstractController
    {
        // the variable name must be: "rate limiter name" + "limiter" suffix
        public function index(Limiter $anonymousApiLimiter)
```

Seems like I was not too clear on this: You should be type-hinting the `Limiter` class (I'm going to propose to rename this one to `RateLimiter` or `LimiterFactory`). This class has a `create()` method, which returns the `LimiterInterface`.

2020-10-08 18:20 UTC, wouterj commented on rate_limiter.rst
> +token is available. In those cases, use the ``reserve()`` and ``wait()`` methods::
```suggestion
token is available. In those cases, use the ``wait()`` method::
```

2020-10-08 18:20 UTC, wouterj commented on rate_limiter.rst
> +            $limiter->consume(1)->wait();
```suggestion
            // this blocks the application until the given number of tokens can be consumed
            do {
                $limit = $limiter->consume(1);
                $limit->wait();
            } while (!$limit->isAccepted());
```

The downside of `consume()` is that there is no guarantee that you are accepted after `wait()`. E.g. if the window allows 5 requests per minute and 6 processes are blocked, 1 process is not accepted after the window reset and has to wait at least another minute.

Idea: add a helper method for this with a `$maxWaitTime`.

2020-10-08 18:20 UTC, wouterj commented on rate_limiter.rst
> +                storage: 'app.redis_cache'
```suggestion
                cache_pool: 'app.redis_cache'
```

2020-10-08 18:27 UTC, javiereguiluz commented
Thanks again for the new review. Thanks to your help this doc is coming along nicely 👍

2020-10-08 18:28 UTC, wouterj approved these changes
One minor fix left, but other than that ready to be merged imho!

2020-10-08 18:28 UTC, wouterj commented on rate_limiter.rst
> +at a rate of another 5,000 requests per hour. If you don't make that number of
```suggestion
at a rate of another 500 requests every 15 minutes. If you don't make that number of
```

2020-10-09 06:54 UTC, merged