[Messenger] Routing & Inheritance
symfony/symfony-docs pull request #14430
Opened 2020-10-16 11:22 UTC by sylfabre

This PR details how Messenger deals with messages and inheritance.

We were discussing with my colleagues and had to do a quick POC to find out as it is not documented, and we had some doubt about it.

2020-10-21 13:59 UTC, OskarStark commented on messenger.rst
> +* `SmsNotification` to `async_2`
```suggestion
* ``Notification`` to ``async_1``
* ``SmsNotification`` to ``async_1``
* ``SmsNotification`` to ``async_2``
```

2020-10-21 13:59 UTC, OskarStark commented on messenger.rst
> +    <?php
```suggestion
```

2020-10-21 13:59 UTC, OskarStark commented on messenger.rst
> +    <?php
```suggestion
```

2020-10-22 12:41 UTC, sylfabre commented
@OskarStark thank you for your review.

Anything else I should do to get it merged?

2020-10-27 15:13 UTC, Matts requested changes
After these changes LTGM

2020-10-27 15:13 UTC, Matts commented on messenger.rst
> +
```suggestion
```

2020-10-27 15:13 UTC, Matts commented on messenger.rst
> +
```suggestion
```

2020-10-27 15:13 UTC, Matts commented on messenger.rst
> +    class SmsNotification extends Notification {}
```suggestion

    class SmsNotification extends Notification {}
```

2020-10-27 15:13 UTC, Matts commented on messenger.rst
> +
```suggestion
```

2020-10-27 16:26 UTC, sylfabre commented
@Matts done, thank you for your review

2020-10-27 17:58 UTC, Matts approved these changes
I am so sorry! It seems the CI does not agree with my interpretation. Did not know that an empty line after a start of the code block is a requirement. See the required changes below. Will approve it now seeing as this is blocked by CI

2020-10-27 17:58 UTC, Matts commented on messenger.rst
> +.. code-block::php
```suggestion
.. code-block::php

```

2020-10-27 17:58 UTC, Matts commented on messenger.rst
> +.. code-block::yaml
```suggestion
.. code-block::yaml

```

2020-10-27 17:58 UTC, Matts commented on messenger.rst
> +.. code-block::php
```suggestion
.. code-block::php

```

2020-10-27 21:24 UTC, sylfabre commented
@Matts no worries!

2020-12-13 17:51 UTC, maxhelias approved these changes

2021-03-04 14:01 UTC, sylfabre commented
I don't why I closed it ...

2021-04-07 13:15 UTC, merged

2021-04-07 13:15 UTC, wouterj commented
Thank you @sylfabre for the research & documentation. I've slightly reduced the content and moved it up a bit (as we already talk a bit about inheritance at the start of the section).