Add gatewayapi-notifier
symfony/symfony-docs pull request #14463
Opened 2020-10-22 17:49 UTC by PGLongo

Add gatewayapi-notifier documentation

2020-10-22 18:07 UTC, Nyholm approved these changes
Looks good. 

Thank you. 

We just need to wait for the code PR to get merged.

2020-10-22 18:25 UTC, OskarStark requested changes
Could you please move it above to stay alphabetically? Thanks

2020-10-23 04:51 UTC, OskarStark approved these changes

2020-10-23 05:17 UTC, OskarStark commented
Sorry (I forgot), please change:
```diff
.. versionadded:: 5.2
    The Smsapi, Infobip, Mobyt, Esendex and Sendinblue integrations were introduced in Symfony 5.2.
```

2020-10-23 05:18 UTC, OskarStark commented
Sorry (I forgot), please change:
```diff
-    The Smsapi, Infobip, Mobyt, Esendex and Sendinblue integrations were introduced in Symfony 5.2.
+    The Smsapi, GatewayAPI, Infobip, Mobyt, Esendex and Sendinblue integrations were introduced in Symfony 5.2.
```

2020-10-23 07:04 UTC, PGLongo commented
> Sorry (I forgot), please change:
> 
> ```diff
> .. versionadded:: 5.2
> 
> -    The Smsapi, Infobip, Mobyt, Esendex and Sendinblue integrations were introduced in Symfony 5.2.
> +    The Smsapi, GatewayAPI, Infobip, Mobyt, Esendex and Sendinblue integrations were introduced in Symfony 5.2.
> ```

Done. Than you so much.

2020-10-23 07:08 UTC, OskarStark approved these changes

2020-10-23 07:15 UTC, Nyholm approved these changes

2020-11-26 13:22 UTC, PGLongo commented
@OskarStark & @Nyholm since there is the RC of 5.2 should I update `.. versionadded:: 5.2`?

2020-12-11 08:43 UTC, OskarStark requested changes
Please change the name like in the code PR, thanks

2020-12-11 08:43 UTC, OskarStark commented on notifier.rst
> +GatewayAPI  ``symfony/gatewayapi-notifier``   ``gatewayapi://TOKEN@default?from=FROM``
```suggestion
GatewayApi  ``symfony/gatewayapi-notifier``   ``gatewayapi://TOKEN@default?from=FROM``
```

2020-12-11 08:43 UTC, OskarStark commented on notifier.rst
> +    The GatewayAPI integration was introduced in Symfony 5.3.
```suggestion
    The GatewayApi integration was introduced in Symfony 5.3.
```

2020-12-11 08:49 UTC, Nyholm approved these changes
Im happy with this after the changes Oskar asked for

2020-12-11 08:49 UTC, Nyholm commented on notifier.rst
> +GatewayAPI  ``symfony/gatewayapi-notifier``   ``gatewayapi://TOKEN@default?from=FROM``
👍

2020-12-11 09:01 UTC, OskarStark commented
Thanks for the double check Tobias 👍

2020-12-13 17:49 UTC, maxhelias approved these changes

2020-12-13 17:56 UTC, OskarStark approved these changes

2021-01-14 13:04 UTC, OskarStark commented
Thank you Piergiuseppe.

2021-01-14 13:04 UTC, merged