Update import.rst
symfony/symfony-docs pull request #14554
Opened 2020-11-16 10:22 UTC by abdounikarim

Hello,

I just add a configuration if we want to import all configuration of a directory, to avoid multiple imports lines.

2020-11-16 17:30 UTC, Matts requested changes
Hey @abdounikarim 
Besides a small space on line 128 LGTM

2020-11-16 17:30 UTC, Matts commented on service_container/import.rst
> +            //If you want to import a directory, use the next configuration
missing space in front of the line.

2020-11-16 17:30 UTC, Matts commented on service_container/import.rst
> +            - { resource: services/ }
Tbh, it does look kind of weird with the unquoted trailing `/`, but guess this is how they implemented this functionality.

2020-11-17 10:28 UTC, abdounikarim commented on service_container/import.rst
> +            //If you want to import a directory, use the next configuration
done

2020-11-17 16:36 UTC, Matts approved these changes

2020-12-04 07:54 UTC, OskarStark commented on service_container/import.rst
> +            # If you want to import a directory, use the next configuration
```suggestion
            # If you want to import a whole directory:
```

2020-12-04 07:55 UTC, OskarStark commented on service_container/import.rst
> +            # If you want to import a directory, use the next configuration
Same for the other

2020-12-04 11:09 UTC, abdounikarim commented on service_container/import.rst
> +            # If you want to import a directory, use the next configuration
done

2020-12-04 12:22 UTC, OskarStark approved these changes

2020-12-04 12:22 UTC, OskarStark commented on service_container/import.rst
> +            // If you want to import a directory, use the next configuration
```suggestion
            // If you want to import a whole directory:
```

2020-12-07 10:40 UTC, OskarStark commented
Thank you Abdouni.

2020-12-07 10:40 UTC, merged