Section method only in ConsoleOutputInterface
symfony/symfony-docs pull request #14550
Opened 2020-11-15 21:20 UTC by ybenhssaien

Since `excecute()` accepts an instanceof `OutputInterface` which doesn't contain the method [`section`](https://github.com/symfony/symfony/blob/5.1/src/Symfony/Component/Console/Output/ConsoleOutputInterface.php#L31) we have to add a check on `ConsoleOutputInterface`

2020-11-16 17:35 UTC, Matts requested changes
Hey @ybenhssaien 

After this change LGTM 👍

2020-11-16 17:35 UTC, Matts commented on console.rst
> +            // section() method available only in classes implement ConsoleOutputInterface
```suggestion
            // section() method available only in classes that implement ConsoleOutputInterface
```

2020-11-16 21:12 UTC, wouterj commented
Hi @ybenhssaien! Thanks for your PR :)

However, I do not agree completely with the changes. Personally, I don't think it's possible to ever get a non-`ConsoleOutputInterface` output as argument to `execute()`, unless you're calling it yourself. In this case, I expect people to have a deeper understanding than the normal documentation audience.

That aside, I think the code you've posted does not work. Later on in the example, `$section1->overwrite()`/`$section1->clear()` is used, which only exists on the `ConsoleSectionOutput` class and not the `OutputInterface`. If you think it's needed to add something here, I would go for something like `if (!$output instanceof ConsoleOutputInterface) { throw new \LogicException('This code should not be reached, only console output is supported.') }` at the start of the command.

2020-11-17 06:28 UTC, ybenhssaien commented
Thanks @wouterj for your feedback, I agree with you about throwing exception rather than my suggestion, and clearly people should receive an instance of `ConsoleOutputInterface` when creating commands inside a Symfony app, may some enterprises internal frameworks which using `Console` components outside Symfony package depend only on this doc to customize their commands, so I think it is better to mention it (I like the idea of throwing exception) => I will update my PR

2020-11-22 11:51 UTC, merged

2020-11-22 11:52 UTC, wouterj commented
Thank you @ybenhssaien! I've merged this one in 4.4 (the lowest still maintained version) and made the nr of lines a bit smaller: 73f02f17d (the focus of this example is the usage of console sections, so I kept the exception as small as possible to avoid too much distraction)