[Console] Caution about disabling autoexist flag
symfony/symfony-docs pull request #14573
Opened 2020-11-19 08:12 UTC by ybenhssaien

Like mentionned in the class comment : https://github.com/symfony/symfony/blob/5.1/src/Symfony/Component/Console/Tester/ApplicationTester.php#L23 : the auto exist flag should be disabled, otherwise the tests won't run

2020-12-07 11:20 UTC, OskarStark requested changes

2020-12-07 11:20 UTC, OskarStark commented on console.rst
> +        $applicationTester = new ApplicationTester($application);
```suggestion
    When testing commands using the :class:`Symfony\\Component\\Console\\Tester\\ApplicationTester`
    class, don't forget to disable the auto exit flag::

        $application = new Application();
        $application->setAutoExit(false);
        
        $tester = new ApplicationTester($application);
```

2020-12-07 11:21 UTC, OskarStark requested changes
Please fix the typo in the commit message and the PR title:

```diff
- autoexists
+ autoexit
```

2020-12-18 21:17 UTC, ybenhssaien commented
@OskarStark there is no `autoexists` left on my pull request and I guess it is ready, thank you

2020-12-19 06:38 UTC, OskarStark commented
![image](https://user-images.githubusercontent.com/995707/102682897-35b3a980-41cd-11eb-81e0-f5e8a07a4abc.jpeg)

😀

2020-12-19 10:09 UTC, OskarStark approved these changes

2021-01-02 11:37 UTC, xabbuh commented
Thank you @ybenhssaien.

2021-01-02 11:38 UTC, merged