Mention MariaDB as well
symfony/symfony-docs pull request #14828
Opened 2021-01-12 20:55 UTC by iangilfillan

2021-01-13 14:26 UTC, OskarStark commented on session/database.rst
> +.............
```suggestion
.. _mysql:

MariaDB/MySQL
.............
```

2021-01-13 14:26 UTC, OskarStark commented on session/database.rst
>  -----------------------------------------------------------
```suggestion
Store Sessions in a Relational Database (MariaDB, MySQL, PostgreSQL)
--------------------------------------------------------------------
```

2021-01-13 14:27 UTC, OskarStark requested changes
2 minor comments

2021-01-22 14:11 UTC, javiereguiluz commented
Ian thanks and congrats on your first Symfony Docs contribution! We fixed some minor syntax issues while merging but your changes were good!

2021-01-22 14:11 UTC, javiereguiluz commented on session/database.rst
> +.............
Done while merging.

2021-01-22 14:12 UTC, merged