Added HexaColor constraint
symfony/symfony-docs pull request #14965
Opened 2021-02-12 15:49 UTC by welcoMattic

This PR introduces the new `HexaColor` constraint, contributed in this Symfony's repo PR

2021-07-04 21:03 UTC, OskarStark commented on reference/constraints/CssColor.rst
> +cast to a string before being validated.
```suggestion
casted to a string before being validated.
```

2021-07-04 21:03 UTC, OskarStark commented on reference/constraints/CssColor.rst
> +.....
Underline to long

2021-07-04 21:03 UTC, OskarStark commented on reference/constraints/CssColor.rst
> +......
Underline to long

2021-07-04 21:03 UTC, OskarStark commented on reference/constraints/CssColor.rst
> +.....
Underline to short

2021-10-06 17:39 UTC, derrabus commented
The feature PR has been merged.

2021-10-06 19:28 UTC, welcoMattic commented
It needs some work here to report the last changes (modes instead of mode) from the code.

2021-10-07 15:51 UTC, welcoMattic commented
I don't understand why the CI fails :thinking:

2021-10-08 06:13 UTC, OskarStark commented
friendly ping @Nyholm can you help?

2021-10-08 06:16 UTC, OskarStark commented on reference/constraints/CssColor.rst
> +of 6 characters (in addition of the leading ``#``) and contained in ranges: 0 to 9 and A to F (case insensitive).
It could be really helpful to add an example to every format like:

```suggestion
of 6 characters (in addition of the leading ``#``) and contained in ranges: 0 to 9 and A to F (case insensitive).

Example: ``fooBar``
```

or 

```suggestion
of 6 characters (in addition of the leading ``#``) and contained in ranges: 0 to 9 and A to F (case insensitive).

Examples: ``fooBar``, ``bazBar``
```

2021-10-08 06:16 UTC, OskarStark commented on reference/constraints/CssColor.rst
> +........
Underline too long

2021-10-08 06:16 UTC, OskarStark commented on reference/constraints/CssColor.rst
> +........
Underline too long

2021-10-08 06:16 UTC, OskarStark commented on reference/constraints/CssColor.rst
> +..................
Underline too short

2021-10-08 06:16 UTC, OskarStark commented on reference/constraints/CssColor.rst
> +........
Underline too long

2021-10-08 06:16 UTC, OskarStark commented on reference/constraints/CssColor.rst
> +........
Underline too long

2021-10-08 06:17 UTC, OskarStark commented on reference/constraints/CssColor.rst
> +A simple regular expression. Allows all values which represent a CSS color following th RGB notation, with or without space between values.
Can we get rid of the word "simple" here? Same for the others

2021-10-08 06:17 UTC, OskarStark requested changes
Some minor, afterwards good to merge

2021-10-08 06:23 UTC, Nyholm commented
The CI is correct. The class is called “Constraint”

https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Validator/Constraint.php

2021-10-08 06:25 UTC, Nyholm commented
Oh. Sorry. I see now that you import partial FQCN. Ci does not support that (appearently)

Feel free to ignore that :)

2021-10-08 09:45 UTC, OskarStark approved these changes

2021-10-08 09:46 UTC, OskarStark commented
Thanks Mathieu for working on this feature, this is much appreciated.

2021-10-08 09:46 UTC, merged