[DependencyInjection] Negated (not:) env var processor
symfony/symfony-docs pull request #14976
Opened 2021-02-14 09:46 UTC by bpolaszek

This PR adds documentation for symfony/symfony#40169: negated env var processor:

------
Casts to a bool (just as `env(bool:...)` does) except it returns the inverted value(falsy values are returned as `true`, truthy values are returned as `false`):

```yaml
# config/services.yaml
parameters:
    safe_for_production: '%env(not:APP_DEBUG)%'
```

2021-02-14 19:50 UTC, OskarStark requested changes
Please add a versionadded directive, thank

2021-02-15 06:19 UTC, bpolaszek commented
> Please add a versionadded directive, thank

Sure, here it is.

2021-02-15 07:25 UTC, OskarStark approved these changes

2021-02-15 07:29 UTC, OskarStark commented
Thanks @bpolaszek for working on this feature, this is much appreciated.

2021-02-15 07:29 UTC, merged