[Mailer] Configuration of the message_bus to use
symfony/symfony-docs pull request #15045
Opened 2021-02-28 22:28 UTC by t-richard

Documents symfony/symfony#34648

Closes #12736

2021-03-02 13:22 UTC, Nyholm approved these changes
I though this was document already. 

Well done!

2021-03-02 13:45 UTC, t-richard commented
I'm currently going through the `5.1` milestone in the issues and trying to document missing features listed there, that's how I caught it :slightly_smiling_face:

2021-03-02 13:47 UTC, Nyholm commented
Nice. You are the best!

That is very appreciated and a great way learn about (new) features.

2021-03-02 13:52 UTC, t-richard commented
Actually got the idea from you [some months ago](https://twitter.com/TobiasNyholm/status/1314478224286650368) :wink: 

And had some time lately to contribute !

2021-03-08 17:39 UTC, maxhelias approved these changes

2021-03-11 12:09 UTC, OskarStark commented on mailer.rst
> +
```suggestion

.. versionadded:: 5.1

    `message_bus` option was introduced in Symfony 5.1.

```

2021-03-11 12:10 UTC, OskarStark requested changes
Please add missing version added directive, thanks

2021-03-11 13:05 UTC, OskarStark approved these changes

2021-03-11 13:06 UTC, OskarStark commented
Thank you Thibault.

2021-03-11 13:06 UTC, merged