Command naming conventions
symfony/symfony-docs pull request #15062
Opened 2021-03-05 17:57 UTC by danepowell

This is a partial fix for https://github.com/symfony/symfony/issues/36973

2021-03-06 08:06 UTC, fabpot requested changes

2021-03-06 08:06 UTC, fabpot commented on contributing/code/conventions.rst
> +Naming commands and options
Naming Commands, Arguments, and Options

2021-03-06 08:06 UTC, fabpot commented on contributing/code/conventions.rst
> +Commands and their options should be named and described using the English
Commands and their arguments and options ...

2021-03-08 18:21 UTC, danepowell commented on contributing/code/conventions.rst
> +Naming commands and options
The irony of screwing up styling in a style guide :) Fixed.

2021-04-16 10:31 UTC, javiereguiluz commented
Dane, thanks for this contribution! Sorry it took us a bit to merge it. Congrats on your first Symfony Docs contribution 🎉

2021-04-16 10:32 UTC, merged