update mercure documentation
symfony/symfony-docs pull request #15149
Opened 2021-03-24 11:20 UTC by azjezz

2021-03-24 15:04 UTC, chalasr commented on mercure.rst
> +        public function __construct(HubInterface $hub)
I suggest to stick to controller argument injection for simplicity and consistency with the rest of the docs.

2021-03-31 08:49 UTC, dunglas requested changes
I tagged the new releases, we can merge this one now! I made some minor change requests.

2021-03-31 08:49 UTC, dunglas commented on mercure.rst
> +        public function __construct(Discovery $discovery, Authorization $authorization)
Same here, you can use controller injection for consistency.

2021-03-31 08:49 UTC, dunglas commented on mercure.rst
> +            $response = new JsonResponse([
I suggest using the `$this->json()` method provided by `AbstractController` for consistency too.

2021-03-31 08:49 UTC, dunglas commented on mercure.rst
> +you can create a token provider that will return the token used by
Could you also document the new `LcobucciFactory` class?

2021-03-31 11:13 UTC, javiereguiluz commented
In which version should we merge this? This article is available in 4.4, 5.2 and 5.x branches. Thanks!

2021-04-06 10:26 UTC, azjezz commented
> In which version should we merge this? This article is available in 4.4, 5.2 and 5.x branches. Thanks!

mercure and mercure-bundle don't follow symfony versioning, these changes apply to mercure 0.5 and mercure-bundle 0.3, so i'm not really sure.

2021-04-06 10:50 UTC, chalasr commented on mercure.rst
>      $ composer require lcobucci/jwt
it's no longer needed

2021-04-06 10:50 UTC, chalasr commented on mercure.rst
>          public function __invoke(Update $update): string
the signature does not look right

2021-04-06 10:56 UTC, chalasr commented
As symfony/mercure and mercure-bundle are still in 0.x versions, and because the latest versions support all maintained Symfony versions, I suggest to merge this in the 4.4 branch.

2021-04-06 15:39 UTC, javiereguiluz commented
@

2021-04-06 15:40 UTC, merged