Add note about ULIDs not being random in one case
symfony/symfony-docs pull request #15314
Opened 2021-05-06 18:26 UTC by roverwolf

Without reading the ULID specification, it is not obvious in this documentation that the random portion of a ULID is not entirely random when multiple are generated in the same millisecond.

2021-05-06 20:16 UTC, OskarStark commented
Friendly ping @fancyweb

2021-05-07 08:26 UTC, fancyweb requested changes

2021-05-07 08:26 UTC, fancyweb commented on components/uid.rst
> +    The random portion is **not** random compared to the previous ULID in this case.
Thanks for the ping @OskarStark :-)

@roverwolf I think this is true only within the same process, we should precise that.

2021-05-07 15:00 UTC, roverwolf commented on components/uid.rst
> +    The random portion is **not** random compared to the previous ULID in this case.
@fancyweb  Yes, that is true.  The text has been updated to mention that.

2021-05-08 13:47 UTC, merged

2021-05-08 13:47 UTC, javiereguiluz commented
David, thanks for improving this article and congrats on your first Symfony Docs contribution!