[Notifier] [MessageMedia] add docs
symfony/symfony-docs pull request #15366
Opened 2021-05-22 07:31 UTC by vuphuong87

MessageMedia Bridge: https://github.com/symfony/symfony/pull/41375

2021-05-22 10:30 UTC, OskarStark requested changes

2021-05-22 10:30 UTC, OskarStark commented on notifier.rst
> +    The MessageMedia integrations were introduced in Symfony 5.4.
```suggestion
    The MessageMedia integration was introduced in Symfony 5.4.
```

2021-05-22 14:56 UTC, vuphuong87 commented on notifier.rst
> +    The MessageMedia integrations were introduced in Symfony 5.4.
Thank you @OskarStark

2021-05-22 16:01 UTC, OskarStark approved these changes

2021-07-02 08:34 UTC, OskarStark commented
Thanks for your work on this new feature!

2021-07-02 08:34 UTC, merged