[Notifier] Telnyx
symfony/symfony-docs pull request #15377
Opened 2021-05-26 16:16 UTC by StaffNowa

2021-05-27 11:35 UTC, OskarStark commented on notifier.rst
Please add a versionadded directive for `5.4` below

2021-05-27 11:35 UTC, OskarStark requested changes
verisonadded missing

2021-05-27 12:25 UTC, StaffNowa commented
@OskarStark done )

2021-05-27 14:40 UTC, OskarStark commented on notifier.rst
> +    The Telnyx integrations were introduced in Symfony 5.4.
```suggestion
    The Telnyx integration was introduced in Symfony 5.4.
```

2021-05-27 17:14 UTC, StaffNowa commented on notifier.rst
> +    The Telnyx integrations were introduced in Symfony 5.4.
Fixed. Updated

2021-05-28 10:17 UTC, OskarStark approved these changes

2021-06-23 12:40 UTC, StaffNowa commented
Merged https://github.com/symfony/symfony/commit/2fb272ef85dedbe1d55c33cc3253e7b15e454f4a :)))

2021-06-23 12:56 UTC, OskarStark approved these changes

2021-07-04 09:11 UTC, OskarStark commented
Can you please rebase? Thanks

2021-07-04 10:04 UTC, StaffNowa commented
@OskarStark solved ;)

2021-07-04 12:55 UTC, OskarStark approved these changes

2021-07-27 14:36 UTC, javiereguiluz commented
Thank you Vasilij.

2021-07-27 14:36 UTC, merged