Added the way to activate remember me in the new authentication system
symfony/symfony-docs pull request #15464
Opened 2021-06-24 15:05 UTC by parijke

I had to search a while for myself not understanding why I did not have a REMEMBERME cookie when I activated the new system. So maybe handy to add it.

2021-07-15 08:50 UTC, OskarStark commented on security/remember_me.rst
> +Beware that in the new Authenitaction System you have to set the RememberMeBadge()
```suggestion
Beware that in the new authenitaction system you have to set the ``RememberMeBadge()``
```

2021-07-15 08:51 UTC, OskarStark commented on security/remember_me.rst
> +in the authenticate method of the authenticator, like:
```suggestion
in the ``authenticate()`` method of the authenticator::
```

2021-07-15 08:52 UTC, OskarStark commented on security/remember_me.rst
> +        }
```suggestion
 
    public function authenticate(Request $request): PassportInterface
    {
        $email = $request->request->get('email', '');

        $request->getSession()->set(Security::LAST_USERNAME, $email);

        return new Passport(
            new UserBadge($email),
            new PasswordCredentials($request->request->get('password', '')),
            [
                new CsrfTokenBadge('authenticate', $request->get('_csrf_token')),
                new RememberMeBadge(),
            ]
        );
    }
```

2021-07-15 08:52 UTC, OskarStark requested changes
Some comments

2021-10-04 13:01 UTC, benjaminmal commented on security/remember_me.rst
> +Beware that in the new Authenitaction System you have to set the RememberMeBadge()
Little spelling error :)

```suggestion
Beware that in the new authentication system you have to set the ``RememberMeBadge()``
```

2021-10-11 15:36 UTC, javiereguiluz commented
@wouterj do you agree with the proposed changes here? I see that in your PR #15503 you didn't update the `security/remember_me.rst` file, so I'm curious. Thanks!

2022-01-07 17:03 UTC, wouterj commented
Hi there! There has been some unfortunate delay with documenting the new remember me system.

I've proposed a complete update of the remember docs now: https://github.com/symfony/symfony-docs/pull/16376 I've cherry-picked your commit in that PR, as it's just me being late on this PR that avoided this commit to make it into the docs repo in the first place.
Thanks for taking the time to not only figure out what was missing your case, but also proposing a doc change to help others @parijke!

2022-01-07 17:03 UTC, closed without merging