[Mailer] ping_threshold for ses+smtp
symfony/symfony-docs pull request #15557
Opened 2021-07-26 07:45 UTC by Tyraelqp

Docs for https://github.com/symfony/symfony/pull/42219

2021-07-26 09:06 UTC, OskarStark requested changes

2021-07-26 09:06 UTC, OskarStark commented on mailer.rst
> +.. _mailer-sending-messages-async:
Why this change?

2021-07-26 09:06 UTC, OskarStark commented on mailer.rst
> +    value lower than ``10``: ``ses+smtp://USERNAME:PASSWORD@default?ping_threshold=9``
```suggestion
    value lower than ``10``: ``ses+smtp://USERNAME:PASSWORD@default?ping_threshold=9``

    .. versionadded:: 5.4
        
        The ping_threshold option was introduced in Symfony 5.4.
```

The option name please in double backticks, thanks

2021-07-26 09:06 UTC, OskarStark commented on mailer.rst
> +    If you want to use `ses+smtp` transport together with :doc:`Messenger </messenger>`
Double backticks please

2021-07-26 09:53 UTC, Tyraelqp commented on mailer.rst
> +.. _mailer-sending-messages-async:
`ref` on line 180

2021-07-26 09:59 UTC, Tyraelqp commented on mailer.rst
> +    value lower than ``10``: ``ses+smtp://USERNAME:PASSWORD@default?ping_threshold=9``
Added, ty

2021-07-26 10:00 UTC, Tyraelqp commented on mailer.rst
> +    If you want to use `ses+smtp` transport together with :doc:`Messenger </messenger>`
Done

2021-07-26 16:56 UTC, OskarStark commented on mailer.rst
> +.. _mailer-sending-messages-async:
Indeed, sorry 😁

2021-07-26 16:56 UTC, OskarStark approved these changes

2021-07-29 13:50 UTC, merged

2021-07-29 13:50 UTC, javiereguiluz commented
Sergey, thanks a lot for contributing this feature and for contributing the docs too. It was a great first contribution to Symfony Docs! Congrats on that 🎉