[FrameworkBundle] Add documentation about using a DSN as the session.handler_id
symfony/symfony-docs pull request #15560
Opened 2021-07-27 10:21 UTC by Kleinkind

The option to provide a DSN as the `framework.session.handler_id` was introduced in v4.4 but is currently not documented. It was previously mentioned, but the section was removed at some point. 
I've reused the config-example from https://github.com/symfony/symfony-docs/pull/13227, and added it to both, the framework configuration reference and the page about using a database for session-storage (as the DSN can be used for file- or database-storage).

2022-10-01 08:01 UTC, HeahDude requested changes
Thanks for that PR!

2022-10-01 08:01 UTC, HeahDude commented on reference/configuration/framework.rst
> +                handler_id: 'file://%kernel.project_dir%/var/sessions'
What about adding more examples as it was done in https://github.com/symfony/symfony-docs/pull/13227/files#diff-278a8e1908e2f0de9f2753d344b248e41eebde795a8e340569d2d0a3514cb29eR1290?

2022-10-01 08:01 UTC, HeahDude commented on reference/configuration/framework.rst
> +                <framework:session enabled="true" handler-id="file://%kernel.project_dir%/var/sessions"/>
```suggestion
                <framework:session enabled="true"
                    handler-id="file://%kernel.project_dir%/var/sessions"
                />
```

2022-10-01 08:01 UTC, HeahDude commented on reference/configuration/framework.rst
> +        $container->loadFromExtension('framework', [
Should use the container configurator as done in other config blocks.

2022-10-01 08:01 UTC, HeahDude commented on session/database.rst
> +Define Session Storage by DSN
Given my comment above this section should not be necessary.

2022-10-01 08:01 UTC, HeahDude commented on session/database.rst
> +Supported DSN protocols are:
I would move this part in a `.. note::` directive under the first example if this section were to be removed.

2023-08-14 07:28 UTC, OskarStark commented
Symfony 4.4 is not supported anymore, you may want to rebase on top of 5.4 branch.

Maybe @alexandre-daubois or @alamirault want to take over?

Thank you

2023-08-14 15:02 UTC, alexandre-daubois commented
Definitely, I'll take care of this 🙂

2023-08-30 15:38 UTC, HeahDude commented
This one can be closed now that #18767 has been merged.

2023-08-31 07:18 UTC, closed without merging