[Mailer] Added OhMySMTP mailer details
symfony/symfony-docs pull request #15747
Opened 2021-08-24 15:53 UTC by paul-oms

Refs https://github.com/symfony/symfony/pull/42710

2021-08-25 05:58 UTC, OskarStark requested changes

2021-08-25 05:58 UTC, OskarStark commented on mailer.rst
> -.. versionadded:: 5.2
Please keep the 5.2 versionadded, copy it and create 5.4 below the 5.2, thanks

2021-08-25 05:58 UTC, OskarStark commented on mailer.rst
> +The following transports only support tags:
Only the following transports support tags:


?

2021-08-26 09:10 UTC, paul-oms commented on mailer.rst
> +The following transports only support tags:
OhMySMTP ignores Metadata headers, but you can add multiple Tags to an email https://docs.ohmysmtp.com/reference/send/#body-parameters https://docs.ohmysmtp.com/integrations/smtp/#tags

2021-08-26 10:29 UTC, OskarStark commented on mailer.rst
> +The following transports only support tags:
Sorry for being clear, I meant rewording the sentence by my proposal

2021-08-26 10:38 UTC, paul-oms commented on mailer.rst
> +The following transports only support tags:
Fixed :)

2021-08-26 13:39 UTC, OskarStark commented on mailer.rst
> +The following transports only support tags:
Ah while reading the paragraph before I realized your sentence was correct , sorry, can you please change it for a last time? Thanks

2021-08-26 21:21 UTC, OskarStark approved these changes

2021-08-30 14:22 UTC, javiereguiluz commented
@paul-oms thanks for adding these contents ... and congrats on your first Symfony Docs contribution 🎉

2021-08-30 14:31 UTC, javiereguiluz commented
I'm closing this manually because the tool we use didn't close it automatically, as usual.

I don't know the reason, because this looks like it was merged correctly in 5.4 (and 6.0) --> https://github.com/symfony/symfony-docs/commits/5.4

2021-08-30 14:31 UTC, closed without merging