[Notifier] Add Sms77 Bridge
symfony/symfony-docs pull request #15840
Opened 2021-09-22 09:35 UTC by matthiez

2021-09-25 07:09 UTC, OskarStark requested changes

2021-09-25 07:09 UTC, OskarStark commented on notifier.rst
> +- Describe notification_on_failed_messages integration
This should be reverted

2021-10-13 07:29 UTC, OskarStark commented
@matthiez the code is merged, can you please finish this PR? Thank you

2021-10-13 07:38 UTC, OskarStark commented
Thanks for your work on this new feature!

2021-10-13 07:39 UTC, OskarStark commented
I fixed it while merging, thanks

2021-10-13 07:39 UTC, closed without merging

2021-10-13 18:40 UTC, matthiez commented on notifier.rst
> +- Describe notification_on_failed_messages integration
Sorry, seems like I forgot about it. Thanks for your help!