[HttpClient] HttpClientInterface::setResponseFactory method
symfony/symfony-docs pull request #15883
Opened 2021-10-01 18:18 UTC by greeflas

2021-10-01 22:53 UTC, OskarStark requested changes

2021-10-01 22:53 UTC, OskarStark commented on http_client.rst
> +    The setResponseFactory() method was introduced in Symfony 5.4.
Method in double backticks please

2021-10-01 23:11 UTC, greeflas commented on http_client.rst
> +    The setResponseFactory() method was introduced in Symfony 5.4.
Done

2022-01-14 14:23 UTC, wouterj commented
Thank you @greeflas! The feature looks great, and you're my hero for also documenting features you add to Symfony core :) I've moved your example a bit further up, but other than that the PR is perfect!

2022-01-14 14:23 UTC, merged