Add Engagespot documentation
symfony/symfony-docs pull request #16165
Opened 2021-11-27 00:48 UTC by danut007ro

Add documentation about engagespot integration

2021-11-27 07:38 UTC, OskarStark commented on notifier.rst
> +Engagespot      ``symfony/engagespot-notifier``        ``engagespot://API_KEY@default?campaign_name=DEFAULT_CAMPAIGN``
```suggestion
Engagespot      ``symfony/engagespot-notifier``        ``engagespot://API_KEY@default?campaign_name=CAMPAIGN_NAME``
```

2021-11-27 07:39 UTC, OskarStark requested changes

2021-11-27 07:39 UTC, OskarStark commented on notifier.rst
> +    The Engagespot, Expo and OneSignal integrations were introduced in Symfony 5.4.
```suggestion
    The Expo, OneSignal and Engagespot integrations were introduced in Symfony 5.4.
```

2022-03-04 18:37 UTC, OskarStark commented
Please retarget `6.1` branch

2022-03-05 11:11 UTC, danut007ro commented
Done, but tests are failing, seems unrelated

2022-03-27 07:47 UTC, OskarStark approved these changes

2022-03-27 07:47 UTC, OskarStark commented
Can you please rebase? This should make the CI green. Thanks

2022-06-10 12:52 UTC, javiereguiluz commented
@danut007ro sorry it took us so long to take care of your contribution. I was going to merge it, but there was lots of conflicts while merging. I couldn't fix those, so I recreated your changes directly in https://github.com/symfony/symfony-docs/commit/e16e05ab02983f166296564b4cb2a9b9b1c33db2 Thanks!

2022-06-10 12:52 UTC, closed without merging