[Form] fix EntityType with multiple=true return type
symfony/symfony-docs pull request #16849
Opened 2022-06-06 09:48 UTC by MrYamous

Small fix for #16805 about return type in form with multiple option

I'm doing this on version 4.4 because it's the older maintained, but maybe we need to correct further?

2022-06-06 12:00 UTC, HeahDude requested changes

2022-06-06 12:00 UTC, HeahDude commented on reference/forms/types/options/multiple.rst.inc
> +Doctrine's Array Collection.
This is true for `EntityType` but not for the `ChoiceType` since only the first use the collection transformer.
So this change cannot be merged as is, only the `EntityType` doc should mention this.

2022-06-09 20:39 UTC, MrYamous commented on reference/forms/types/options/multiple.rst.inc
> +Doctrine's Array Collection.
You are right, I put back this file in its initial state and I keep the modification only for EntityType

2022-10-26 15:35 UTC, javiereguiluz commented
Thank you @MrYamous.

2022-10-26 15:37 UTC, merged