[DependecyInjection] Added Uses & hints
symfony/symfony-docs pull request #17197
Opened 2022-08-17 18:51 UTC by mohamedGasmii

2022-08-17 19:25 UTC, wouterj requested changes
I'm +1 for the Response return type, but -1 for the uses and Route attribute. The `// ...` indicates that not all information is present in this example, and the example should stay focussed on what it is demonstrating: the dependency injection.

Also, I see a lot of PRs by you from the past days. It's nice to receive contributions, but many small PRs add a lot of maintenance overhead (reviewing, merging, etc). Please try to combine more changes in a single PR if they are about the same topic (e.g. "add return types to all code examples in the Cache chapter").

2022-08-17 19:56 UTC, mohamedGasmii commented
@wouterj  Thank you for your feedback, i removed the uses & route attribute and i try to combine small changes in for the next PRs.

2022-08-22 07:57 UTC, xabbuh approved these changes

2022-08-22 08:12 UTC, xabbuh commented
Thank you @mohamedGasmii.

2022-08-22 08:12 UTC, merged