Added description to improved bin/console debug:container --env-vars …
symfony/symfony-docs pull request #17833
Opened 2023-01-30 20:34 UTC by mw3e21a

2023-01-31 05:42 UTC, OskarStark requested changes

2023-01-31 05:42 UTC, OskarStark commented on configuration.rst
> + ------------ ----------------- ------------------------------------ -------------
Please use the same indentation as before, thanks

2023-01-31 05:42 UTC, OskarStark commented on configuration.rst
> +see the number of occurrences of each environment variable in the container:
```suggestion
environment variables, with their values, referenced in Symfony's container configuration,
you can also see the number of occurrences of each environment variable in the container:
```

2023-02-01 19:33 UTC, mw3e21a commented
@OskarStark Thanks for the suggestions. Done

2023-10-17 18:38 UTC, alamirault approved these changes

2023-12-27 15:27 UTC, javiereguiluz commented
Michael, thanks and congrats on your first Symfony Docs contribution 🎉

2023-12-27 15:27 UTC, merged