[HttpFoundation] update doc creation session table
symfony/symfony-docs pull request #17844
Opened 2023-02-01 08:20 UTC by alli83

linked to issue https://github.com/symfony/symfony-docs/issues/17569 and PR https://github.com/symfony/symfony/pull/49097/files

Update the methods to create the session table.

2023-05-22 15:45 UTC, stof requested changes

2023-05-22 15:45 UTC, stof commented on session.rst
>  .. _mysql:
this must stay just before the title.

2023-05-22 15:49 UTC, stof commented
this change is correct but it is not specific to databases. Passing a DSN as handler_id is supported in Symfony 4.4+ and supports other kinds of handlers too (if you pass a `redis://` URL, it will create a redis handler).
See https://github.com/symfony/symfony/pull/34177 for the PR implementing it and https://github.com/symfony/symfony-docs/pull/13227 for the PR documenting it.
So I'm not sure this should be repeated in this code snippet.

IMO, this PR should focus only on the issue it attempts to fix, i.e. documenting the integration with the doctrine schema tool.

2023-05-23 04:54 UTC, alli83 commented
@stof I see, thanks for your feedback ! I'll update it

2023-05-25 07:52 UTC, merged

2023-05-25 07:53 UTC, javiereguiluz commented
@alli83 thanks a lot for improving the docs and congrats on your first Symfony Docs contribution 🎉 

Thanks also to Christophe for reviewing this.