Change security title for checking if user is logged in
symfony/symfony-docs pull request #18036
Opened 2023-03-09 18:56 UTC by alamirault

Fix #18023

2023-03-10 07:12 UTC, artyuum requested changes

2023-03-10 07:12 UTC, artyuum commented on security.rst
> +Secondly, you can use a special "attribute" ``IS_AUTHENTICATED_FULLY`` in place of a role::
I suggest one of those:
> Secondly, you can use a special "attribute" (``IS_AUTHENTICATED_FULLY``) in place of a role::

or 
> Secondly, you can use the special "attribute" ``IS_AUTHENTICATED_FULLY`` in place of a role::

2023-03-10 18:54 UTC, alamirault commented on security.rst
> +Secondly, you can use a special "attribute" ``IS_AUTHENTICATED_FULLY`` in place of a role::
Second choice sounds better

2023-03-10 18:57 UTC, artyuum approved these changes

2023-03-11 04:59 UTC, OskarStark approved these changes

2023-03-11 09:39 UTC, OskarStark commented
Thank you @alamirault.

2023-03-11 09:39 UTC, merged

2023-03-22 07:00 UTC, artyuum commented
Oops... I think there is a mistake here 😅
[The issue](https://github.com/symfony/symfony-docs/issues/18023) was about changing `IS_AUTHENTICATED_FULLY` to `IS_AUTHENTICATED`.
Not sure how I missed that while reviewing.