[Serializer] Add Debug command
symfony/symfony-docs pull request #18211
Opened 2023-04-14 14:16 UTC by loic425

Fixes #18208

2023-04-16 19:24 UTC, mdoutreluingne commented
Versionadded directive is missing

2023-04-21 13:49 UTC, loic425 commented
> Versionadded directive is missing

done

2023-04-21 16:55 UTC, mdoutreluingne approved these changes

2023-04-26 08:44 UTC, OskarStark commented on serializer.rst
> +    $ php bin/console debug:serializer 'App\Entity\SomeClass'
```suggestion
    $ php bin/console debug:serializer 'App\Entity\Book'
```

2023-04-26 08:44 UTC, OskarStark commented on serializer.rst
> +    This debug command was introduced in Symfony 6.3.
```suggestion
    The debug:serializer`` command was introduced in Symfony 6.3.
```

2023-04-26 08:45 UTC, OskarStark commented on serializer.rst
> +        | firstArgument  | [                                                          |
Can we use something more real life instead of `firstArgument` ?

Maybe name and ISBN, because the groups also mention `book`

Thanks

2023-04-26 08:45 UTC, OskarStark commented on serializer.rst
> +        App\Entity\SomeClass
```suggestion
        App\Entity\Book
```

2023-04-26 08:45 UTC, OskarStark requested changes
See my comments

2023-04-26 15:00 UTC, loic425 commented on serializer.rst
> +        | firstArgument  | [                                                          |
done

2023-04-26 15:32 UTC, OskarStark approved these changes

2023-04-26 15:33 UTC, OskarStark commented
Thanks for your work on this new feature!

2023-04-26 15:34 UTC, merged