[Scheduler] Add new component documentation
symfony/symfony-docs pull request #18290
Opened 2023-05-07 09:37 UTC by andreybolonin

Fixes #18067, #18255, #18251

Also based on #18136

Waiting for feedbacks and ready to fix some issues :)

2023-07-12 18:09 UTC, alexislefebvre commented on scheduler.rst
> +    $ php bin/console messenger:consume scheduler_trial
Where do `scheduler_trial` comes from?

2023-08-02 15:44 UTC, Aerendir requested changes

2023-08-02 15:44 UTC, Aerendir commented on scheduler.rst
> +This trigger allows you to define you schedule with frequency as text, using
"allows you to define YOUR"

2023-08-02 15:44 UTC, Aerendir commented on scheduler.rst
> +If your schedule do not need to run indefinitely, you can use `until` option
- "If your schedule DOES not"
- "you can use THE `until`"

2023-08-02 15:44 UTC, Aerendir commented on scheduler.rst
> +This trigger can be configured following same rules as the eponymous Unix
"following THE same rules OF the"

2023-08-02 15:44 UTC, Aerendir commented on scheduler.rst
> +Also you can use some another triggers: ``CallbackTrigger, CronExpressionTrigger, DateIntervalTrigger, DatePeriodTrigger, ExcludeTimeTrigger``
"You can also use some other triggers"

2023-08-02 15:44 UTC, Aerendir commented on scheduler.rst
> +By implementing the TriggerInterface your can create your own trigger using
"By implementing the TriggerInterface, you can create your own trigger using

2023-08-30 14:29 UTC, alexandre-daubois requested changes
Great to see this component being documented! :smiley:

2023-08-30 14:29 UTC, alexandre-daubois commented on scheduler.rst
> +It is possible to specify an exact hour to trigger the schedule with `from`
```suggestion
It is possible to specify an exact hour to trigger the schedule with ``from``
```

2023-08-30 14:29 UTC, alexandre-daubois commented on scheduler.rst
> +If your schedule does not need to run indefinitely, you can use the `until` option
```suggestion
If your schedule does not need to run indefinitely, you can use the ``until`` option
```

2023-08-30 14:29 UTC, alexandre-daubois commented on scheduler.rst
> +    The minimal interval allowed with cron is 1 minute.
```suggestion
    The minimal interval allowed by the ``cron()`` method is 1 minute.
```

2023-08-30 14:29 UTC, alexandre-daubois commented on scheduler.rst
> +Run the Messenger consumer
```suggestion
Run The Messenger Consumer
```

2023-08-30 14:29 UTC, alexandre-daubois commented on scheduler.rst
> +Trigger your schedule
```suggestion
Trigger Your Schedule
```

2023-08-30 14:29 UTC, alexandre-daubois commented on scheduler.rst
> +~~~~
```suggestion
~~~~~~~~~~~~~~~~~~
```

2023-08-30 14:29 UTC, alexandre-daubois commented on scheduler.rst
> +    * `#hourly` - Run once an hour, first minute - `0 * * * *`
```suggestion
    * ``#yearly``, ``#annually`` - Run once a year, midnight, Jan. 1 - ``0 0 1 1 *``
    * ``#monthly`` - Run once a month, midnight, first of month - ``0 0 1 * *``
    * ``#weekly`` - Run once a week, midnight on Sun - ``0 0 * * 0``
    * ``#daily``, ``#midnight`` - Run once a day, midnight - ``0 0 * * *``
    * ``#hourly`` - Run once an hour, first minute - ``0 * * * *``
```

2023-08-30 14:29 UTC, alexandre-daubois commented on scheduler.rst
> +~~~~
```suggestion
~~~~~~~~~~~~~~~~~
```

2023-08-30 14:29 UTC, alexandre-daubois commented on scheduler.rst
> +Define your own trigger
```suggestion
Define Your Own Trigger
```

2023-08-30 14:29 UTC, alexandre-daubois commented on scheduler.rst
> +``getNextRunDate`` method::
```suggestion
the :method:`FQCN\TriggerInterface::getNextRunDate` method::
```

2023-08-31 07:19 UTC, OskarStark commented
@kbond maybe you can find some spare time and review this PR, so we can merge this as a first version. Thanks

2023-08-31 07:48 UTC, javiereguiluz commented
**Please, let's not work on this PR anymore for now.**

It's not bad 🙏 but we're discussing internally about a radically different approach for the docs of this component. Same comment for the #17964 PR about Webhook/RemoteEvent docs.

I'm sorry but I hope you understand this. Thanks!

2023-08-31 08:44 UTC, Aerendir commented
@javiereguiluz , please, can you give us more details? I'm so curious! 😋

2023-08-31 14:32 UTC, closed without merging