Fix doctrine/dbal deprecation using Statement::executeQuery
symfony/symfony-docs pull request #18429
Opened 2023-06-17 17:26 UTC by vinceAmstoutz

Deprecation warning when `doctrine/dbal >= 3.4`.

In Symfony docs,executeQuery() is mentionned here : [Querying with SQL](https://symfony.com/doc/current/doctrine.html#querying-with-sql).
 
But since `3.4.*` passing parameters to `tatement::execute*()` functions is deprecated by `doctrine/dbal` with this warning:
`User Deprecated: Passing $params to Statement::executeQuery() is deprecated. Bind parameters using Statement::bindParam() or Statement::bindValue() instead. (Statement.php:212 called by User.php:40, https://github.com/doctrine/dbal/pull/5556, package doctrine/dbal)`.

I've already ask in the [DBAL PR concerned](https://github.com/doctrine/dbal/pull/5556#issuecomment-1571489203) how to use `executeQuery` from now on. 

![image](https://github.com/symfony/symfony-docs/assets/46444652/e0b6938b-4f67-474a-a8f5-5f565b04e5b4)
[(in the same PR)](https://github.com/doctrine/dbal/pull/5556#issuecomment-1571617512)

So, after having tested it in a prod project, I propose an update of the doc in this sense.

Thanks again @derrabus 🙏

2023-06-17 19:20 UTC, derrabus requested changes

2023-06-17 19:20 UTC, derrabus commented on doctrine.rst
> +            $resultSet = $stmt->executeQuery($sql, ['price' => $price]);
```suggestion
            $resultSet = $conn->executeQuery($sql, ['price' => $price]);
```

2023-06-17 19:35 UTC, vinceAmstoutz commented on doctrine.rst
> +            $resultSet = $stmt->executeQuery($sql, ['price' => $price]);
Tanks, sorry for the inadvertence

2023-06-17 21:33 UTC, derrabus approved these changes

2023-06-19 06:26 UTC, OskarStark approved these changes

2023-06-19 08:07 UTC, xabbuh approved these changes

2023-06-19 08:42 UTC, OskarStark commented
Thank you Vincent.

2023-06-19 08:42 UTC, merged