[Form] Support Translatable Enum
symfony/symfony-docs pull request #18599
Opened 2023-07-23 16:21 UTC by Seb33300

Documentation for https://github.com/symfony/symfony/pull/50931

2023-07-24 15:00 UTC, derrabus requested changes

2023-07-24 15:00 UTC, derrabus commented on reference/forms/types/enum.rst
> +implements ``TranslatableInterface`` to translate or display custom labels::
```suggestion
implement ``TranslatableInterface`` to translate or display custom labels::
```

2023-07-24 15:00 UTC, derrabus commented
Code PR has been merged.

2023-07-26 14:42 UTC, xabbuh commented
We also need a `versionadded` directive which explains that you can use this feature since Symfony 6.4.

2023-07-27 07:53 UTC, Seb33300 commented
Added

2023-07-27 09:24 UTC, derrabus commented on reference/forms/types/enum.rst
> +    Support for ``TranslatableInterface`` was introduced in Symfony 6.4.
The interface itself has existed before 6.4. Maybe we should be a bit more precise here.

```suggestion
    Support for enums that implement ``TranslatableInterface`` was introduced in Symfony 6.4.
```

2023-07-27 09:34 UTC, Seb33300 commented on reference/forms/types/enum.rst
> +    Support for ``TranslatableInterface`` was introduced in Symfony 6.4.
Symfony (twig) already supports enums that implement ``TranslatableInterface.
But EnumType did not support them yet.

This is the EnumType documentation page so I think it's obvious that we are talking about the EnumType here.

> Support for ``TranslatableInterface`` was introduced in Symfony 6.4.
means
> ``EnumType`` support for ``TranslatableInterface`` was introduced in Symfony 6.4.

2023-07-27 13:05 UTC, OskarStark approved these changes

2023-07-27 13:06 UTC, OskarStark commented
Thanks for your work on this new feature!

2023-07-27 13:06 UTC, merged