[DependencyInjection] Add `#[AutowireLocator]` attribute
symfony/symfony-docs pull request #18775
Opened 2023-08-21 13:05 UTC by alexandre-daubois

Fix https://github.com/symfony/symfony-docs/issues/18774

2023-08-21 22:22 UTC, kbond requested changes
Thanks for this @alexandre-daubois!

2023-08-21 22:22 UTC, kbond commented on service_container/service_subscribers_locators.rst
> +    class CommandBus implements ServiceSubscriberInterface
```suggestion
    class CommandBus
```

This should be removed, correct? (Same with below)

2023-08-21 22:22 UTC, kbond commented on service_container/service_subscribers_locators.rst
> +    use Symfony\Contracts\Service\ServiceSubscriberInterface;
```suggestion
```

2023-08-22 06:57 UTC, alexandre-daubois commented on service_container/service_subscribers_locators.rst
> +    class CommandBus implements ServiceSubscriberInterface
Indeed! That's updated :slightly_smiling_face:

2023-08-22 11:19 UTC, kbond approved these changes

2023-08-22 12:27 UTC, nicolas-grekas commented on service_container/service_subscribers_locators.rst
> +to define aliased services thanks to named argument, as well as optional
```suggestion
to define aliased services thanks to named arguments, as well as optional
```

2023-08-22 12:27 UTC, nicolas-grekas reviewed
LGTM thanks

2023-08-22 13:18 UTC, alexandre-daubois commented on service_container/service_subscribers_locators.rst
> +to define aliased services thanks to named argument, as well as optional
Updated, thanks :slightly_smiling_face:

2023-08-28 10:25 UTC, javiereguiluz commented
Another nice new feature and another perfect contribution. Thanks Alex ... and thanks to reviewers too!

2023-08-28 10:25 UTC, merged