Fix documentation for MongoDB Session Handler
symfony/symfony-docs pull request #19070
Opened 2023-10-21 01:07 UTC by GromNaN

- `database` and `collection` parameters are [required](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/MongoDbSessionHandler.php#L45-L46) by `MongoDbSessionHandler`
- @alcaeus compatibility package can't be recommended anymore, projects have moved to Doctrine ODM 2.

2023-10-21 07:16 UTC, OskarStark approved these changes

2023-10-23 08:53 UTC, alexandre-daubois approved these changes

2023-10-23 12:55 UTC, xabbuh commented on session.rst
> +    The name of the database
Should we emphasize that the parameter is required (same for `collection`)?

2023-10-23 13:02 UTC, GromNaN commented on session.rst
> +    The name of the database
I moved this required parameters to the previous section.

2023-10-23 13:34 UTC, xabbuh approved these changes

2023-10-23 13:38 UTC, xabbuh requested changes

2023-10-23 13:38 UTC, xabbuh commented on session.rst
> +                        'database' => '%env('MONGODB_DB')%',
```suggestion
                        'database' => '%env("MONGODB_DB")%',
```

2023-10-24 08:25 UTC, OskarStark commented
Thank you Jérôme.

2023-10-24 08:25 UTC, merged

2023-10-24 08:26 UTC, OskarStark commented on session.rst
> +                        'database' => '%env('MONGODB_DB')%',
Fixed in e0b410708