[String] Remove confusing paragraph about withEmoji('strip')
symfony/symfony-docs pull request #19323
Opened 2023-12-21 08:55 UTC by smnandre

The AsciiSlugger does remove every emoji from a given string per default without any external component or package, as they are not... ASCII.

The paragraph added some confusion to the reader, implying that
* AsciiSlugger did not work with emoji per default
* the special locale + the Intl component was required

So i suggest to purely remove it.

2023-12-23 10:56 UTC, OskarStark commented
But afterwards there is no mention about `strip` locale, isn't it?

I am for keeping it and change it to remove potentially confusion

2023-12-23 11:49 UTC, smnandre commented
If it's changed **_and_** moved outside the Slugger section i agree :)

2023-12-23 13:42 UTC, wouterj requested changes
We should move this paragraph+example to https://symfony.com/doc/current/components/intl.html#emoji-transliteration

2023-12-26 08:15 UTC, javiereguiluz commented
Good catch, thanks Simon.

2023-12-26 08:15 UTC, merged