[Contracts][DependencyInjection] Add `ServiceCollectionInterface`
symfony/symfony-docs pull request #19370
Opened 2024-01-03 07:50 UTC by alexandre-daubois

Fix #19368

Ping @kbond 🙂

2024-01-03 14:39 UTC, kbond requested changes
Thanks for working on this Alex!

2024-01-03 14:39 UTC, kbond commented on service_container/service_subscribers_locators.rst
> +Because the service locator implements the
I wonder if we should move this to the above paragraph where we explain what `ServiceLocator` implements?

2024-01-03 14:39 UTC, kbond commented on service_container/service_subscribers_locators.rst
> +        $this->locator->get($serviceId)->someMethod();
Let's move this line out of the foreach as a separate example. `$service` is initialized at this point.

2024-01-03 14:39 UTC, kbond commented on service_container/service_subscribers_locators.rst
> +    foreach ($this->locator as $serviceId => $service) {
I also think we should merge this code block with the one above.

2024-01-03 17:15 UTC, alexandre-daubois commented
Thanks for your suggestions Kevin! I reworked the PR, is it better now? 🙂

2024-01-03 17:27 UTC, kbond commented on service_container/service_subscribers_locators.rst
>      $handler = ($this->locator)($commandClass);
`ServiceLocator` is indeed callable but this isn't part of the contracts:

```php
public function someAction(ServiceCollectionInterface $locator)
{
    $handler = ($locator)($commandClass); // this works but static analysis will complain
}
```

I'd prefer removing this in favor of `$this->locator->get($commandClass)` but as we've shown this callable example for some time, I'm not sure... @nicolas-grekas, what do you think. I don't have the context on why `ServiceLocator` was made callable initially.

2024-01-03 17:30 UTC, nicolas-grekas commented on service_container/service_subscribers_locators.rst
>      $handler = ($this->locator)($commandClass);
I would reformulate the whole paragraph. Why tell that the injected service is some implementation-specific class while only an interface is type hinted? This is a bad hint that encourages against SOLID principles.

2024-01-03 17:50 UTC, alexandre-daubois commented on service_container/service_subscribers_locators.rst
>      $handler = ($this->locator)($commandClass);
Alright, I tried something totally different not mentioning "internal" implementation but only explaining the locators are countable and traversable.

2024-01-03 17:57 UTC, nicolas-grekas commented on service_container/service_subscribers_locators.rst
> +:class:`Symfony\\Component\\DependencyInjection\\ServiceLocator`. A service
I still wouldn't mention this, it's an implementation detail.
We should tell about ServiceCollectionInterface: if ppl type-hint for it, *then* they will get an object that is coutable+iterable, in addition to being a PSR11 locator.

2024-01-11 09:12 UTC, alexandre-daubois commented
I tried to remove useless implementation details and go for the type-hint approach Nicolas suggested.

2024-01-12 15:56 UTC, merged

2024-01-12 15:57 UTC, javiereguiluz commented
A nice contribution! Thanks a lot Alex and thanks for your patience during the review 🙏 

Thanks also to Kevin and Nicolas for the review!