[AssetMapper] [WCM] Replace ImportMapConfigReader by interface
symfony/symfony-docs pull request #19407
Opened 2024-01-10 16:15 UTC by damienfern

Related to this PR : https://github.com/symfony/symfony/pull/53485

2024-01-11 08:48 UTC, alexandre-daubois requested changes

2024-01-11 08:48 UTC, alexandre-daubois commented on frontend/asset_mapper.rst
> +Sometimes you may want to create your own config reader to load your importmap or use a custom one from a 3rd party package. You can do this by creating a service that implements ``ImportMapConfigRea
Try to break your lines at char 80

2024-01-11 08:48 UTC, alexandre-daubois commented on frontend/asset_mapper.rst
> +
You may add this at the end of your option description:

```rst
.. versionadded:: 7.1

    The ``framework.asset_mapper.config_reader_id`` was introduced in Symfony 7.1.
```

2024-01-11 08:49 UTC, alexandre-daubois commented on frontend/asset_mapper.rst
> +Sometimes you may want to create your own config reader to load your importmap or use a custom one from a 3rd party package. You can do this by creating a service that implements ``ImportMapConfigRea
```suggestion
Sometimes you may want to create your own config reader to load your importmap or use a custom one from a third party package. You can do this by creating a service that implements ``ImportMapConfigReaderInterface`` and then setting the ``config_reader_id`` option:
```

2024-12-06 08:29 UTC, javiereguiluz commented
Closing because the related code PR #53485 was closed as "won't fix".

2024-12-06 08:29 UTC, closed without merging