Update shared.rst to add doc on PHP attributes
symfony/symfony-docs pull request #19698
Opened 2024-03-22 09:45 UTC by arnissolle

Add code block for PHP attributes.

2024-03-22 09:55 UTC, xabbuh requested changes

2024-03-22 09:55 UTC, xabbuh commented on service_container/shared.rst
> +        namespace App\SomeNonSharedService;
```suggestion
        namespace App;
```

2024-03-22 11:51 UTC, xabbuh approved these changes

2024-03-22 14:42 UTC, javiereguiluz commented
Pierre, thanks a lot for improving the docs ... and congrats on your first Symfony Docs contribution 🎉

2024-03-22 14:42 UTC, merged

2024-03-22 17:45 UTC, arnissolle commented
⚠️ @javiereguiluz @xabbuh [the doc is broken](https://symfony.com/doc/current/service_container/shared.html), is there something missing in the code block?

<img width="795" alt="Capture d’écran 2024-03-22 à 18 46 21" src="https://github.com/symfony/symfony-docs/assets/5046159/c80b7965-628b-4c9f-a0ed-bf580204b6d0">

2024-03-27 19:53 UTC, xabbuh commented
@arnissolle Thanks for the heads up. I guess this is due to the fact that there was a tab instead of four spaces (dda1b38a0acb6023236bbc5fe3d17cc15df801b1 should fix that).