feat(mailer): Add AhaSend Mailer doc
symfony/symfony-docs pull request #20361
Opened 2024-10-29 17:43 UTC by farhadhf

This PR adds the necessary documentation for AhaSend Mailer Bridge and Webhooks.

Code PR : https://github.com/symfony/symfony/pull/58698

2025-01-07 09:05 UTC, mdoutreluingne reviewed
To be merged into version 7.3

2025-01-07 09:05 UTC, mdoutreluingne commented on mailer.rst
> +`AhaSend`_            ``composer require symfony/ahasend-mailer``     yes
```suggestion
`AhaSend`_            ``composer require symfony/aha-send-mailer``     yes
```

2025-01-09 06:24 UTC, OskarStark requested changes

2025-01-09 06:24 UTC, OskarStark commented on mailer.rst
> +    The Mailomat, Mailtrap, Postal, Sweego and AhaSend integrations were introduced in Symfony 7.2.
Needs to be moved to a new verdionadded 7.3 directive

2025-01-09 06:24 UTC, OskarStark commented on webhook.rst
> +    The ``Mandrill``,  ``Mailomat``, ``Mailtrap``, ``Sweego`` and ``AhaSend`` integrations were introduced in
Please move to a dedicated versionadded 7.3 directive

2025-01-09 08:18 UTC, farhadhf commented
Thanks @OskarStark. The requested changes have been made, but I also pulled the latest changes from 7.3 to prevent any potential conflicts and changed the base for this PR to 7.3. Please let me know if this is a problem, we can close this PR and I'll create a fresh one from 7.3.

2025-01-09 08:24 UTC, xabbuh commented on mailer.rst
> +    The Mailomat, Mailtrap, Postal, Sweego and AhaSend integrations were introduced in Symfony 7.2.
```suggestion
    The Mailomat, Mailtrap, Postal and Sweego integrations were introduced in Symfony 7.2.
```

2025-01-09 10:07 UTC, xabbuh approved these changes

2025-01-09 10:52 UTC, mdoutreluingne approved these changes

2025-01-16 15:02 UTC, javiereguiluz commented
Merged! Thanks Farhad ... and congrats on your first Symfony Docs contribution 🎉

2025-01-16 15:03 UTC, closed without merging