Use non-static PHPUnit assert methods
symfony/symfony-docs pull request #20405
Opened 2024-11-22 15:22 UTC by javiereguiluz

Fixes #20392.

2024-11-22 15:48 UTC, xabbuh approved these changes

2024-11-22 15:50 UTC, xabbuh requested changes
looks like there are some more examples in `/components.clock.rst`

2024-11-22 21:15 UTC, wouterj approved these changes

2024-11-22 21:34 UTC, xabbuh approved these changes

2024-11-25 07:29 UTC, merged

2024-11-25 07:39 UTC, javiereguiluz commented
@OskarStark do you know if DOCtor-RST can alert if we use `self::assert*` instead of `$this->assert*`? Thanks