Document new utf8 option of Routing component
symfony/symfony-docs pull request #6938
Opened 2016-09-01 08:55 UTC by mickaelandrieu

Hi,

all credits to @javiereguiluz and @nicolas-grekas, I've just copy/pasted the blog article http://symfony.com/blog/new-in-symfony-3-2-unicode-routing-support#comment-form

Mickaël

2016-09-01 08:58 UTC, nicolas-grekas commented
See #6890
we now have to decide which one is better :)

2016-09-01 08:59 UTC, nicolas-grekas commented
or merge both since they aren't on the same page

2016-09-01 11:59 UTC, mickaelandrieu commented
@nicolas-grekas my bad, didnt thank you have started something... as you like, I wont be sad if you close this one my only interest is to see this feature documented.

By the way, big thanks! From a business/e-commerce point of view, this feature is so useful :)

2016-09-21 19:58 UTC, xabbuh commented on components/routing.rst
> +Unicode routing support
Unicode Routing Support

2016-09-21 19:58 UTC, xabbuh commented on components/routing.rst
> +The routing component supports UTF-8 characters in route paths and requirements. Thanks to the `utf8` route option, you can make Symfony match and generate routes with UTF-8 characters:
Routing component

2016-09-21 19:58 UTC, xabbuh commented on components/routing.rst
> +The routing component supports UTF-8 characters in route paths and requirements. Thanks to the `utf8` route option, you can make Symfony match and generate routes with UTF-8 characters:
The option needs to be enclosed by double backticks.

2016-09-21 19:59 UTC, xabbuh commented on components/routing.rst
> +          utf8: true
Please add Annotations, XML, and PHP examples too.

2016-09-21 19:59 UTC, xabbuh commented on components/routing.rst
> +In this route, the `utf8` option set to true makes Symfony consider the `.` requirement to match any UTF-8 characters instead of just a single byte character, so the following URLs would match: `/cat
please use double backticks everywhere here too

2016-09-21 20:00 UTC, xabbuh commented on components/routing.rst
> +In this route, the `utf8` option set to true makes Symfony consider the `.` requirement to match any UTF-8 characters instead of just a single byte character, so the following URLs would match: `/cat
and please wrap lines after the first word that crosses the 72nd character

2016-09-21 20:00 UTC, xabbuh commented on components/routing.rst
> +The routing component supports UTF-8 characters in route paths and requirements. Thanks to the `utf8` route option, you can make Symfony match and generate routes with UTF-8 characters:
Please also wrap lines after the first word that crosses the 72nd character.

2016-09-21 20:00 UTC, xabbuh commented on components/routing.rst
> +          utf8: true
We need other format examples here too.

2016-09-21 20:00 UTC, xabbuh commented on components/routing.rst
> +This second example describes how you can use utf8 string as a routing requirement.
UTF-8

2016-09-21 20:01 UTC, xabbuh commented on components/routing.rst
> +    In Symfony 3.2 there is no need to set this utf8 explicitly. As soon as Symfony finds a UTF-8 character in the route path or requirements, it will turn the UTF-8 support automatically. In additio
same as above

2016-09-21 20:01 UTC, xabbuh commented on components/routing.rst
> +    The UTF8 support in route paths and requirements were added in Symfony 3.2
UTF-8 support for route paths and requirements were introduced in Symfony 3.2.

2016-09-21 20:01 UTC, xabbuh requested changes

2016-09-21 21:43 UTC, mickaelandrieu commented
Wow ... I feel so bad :(  thank you for this review, I will address comments tomorrow!

2016-09-21 22:03 UTC, xabbuh commented
No need to worry. There's not much to change. :)

2016-09-22 12:54 UTC, mickaelandrieu commented on components/routing.rst
> +          utf8: true
Do we really need ? I don't see the gain here when it's already well described [here](http://symfony.com/doc/current/routing.html#routing-examples)

I will do it if you insist, though (sounds like a simple copy/paste of the resource I've linked ^ ).

2016-09-22 12:57 UTC, mickaelandrieu commented
Hi @xabbuh,

I've adressed almost all comments except the one about complete all formats, let me know if this need more work :)

Mickaël

2016-09-22 13:02 UTC, nicolas-grekas commented on components/routing.rst
> +          utf8: true
That's how the doc is yes, config are always in all formats, repeating is teaching isn't it?

2016-09-22 13:07 UTC, mickaelandrieu commented on components/routing.rst
> +          utf8: true
true, let's go for it :)

2016-09-22 13:16 UTC, xabbuh commented
👍 (except for the missing config formats)

2016-09-22 13:31 UTC, mickaelandrieu commented on components/routing.rst
> +                <option key="utf8">true</option>
Question here: how can we do to ensure true will be converted to boolean value ?

2016-09-24 09:04 UTC, xabbuh commented on components/routing.rst
> +                <option key="utf8">true</option>
That's the responsibility of the loader.

2016-09-24 15:13 UTC, mickaelandrieu commented on components/routing.rst
> +                <option key="utf8">true</option>
So ... is it good, or does it need much work from me ?

2016-09-25 07:54 UTC, xabbuh commented on components/routing.rst
> +Unicode Routing support
Support

2016-09-25 07:54 UTC, xabbuh commented on components/routing.rst
> +            utf8: true
please indent this line with four spaces

2016-09-25 07:55 UTC, xabbuh commented on components/routing.rst
> +          defaults: { _controller: 'DefaultController::categoryAction' }
`AppBundle:Default:category`

2016-09-25 07:55 UTC, xabbuh commented on components/routing.rst
> +                <option key="utf8">true</option>
It's good as it is. :)

2016-09-25 07:56 UTC, xabbuh commented on components/routing.rst
> +In this route, the ``utf8`` option set to true makes Symfony consider the
please enclose `true` in double backticks

2016-09-25 07:56 UTC, xabbuh commented on components/routing.rst
> +byte character, so the following URLs would match: ``/category/日本語``,
maybe split this here: "[...] character. This means that the following URL would match [...]"

2016-09-25 07:57 UTC, xabbuh commented on components/routing.rst
> +  .. code-block:: php-annotations
please indent with four spaces

2016-09-25 07:57 UTC, xabbuh commented on components/routing.rst
> +This second example describes how you can use UTF-8 string as a routing
strings

2016-09-25 07:57 UTC, xabbuh commented on components/routing.rst
> +This second example describes how you can use UTF-8 string as a routing
[...] as routing requirements.

2016-09-25 07:58 UTC, xabbuh commented on components/routing.rst
> +    In Symfony 3.2 there is no need to set this utf8 explicitly. As soon
[...] to explicitly set the `utf8` option.

2016-09-25 07:58 UTC, xabbuh commented on components/routing.rst
> +    Symfony 3.2.
I would move this up to the beginning of this section.

2016-09-27 21:08 UTC, mickaelandrieu commented
@xabbuh thanks again for your time. Comments addressed ;)

2016-09-28 07:52 UTC, xabbuh commented on components/routing.rst
> +    UTF-8 support for route paths and requirements were introduced in
was

2016-09-28 07:53 UTC, xabbuh commented on components/routing.rst
> +            utf8: true
indentation :)

2016-09-28 07:54 UTC, xabbuh commented on components/routing.rst
> +            utf8: true
Looks like it's the same in the other YAML example too.

2016-09-28 07:54 UTC, xabbuh commented
@mickaelandrieu I left two last minor comments and indentation of the PHP code examples looks weird too. But overall this change looks ready to be merged. 👍

2016-09-28 07:58 UTC, mickaelandrieu commented
@xabbuh I won't give up now :D let me improve again my contribution ;)

2016-09-28 17:31 UTC, xabbuh approved these changes

2016-09-28 17:31 UTC, xabbuh commented
👍 

Status: Reviewed

2016-10-06 21:30 UTC, merged

2016-10-06 21:31 UTC, wouterj commented
Thanks @mickaelandrieu! After your quick responses to the reviews, this PR has now made it to the docs!

Fyi, I've fixed some indentation issues and splitted the big note directive in c5328d7.

2016-10-06 23:31 UTC, mickaelandrieu commented
@wouterj  thank you, it's better now :)
Always happy to help ;)