Mentioned the "Symfony Upgrade Fixer" in the upgrade article
symfony/symfony-docs pull request #6941
Opened 2016-09-01 14:37 UTC by javiereguiluz

This fixes #5951.

2016-09-04 10:00 UTC, snoek09 commented on setup/upgrade_major.rst
> +changes). These releases are the trickiest to upgrade, as they are allowed break
allowed `to` break backwards compatibility

2016-09-04 10:02 UTC, snoek09 commented
Cool stuff :+1: 

One minor comment.

Status: reviewed.

2016-09-18 09:50 UTC, wouterj requested changes
Afaik, it only works for Symfony 2 to 3 atm, I think we have to mention that.

2016-09-18 10:53 UTC, javiereguiluz commented
@wouterj thanks for the review. I made the change you asked for.

2016-09-18 11:21 UTC, wouterj approved these changes

2016-09-18 11:21 UTC, wouterj commented
👍

2016-09-19 00:43 UTC, weaverryan commented
Awesome!

2016-09-19 00:43 UTC, merged