[Routing] Add a note for refering invokable controllers
symfony/symfony-docs pull request #6951
Opened 2016-09-02 17:36 UTC by chalasr

Since this feature can help to avoid defining controllers as services or writing `Controller::__invoke` when it's not needed, I think we should document it.

2016-09-22 08:52 UTC, xabbuh commented on routing.rst
> +   passing the method name, just use its fully-qualified namespace.
I think we should reword this a bit:

> To refer to an action that is implemented as the `__invoke()` method of a controller class, you do not have to pass the method name, but can just use the fully qualified class name.

And we should then add an example for it imo.

2016-09-22 08:52 UTC, xabbuh commented on routing.rst
> +   passing the method name, just use its fully-qualified namespace.
Maybe also move it to its own headline?

2016-09-22 22:51 UTC, chalasr commented on routing.rst
> +   passing the method name, just use its fully-qualified namespace.
👍  For the reword and the example, I made the changes.
About the visibility, IMHO we should stay consistent with the `controllers as a service` _note_ above, don't you think it's enough as is?

2016-10-16 14:45 UTC, iltar commented
In the note below it's referencing to Controller as a Service. When using Controller as a Service, you simply refer to the service id: `app.controller.foo:__invoke` would be `app.controller.foo`.

2016-10-17 09:06 UTC, chalasr commented
@iltar The note redirects to a dedicated section which already document that https://github.com/symfony/symfony-docs/blob/master/controller/service.rst#referring-to-the-service

2017-04-01 11:49 UTC, HeahDude requested changes
👍

2017-04-01 11:49 UTC, HeahDude approved these changes

2017-05-17 07:27 UTC, xabbuh commented
Thank you @chalasr.

2017-05-17 07:27 UTC, merged