Patch based 2.7
symfony/symfony-docs pull request #6985
Opened 2016-09-20 17:46 UTC by franciscocorrales

Doc changes on 2.7

2016-09-21 07:56 UTC, xabbuh commented on bundles/installation.rst
> +    $ bin/console config:dump-reference AsseticBundle
This does only apply to Symfony >= 3.0.

2016-09-21 07:56 UTC, xabbuh commented on bundles/override.rst
> +Form types are referred to by their fully-qualified class name::
This is only true for Symfony >= 2.8.

2016-09-21 07:57 UTC, xabbuh commented on bundles/override.rst
> +Form types are referred to by their fully-qualified class name::
But we may want to remove this paragraph entirely for the 2.7 docs and only talk about form type extensions.

2016-09-21 07:59 UTC, xabbuh requested changes
@franciscocorrales I left some minor comments that should be addressed. But overall I like your suggestions.

2017-02-14 15:07 UTC, javiereguiluz commented
@franciscocorrales thanks for contributing these improvements. The PR stalled and has conflicts, so I'm finishing it in #7490. I reused your original commits, so you'll get full credit for your work. Thanks!

2017-02-14 15:07 UTC, closed without merging