Use new array syntax and make a few minor tweaks
symfony/symfony-docs pull request #7005
Opened 2016-09-23 07:11 UTC by bocharsky-bw

2016-09-23 07:15 UTC, xabbuh commented on page_creation.rst
> +            ]);
I am against making this change. Using the short array syntax in newer branches makes merging branches up a nightmare.

2016-09-23 07:15 UTC, xabbuh requested changes

2016-09-23 07:20 UTC, bocharsky-bw commented on page_creation.rst
> +            ]);
@xabbuh Ah, it makes sense. So making changes to the new array syntax is pointless in docs? I'm just wondering for myself for the future.

2016-09-23 07:35 UTC, bocharsky-bw commented on page_creation.rst
> +            $bundles = [
@xabbuh Could we keep the new array syntax here? We already used it in [Symfony SE v3](https://github.com/symfony/symfony-standard/blob/3.0/app/AppKernel.php#L10-L19).

2016-09-23 16:44 UTC, wouterj commented on page_creation.rst
> +            ]);
@bocharsky-bw yes. I think we should wait till PHP <5.4 is completely dropped in Symfony (that'll be when 2.8 reaches end of maintainance). We can then safely do this change for all code examples in all branches at one go.

2016-09-23 16:45 UTC, wouterj commented on page_creation.rst
> +            $bundles = [
I would say no. If we change the line below this or move the example in some way, we'll always get merge conflicts.

2016-09-23 16:46 UTC, wouterj commented
I agree with @xabbuh on the short array syntax, but I like the other changes. 👍 

If you can update this PR to remove the short array syntax, please do so. Otherwise, we'll do while merging.

Status: reviewed

2016-09-23 17:32 UTC, bocharsky-bw commented on page_creation.rst
> +            ]);
Fair enough 👍

2016-09-23 17:33 UTC, bocharsky-bw commented on page_creation.rst
> +            $bundles = [
Thanks for the clarification!

2016-09-23 17:37 UTC, bocharsky-bw commented
Short array syntax reverted.

2016-09-23 22:25 UTC, wouterj approved these changes

2016-09-24 08:38 UTC, xabbuh commented
Thank you @bocharsky-bw.

2016-09-24 08:38 UTC, xabbuh approved these changes

2016-09-24 08:39 UTC, closed without merging