[DependencyInjection] Docs for method autowiring
symfony/symfony-docs pull request #7041
Opened 2016-10-06 14:28 UTC by dunglas

Docs for symfony/symfony#20167 and symfony/symfony#17608.

2016-10-06 23:36 UTC, mickaelandrieu requested changes

2016-10-06 23:36 UTC, mickaelandrieu commented on components/dependency_injection/autowiring.rst
> +.. versionadded:: 2.8
Should be 3.2

2016-10-06 23:36 UTC, mickaelandrieu commented on components/dependency_injection/autowiring.rst
> +Alternatively, the list of method to use for dependency injection can be configured explicitly:
methods

2016-10-09 16:57 UTC, mickaelandrieu approved these changes

2017-04-28 16:41 UTC, weaverryan commented
This has now totally been changed - #7608 is the way to do it, which is much simpler. So let's make a PR for that! :)

2017-04-28 16:41 UTC, closed without merging