Update setup.rst
symfony/symfony-docs pull request #7058
Opened 2016-10-14 09:39 UTC by jagonzaar

I put some code that resolve some problems in windows 10 with xampp, without using composer.

2016-10-16 14:35 UTC, iltar commented
Isn't it possible to simply call `php` instead of `php.exe`? Seems like an issue within xampp and windows 10, not in the docs.

2016-10-16 14:40 UTC, wouterj requested changes

2016-10-16 14:40 UTC, wouterj commented on setup.rst
> +    c:\> php.exe -r "readfile('https://symfony.com/installer');" > symfony
not needed, when `c:\xampp\php` is in your PATH, `php` will be resolved to `c:\xampp\php\php.exe` by Windows

2016-10-16 14:40 UTC, wouterj commented on setup.rst
> +        c:\projects\> php.exe symfony
same applies here (and below)

2016-10-16 14:40 UTC, wouterj commented on setup.rst
> +    In windows 10 with xampp, if you have un error like
Typo: "un" should be "an"

2016-10-16 14:40 UTC, wouterj commented on setup.rst
> +    In windows 10 with xampp, if you have un error like
I think this is an error that occurs in all cases on Windows. So let's make a bit more generic:

```rst
.. note::

    If you're on Windows, you might get this error:

        cURL error 60: SSL certificate problem: unable to get local issuer certificate.

    In this case, download this link: http://curl.haxx.se/ca/cacert.pem and move the
    file on your computer. Then edit your `php.ini` file and insert:

    .. code-block:: ini

        curl.cainfo = "C:\path\to\cacert.pem"
```

2016-10-16 19:34 UTC, jagonzaar commented
Thanks for the idea. I tried with php (when the path is defined) instead of php.exe and that's works...

      From: Iltar van der Berg <notifications@github.com>
 To: symfony/symfony-docs <symfony-docs@noreply.github.com> 
Cc: jagonzaar <jagonzaar@yahoo.com>; Author <author@noreply.github.com>
 Sent: Sunday, October 16, 2016 4:35 PM
 Subject: Re: [symfony/symfony-docs] Update setup.rst (#7058)
   
Isn't it possible to simply call php instead of php.exe? Seems like an issue within xampp and windows 10, not in the docs.—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2016-10-16 19:48 UTC, jagonzaar commented on setup.rst
> +    c:\> php.exe -r "readfile('https://symfony.com/installer');" > symfony
You are right... I used php (not php.exe) and that's works...

2016-10-16 19:57 UTC, jagonzaar commented on setup.rst
> +        c:\projects\> php.exe symfony
You are right... I used php (not php.exe) and that's works...
The only problem is that
c:\projects\> php symfony
doesn't create another file. I need use "php symfony" each time that must use symfony.
When I try symfony alone, I have errors:
c:\xampp\htdocs\symfonywebs>symfony
'symfony' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
the file 'symfony' is the PATH directory and in the directory where I execute that command.
What can be the problem?

2016-10-16 20:04 UTC, jagonzaar commented on setup.rst
> +    In windows 10 with xampp, if you have un error like
Sorry... is my "spanglish"!

2016-10-16 20:05 UTC, jagonzaar commented on setup.rst
> +        c:\projects\> php.exe symfony
correction: the file symfony is in the PATH....

2016-11-21 10:07 UTC, javiereguiluz reviewed
The `setup.rst` article is probably the most critical article for us, because it's usually the entry point for Symfony newcomers. So we must be extra careful when making any changes.

I agree with @wouterj's proposal to add a note about the certificate problems. But I wonder if we need to add the other changes about Windows 10 and XAMPP.

2017-02-14 15:23 UTC, javiereguiluz commented
@jagonzaar thanks for contributing these improvements. However, as Wouter explained, most of the changes are not required because `php` will also work on Windows systems. That's why we can close this as "won't fix" ... except for the cURL certificate problem, which is very important/common ... and not only for Windows, so I've opened #7492 to fix it. Thanks!

2017-02-14 15:23 UTC, closed without merging