Added docs mentioning UserInterface in action args
symfony/symfony-docs pull request #7060
Opened 2016-10-15 21:13 UTC by iltar

Added notes about the `UserInterface` added in symfony/symfony#18510, was waiting for the in-deprecation of the `getUser()` method: symfony/symfony#19452.

2016-10-16 14:13 UTC, wouterj commented on security.rst
>  look like::
this paragraph needs to be changed

2016-10-16 14:14 UTC, wouterj requested changes

2016-10-16 14:14 UTC, wouterj commented on security.rst
> +    The functionality to get the user via the method signature was added in 3.2,
"was introduced in Symfony 3.2. You can still retrieve it by [...]"

2016-10-16 14:14 UTC, wouterj commented
status: needs work

Thanks for the docs PR!

2016-10-16 14:29 UTC, iltar commented on security.rst
>  look like::
What do you suggest? It's still correct

2016-11-09 13:24 UTC, wouterj commented on security.rst
>  look like::
Indeed, sorry. The paragraph is a bit confusing, but correct.

2016-11-09 13:25 UTC, wouterj approved these changes

2016-11-09 13:25 UTC, wouterj commented
👍 
status: reviewed

2016-11-12 10:12 UTC, xabbuh commented on security.rst
> +    extend the :class:`Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller`.
[...] the Controller class.

2016-11-12 10:13 UTC, xabbuh commented on security.rst
> +
this blank line should be removed

2016-11-19 16:57 UTC, merged

2016-11-19 16:57 UTC, wouterj commented
Thanks @iltar! I've applied the feedback from @xabbuh in f0db5af and merged this PR.

2016-11-20 18:59 UTC, iltar commented
Ah thanks! I completely forgot about the reply