[PhpUnitBridge] Doc for @expectedDeprecation & new configuration env vars
symfony/symfony-docs pull request #7074
Opened 2016-10-21 15:31 UTC by nicolas-grekas

Related to https://github.com/symfony/symfony/pull/20255 & https://github.com/symfony/symfony/pull/20256

2016-10-21 15:35 UTC, stof commented on components/phpunit_bridge.rst
> +     * @expectedDeprecation The second argument of the "%s" method is deprecated.
is the order of annotations important ? If they must be in the same order than the triggered deprecation, this should be documented (or changed in the code)

2016-10-21 15:36 UTC, javiereguiluz approved these changes
👍

2016-10-21 15:36 UTC, javiereguiluz commented on components/phpunit_bridge.rst
> +* Provides a ``ClockMock`` and ``DnsMock`` helpers class for time or network-sensitive tests.
`helpers class` -> `helper classes`

2016-10-21 15:40 UTC, nicolas-grekas commented on components/phpunit_bridge.rst
> +     * @expectedDeprecation The second argument of the "%s" method is deprecated.
yes it is, open for discussion for sure

2016-10-21 15:43 UTC, nicolas-grekas commented on components/phpunit_bridge.rst
> +     * @expectedDeprecation The second argument of the "%s" method is deprecated.
Note added above

2016-10-21 22:25 UTC, wouterj requested changes

2016-10-21 22:25 UTC, wouterj commented on components/phpunit_bridge.rst
> +When adding deprecations to your code, you might like writting tests that verify
typo: writting -> writing

2016-10-21 22:25 UTC, wouterj commented on components/phpunit_bridge.rst
> +alongside with the expected message, given in the same format than for the
"[...] that you can use on your test methods. It requires you to pass the expected message, [...]"

2016-10-21 22:25 UTC, wouterj commented on components/phpunit_bridge.rst
> +deprecation messages for a given test method, you can use the annotation several
"messages" -> "message"

2016-10-21 22:25 UTC, wouterj commented on components/phpunit_bridge.rst
> +    ``prophecy`` but not ``symfony/yaml``.
What does "if you need" mean? Am I not able to use Prophecy if I don't set this env var to `symfony/yaml`?

2016-10-21 22:25 UTC, wouterj commented on components/phpunit_bridge.rst
> +`PHPUnit assertStringMatchesFormat()`_ method. If you expect more than one
"PHPUnit's assertStringMatchesFormat() method"

2016-10-23 16:00 UTC, nicolas-grekas commented on components/phpunit_bridge.rst
> +    ``prophecy`` but not ``symfony/yaml``.
Yes: as state before, the default is to have prophecy and symfony/yaml removed

2016-10-23 16:06 UTC, nicolas-grekas commented
Comments addressed
Status: needs review

2016-10-23 16:17 UTC, wouterj approved these changes

2016-10-23 16:18 UTC, wouterj commented
:+1:
status: reviewed

2016-10-26 19:03 UTC, xabbuh commented
Thank you @nicolas-grekas.

2016-10-26 19:04 UTC, merged