[Doctrine] Slave/Master configuration options
symfony/symfony-docs pull request #7111
Opened 2016-11-02 18:42 UTC by Simperfit

Like settled in the [Configuration Class](https://github.com/doctrine/DoctrineBundle/blob/master/DependencyInjection/Configuration.php#L149) options keep_slave should be a children of connections

2016-11-04 08:02 UTC, xabbuh requested changes

2016-11-04 08:02 UTC, xabbuh commented on reference/configuration/doctrine.rst
>                  # the DBAL keepSlave option
the comment must be moved too

2016-11-04 19:07 UTC, Simperfit commented
@xabbuh comment taken in account

2016-11-04 19:14 UTC, javiereguiluz commented
👍

2016-11-05 10:13 UTC, xabbuh commented
Thank you @Simperfit.

2016-11-05 10:14 UTC, closed without merging