Added "How to Use a Custom Version Strategy for Assets"
symfony/symfony-docs pull request #7141
Opened 2016-11-15 09:34 UTC by javiereguiluz

This PR finishes the great work made by @teohhanhui in #5489.

2016-11-15 09:37 UTC, stof commented
you should also fix conflicts

2016-11-15 10:26 UTC, OskarStark commented on frontend/custom_version_strategy.rst
> +your own version strategy.
Shouldn't we add an example here, what "requires a more advanced versioning"  means?

2016-11-15 10:26 UTC, OskarStark commented on frontend/custom_version_strategy.rst
> +the manifest file generated by gulp-buster and the format of the generated
gulp buster should be a link here, too

2016-11-15 10:26 UTC, OskarStark commented on reference/twig_reference.rst
> +.. _reference-twig-function-asset:
why did you add this here @javiereguiluz ?

2016-11-15 10:30 UTC, javiereguiluz commented on reference/twig_reference.rst
> +.. _reference-twig-function-asset:
Good catch. It was in the original PR. I've just removed it.

2016-11-15 10:55 UTC, javiereguiluz commented on frontend/custom_version_strategy.rst
> +the manifest file generated by gulp-buster and the format of the generated
Done.

2016-11-15 10:55 UTC, javiereguiluz commented on frontend/custom_version_strategy.rst
> +your own version strategy.
I've reworded this part a bit. Thanks.

2016-12-08 19:54 UTC, xabbuh commented on frontend/custom_version_strategy.rst
> +the :ref:`version_strategy <reference-framework-assets-version_strategy>` option:
It looks like you have to add a label for this.

2016-12-09 06:03 UTC, xabbuh requested changes

2016-12-09 06:03 UTC, xabbuh commented on frontend/custom_version_strategy.rst
> +identifier is also modified to force the browser download it again instead of
[...] the browser to download it [...]

2016-12-09 06:03 UTC, xabbuh commented on frontend/custom_version_strategy.rst
> +            $hashes = json_decode(file_get_contents($this->manifestPath), true);
The variable is not needed.

2016-12-09 06:03 UTC, xabbuh commented on frontend/custom_version_strategy.rst
> +After creating the strategy PHP class, register it as a Symfony service
Missing colon at the end of the sentence.

2016-12-09 06:03 UTC, xabbuh commented on frontend/custom_version_strategy.rst
> +                <framework:assets version_strategy="app.assets.versioning.gulp_buster" />
In XML, the attribute should be `version-strategy`.

2016-12-09 06:03 UTC, xabbuh commented on reference/configuration/framework.rst
> +The service id of the :doc:`asset version strategy </frontend/custom_version:strategy>`
The colon in the path would be an underscore.

2016-12-09 07:40 UTC, javiereguiluz commented
@xabbuh thanks for your review. I've fixed everything.

2016-12-09 07:48 UTC, xabbuh commented on reference/configuration/framework.rst
> +* :ref:`version_strategy <reference-assets-version-strategy>`
I guess this should be `reference-framework-assets-version_strategy` instead (see the build failure on Travis CI).

2016-12-09 08:03 UTC, xabbuh commented
:+1:

Status: Reviewed

2016-12-09 08:35 UTC, xabbuh approved these changes

2016-12-12 20:14 UTC, xabbuh commented
Thank you Javier.

2016-12-12 20:14 UTC, merged

2016-12-12 20:15 UTC, xabbuh commented
And thank you for starting this awesome PR @teohhanhui!