adding the namespace for ArrayInput
symfony/symfony-docs pull request #7192
Opened 2016-11-28 15:50 UTC by nodefortytwo

Makes the documentation a little cleaner, easier to copy

2016-11-28 21:41 UTC, chalasr requested changes

2016-11-28 21:41 UTC, chalasr commented on console/calling_commands.rst
> +    use Symfony\Component\Console\Input\ArrayInput
missing semicolon

2016-11-28 21:41 UTC, chalasr commented on console/calling_commands.rst
>      protected function execute(InputInterface $input, OutputInterface $output)
If we do it for `ArrayInput`, shouldn't we do it for these too?

2016-12-08 19:41 UTC, xabbuh commented
👍 I think it makes sense to document it this way. All other classes should indeed be known at this point.

Status: Reviewed

2016-12-12 20:09 UTC, xabbuh commented
Thank you @nodefortytwo.

2016-12-12 20:09 UTC, closed without merging