[Fix][httpKernel] Wrong links
symfony/symfony-docs pull request #7308
Opened 2017-01-02 11:51 UTC by 20uf

Hello here,

### Problem
Fixes bad links pointing to the HttpKernel api.
http://symfony.com/doc/current/components/http_kernel.html#the-kernel-request-event

Happy New Year !

2017-01-02 12:04 UTC, javiereguiluz requested changes

2017-01-02 12:04 UTC, javiereguiluz commented on components/http_kernel.rst
> +    As of 3.1 the :class:`Symfony\\Component\\HttpKernel` accepts a
I'd say that the original reference was correct. See: http://api.symfony.com/3.1/Symfony/Component/HttpKernel/HttpKernel.html

2017-01-02 12:04 UTC, javiereguiluz commented on components/http_kernel.rst
> +    :class:`Symfony\\Component\\HttpKernel\\Controller\\ArgumentResolverInterface`.
Nice catch!

2017-01-02 12:15 UTC, 20uf commented
Indeed I have done wrong.

2017-01-03 11:55 UTC, javiereguiluz approved these changes
👍 

Very nice catch! Thanks @20uf.

2017-01-10 19:10 UTC, xabbuh commented
Thank you @20uf.

2017-01-10 19:10 UTC, closed without merging