[Workflow] Add tip for workflow configuration default values
symfony/symfony-docs pull request #7315
Opened 2017-01-04 07:54 UTC by dominikhajduk

Added tip for http://symfony.com/doc/current/workflow/usage.html configuration.

Tested and based on great examples provided by @lyrixx in: https://github.com/lyrixx/SFLive-Paris2016-Workflow/blob/master/app/config/workflow.yml#L3 and
https://github.com/lyrixx/SFLive-Paris2016-Workflow/blob/master/src/AppBundle/Entity/Article.php#L24

2017-01-08 16:02 UTC, javiereguiluz requested changes
Adding this tip looks like a good idea to me. Sadly, it's hard to understand it, so I'd recommend to reword it a bit. Thanks!

2017-01-08 16:37 UTC, dominikhajduk commented
@javiereguiluz thanks for CR. I've rewritten tip to be clearer in the same PR. If you have additional suggestions please let me know. Or should I open new PR?

2017-01-08 17:34 UTC, javiereguiluz commented
@dominikhajduk thanks for this reword. I can now understand everything perfectly 👍

2017-01-08 17:35 UTC, javiereguiluz approved these changes
👍

2017-01-10 20:02 UTC, xabbuh commented on workflow/usage.rst
> +    for ``type`` is "single_state". Default value for ``arguments`` is "marking".
I would reword this a bit to something like this:

> The `type` (default value `single_state`) and `arguments` (default value `marking`) attributes of the `marking_store` option are optional. If omitted, their default values will be used.

What do you think?

2017-01-10 20:04 UTC, dominikhajduk commented on workflow/usage.rst
> +    for ``type`` is "single_state". Default value for ``arguments`` is "marking".
@xabbuh fine for me. Thanks.

2017-01-10 20:10 UTC, dominikhajduk commented
@xabbuh should be fine now. Thanks

2017-01-10 20:13 UTC, xabbuh commented
:+1:

@javiereguiluz Good for you too?

2017-01-10 20:36 UTC, javiereguiluz commented
@xabbuh yes, it looks very nice!

2017-01-11 07:38 UTC, xabbuh commented
Thank you Dominik.

2017-01-11 07:38 UTC, closed without merging