Rename "console tasks" to "console commands"
symfony/symfony-docs pull request #7346
Opened 2017-01-09 16:21 UTC by javiereguiluz

In the past we used "console tasks" to refer to "console commands". There were still some occurrences of "console tasks" in the docs. This PR fixes them.

2017-01-10 10:43 UTC, OskarStark approved these changes

2017-01-11 08:33 UTC, xabbuh requested changes

2017-01-11 08:33 UTC, xabbuh commented on reference/dic_tags.rst
> +commands (unless you pass ``--no-warmup`` to ``cache:clear``). It is also run
command

2017-01-11 09:15 UTC, xabbuh commented
👍 

Status: Reviewed

2017-01-11 09:15 UTC, xabbuh approved these changes

2017-01-11 19:23 UTC, xabbuh commented
Thank you Javier.

2017-01-11 19:23 UTC, closed without merging