ePub generation fixes
symfony/symfony-docs pull request #7347
Opened 2017-01-09 21:08 UTC by michaelperrin

This PR enables back the generation of ePub files. It fixes #5707 and #6485.

The main problems were due to:

* A missing reference for templates in the _symfonycom_ extension.
* Several syntax errors in the HTML files (missing closing tags, lack of quotes on attribute values).

Note that I didn't change the strange need of a double `<body>` tag (yup, that's really strange, but there must be a reason).

Generating the ePub file can be done with the following command:

    make epub

I have tested the generated file in Apple iBooks, and it works fine.

I also removed the changelog from the generated file, as it was making a really big file without any added value. I can put it back if you wish.

I can also squash the commits into one.

2017-01-11 16:08 UTC, xabbuh requested changes

2017-01-11 16:08 UTC, xabbuh commented on index.rst
> -    changelog
Looks like you have to keep this (see the failing build on Travis CI).

2017-01-11 16:26 UTC, michaelperrin commented on index.rst
> -    changelog
This was intentional as the generated file contains the whole changelog, which is huge and not really useful. But I'm going to remove it for now, and we can decide later if it is relevant to keep it.

2017-01-11 16:30 UTC, michaelperrin commented
@xabbuh I removed the changelog removal (!) for now.

2017-01-26 19:10 UTC, sepehr commented
Would love to see this merged. Big thanks, @michaelperrin.

2017-01-26 21:08 UTC, michaelperrin commented
Thanks @sepehr . The generated ePub file could be better, but this PR can't do any harm anyway as it basically fixes HTML issues is the docs (missing closing tags, missing quotes for HTML attributes, etc.).

2017-01-28 04:40 UTC, sepehr commented
Yeah, even with these fixes, there are a lot of problems with the generated epub. `epubcheck` throws a lot of errors. And the Google Play Books app cannot parse the epub even though it seems to be working with Apple's iBook.

@michaelperrin, Is there any chance that you have working compiled epub of Symfony 3.x docs? If so, I'd be grateful if you share it.

2017-01-28 13:40 UTC, michaelperrin commented
@sepehr I didn't know the `epubcheck` tool and there are indeed a huge amount of errors in the generated file! I'll have a look at it but I think it needs a lot of work to make all the changes...

2018-01-21 18:10 UTC, javiereguiluz commented
@michaelperrin I'm sorry we didn't merge this on time. If you could rebase it, I'd merge it quickly. I guess there will be still some issues in the generated ePub, but as you said, there are too many to fix them all. the work you did here is good enough to fix some things. Thank you.

2018-02-09 14:23 UTC, javiereguiluz commented
Let's close this one because we have problems even to generate HTML and PDF ... so we can't dedicate resources to a new format. I'm sorry.

2018-02-09 14:23 UTC, closed without merging

2018-02-09 14:25 UTC, michaelperrin commented
@javiereguiluz Yep, better closing it indeed.
If needed, I can make the changes in an other PR to fix the few issues as you requested.