Fix typo in doctrine doc
symfony/symfony-docs pull request #7371
Opened 2017-01-15 21:31 UTC by Th3Mouk

2017-01-15 21:47 UTC, javiereguiluz commented on doctrine/event_listeners_subscribers.rst
>  happens inside the system. For you, this means that you can create arbitrary
`have` ?

2017-01-15 21:49 UTC, Th3Mouk commented on doctrine/event_listeners_subscribers.rst
>  happens inside the system. For you, this means that you can create arbitrary
obviously too fast, i correct it

2017-01-16 09:13 UTC, xabbuh commented
:+1:

Status: Reviewed

2017-01-16 10:55 UTC, javiereguiluz approved these changes
👍

2017-01-24 19:48 UTC, xabbuh requested changes
please ignore this review

2017-01-24 19:48 UTC, xabbuh commented on doctrine/event_listeners_subscribers.rst
> +Doctrine packages have a rich event system that fires events when almost anything
This is just a test. Please ignore the comment.

2017-01-24 20:06 UTC, xabbuh approved these changes

2017-01-24 20:42 UTC, xabbuh commented
Good catch, thanks @Th3Mouk.

2017-01-24 20:42 UTC, closed without merging