Documented the "labels" option of DateIntervalType
symfony/symfony-docs pull request #7400
Opened 2017-01-22 18:20 UTC by javiereguiluz

This fixes #7368.

2017-01-24 18:43 UTC, HeahDude requested changes

2017-01-24 18:43 UTC, HeahDude commented on reference/forms/types/dateinterval.rst
> +      'invert' => 'form.trans.invert',
Default option values are `null`, so default labels are humanized child names, so "Invert", "Years", ...

2017-01-25 10:24 UTC, javiereguiluz commented on reference/forms/types/dateinterval.rst
> +      'invert' => 'form.trans.invert',
@HeahDude thanks for explaining the error. Hopefully I've fixed it in my other commit.

2017-01-25 10:32 UTC, HeahDude commented
Thank you @javiereguiluz for documenting it!

👍

Status: Reviewed

2017-01-31 21:56 UTC, xabbuh commented
Thank you Javier.

2017-01-31 21:57 UTC, closed without merging