Use the Ldap factory in the ldap service definition
symfony/symfony-docs pull request #7413
Opened 2017-01-26 00:17 UTC by nietonfir

as LdapClient has been marked deprecated in 3.1.

Refs symfony/symfony#19008

@csarrazi Hope this is correct.

2017-01-30 14:37 UTC, xabbuh requested changes

2017-01-30 14:37 UTC, xabbuh commented on security/ldap.rst
>              ->setDefinition('ldap', new Definition(LdapClient::class, array(
Looks like you need to update the class name here and add the factory too.

2017-01-30 15:05 UTC, csarrazi commented
@nietonfir I would advise you to make your pull request against the existing PR for the 3.1 version of the component: See #6982

2017-01-30 22:22 UTC, nietonfir commented
@csarrazi @xabbuh Rebased from #6982 and updated the PHP service definition.

2017-03-31 19:09 UTC, stephenyeargin commented on security/ldap.rst
> +                      debug: false,      # Enable debugging output
trailing comma

2017-07-09 15:20 UTC, javiereguiluz approved these changes

2017-07-09 20:34 UTC, csarrazi commented
👍

2017-09-15 10:59 UTC, xabbuh commented
@nietonfir I am sorry that we did not merge your PR earlier. In the meantime, support was dropped for Symfony 3.1 and 3.2 and we did some other changes to the Ldap component docs. Could you rebase your PR onto the `3.3` branch?

2017-09-18 21:41 UTC, nietonfir commented
Done.

2017-09-19 09:13 UTC, xabbuh approved these changes

2018-01-02 12:15 UTC, javiereguiluz commented
@nietonfir thanks for this contribution and I'm sorry it took us so long to merge this.

2018-01-02 12:15 UTC, merged