[WIP] Adding documentation about the simple cache PSR-16 implementation
symfony/symfony-docs pull request #7417
Opened 2017-01-26 11:45 UTC by weaverryan

Hi guys!

This covers #7409!

But I still have a few minors todos

* talk about converting between PSR-6 & PSR-16
* PhpArrayAdapter/Cache and PhpFilesAdapter/Cache are not covered yet

Cheers!

2017-01-26 11:46 UTC, weaverryan commented on components/cache.rst
> +------------------------------------------
@nicolas-grekas Is this small section accurate? Everything else is straightforward - I just wanted you to check this one spot! Thanks!

2017-01-26 23:33 UTC, nicolas-grekas reviewed
LGTM, thanks!

2017-01-26 23:33 UTC, nicolas-grekas commented on components/cache.rst
> +    To find out more about each of these classes, you can read th
you can read theee

2017-01-26 23:35 UTC, nicolas-grekas commented on components/cache/cache_pools.rst
> +    $cache = new TraceableAdapter(array($fileCache));
No array wrapper

2017-01-27 09:51 UTC, javiereguiluz commented on components/cache.rst
> +Simple Caching (PSR-16)
I'd move the simple cache part (PSF-16) before the complex cache part (PSR-6). That's the usual practice in docs: simple first and then build up to complex.

2017-01-27 09:52 UTC, javiereguiluz commented on components/cache.rst
> +one of the built-in cache clases. For example, to create a filesystem-based cache,
`clases` -> `classes`

2017-01-27 09:52 UTC, javiereguiluz commented on components/cache/cache_pools.rst
> +Cache Pools & Supported Adapters
`&` -> `and` ?

2017-01-27 09:53 UTC, javiereguiluz commented on components/cache/cache_pools.rst
> +        ['persistent_id' => '_products_cache']
Long array syntax here.

2017-01-27 09:53 UTC, javiereguiluz commented on components/cache/cache_pools.rst
> +    $memcachedClient = MemcachedAdapter::createConnection([
And here too, long array syntax

2017-01-27 09:54 UTC, javiereguiluz requested changes
Thanks for adding this!

2017-01-27 22:40 UTC, weaverryan commented
Feedback applied! And I added the last section about converting between the 2 caches

Status: Needs Review

2017-02-01 09:38 UTC, javiereguiluz commented on components/cache.rst
> +    $cache->deleteItem('stats.num_products');
`deleteItem()` should be `delete()` ?

2017-02-01 16:08 UTC, javiereguiluz commented on components/cache/cache_pools.rst
> +    $memcachedClient = MemcachedAdapter::createConnection(array(
Is this repeated `$memcachedClient` variable defined on purpose? Should we merge its contents with the previous variable?

2017-02-01 16:10 UTC, javiereguiluz approved these changes
👍 

Status: reviewed

2017-02-06 15:25 UTC, closed without merging