Update cache_pools.rst
symfony/symfony-docs pull request #7451
Opened 2017-02-06 19:46 UTC by crislinu

When retrieving an item from cache you have to use `getItem()` and not `get()`

The `Psr\Cache\CacheItemPoolInterface` doesn't declare the `get` method

2017-02-07 14:09 UTC, xabbuh requested changes

2017-02-07 14:09 UTC, xabbuh commented on components/cache/cache_pools.rst
> +    $userFriends = $cache->getItem('user_'.$userId.'_friends');
We now also need to call `get()` on the return value (the cache pool does not return the cached value, but a `CacheItemInterface` instance).

2017-02-07 14:31 UTC, crislinu commented on components/cache/cache_pools.rst
> +    $userFriends = $cache->getItem('user_'.$userId.'_friends');
It's just about saving cache items. 

I don't think it is necessary to get the value if you just want to save the value into cache.

2017-02-07 14:34 UTC, xabbuh commented on components/cache/cache_pools.rst
> +    $userFriends = $cache->getItem('user_'.$userId.'_friends');
Ah indeed, I misread the following code.

2017-02-07 14:35 UTC, xabbuh approved these changes
:+1:

Status: Reviewed

2017-02-07 19:41 UTC, javiereguiluz approved these changes
👍

2017-02-19 14:04 UTC, xabbuh commented
Good catch, thanks @crislinu.

2017-02-19 14:04 UTC, merged