[Form] Compare fields inside a RepeatedType through compare option
symfony/symfony-docs pull request #7484
Opened 2017-02-14 11:49 UTC by MetalArend

This adds documentation on the compare field, added by a new feature PR on symfony/symfony.

2017-02-14 12:34 UTC, xabbuh commented on reference/forms/types/repeated.rst
> +When this option has a null value, it uses internally a callable comparable to:
You need a second colon here so that the following paragraph is treated as a code block.

2017-02-14 12:36 UTC, MetalArend commented on reference/forms/types/repeated.rst
> +When this option has a null value, it uses internally a callable comparable to:
So, might be more interesting to add backticks around that code block?

2017-02-14 12:40 UTC, xabbuh commented on reference/forms/types/repeated.rst
> +When this option has a null value, it uses internally a callable comparable to:
No not really. The alternative to the double colon would be the `code-block` directive like this:

```rst
.. code-block:: php

    $builder->add('password', RepeatedType::class, array(
        'compare'  => function ($value1, $value2) {
            return $value1 === $value2;
        },
    ));
```

But throughout the docs we prefer the double colon if the previous paragraph ended with a colon and we want to show a PHP code example.

2017-02-27 19:20 UTC, HeahDude requested changes

2017-02-27 19:20 UTC, HeahDude commented on reference/forms/types/repeated.rst
> +|             | - `compare`_                                                           |
Form options are sorted alphabetically, can you please preserve it?

2017-02-27 19:20 UTC, HeahDude commented on reference/forms/types/repeated.rst
> +**compare**: ``callable`` **default**: ``null``
``**compare**` => `**type**`

2017-02-27 19:20 UTC, HeahDude commented on reference/forms/types/repeated.rst
> +The two underlying fields' values will be compared by this callable. The callable receives two values to compare, and should return a boolean: true if the fields are considered equal, false otherwise
I think you can omit the first sentence and start directly with `The callable receives two values to compare`.

2017-02-27 19:20 UTC, HeahDude commented on reference/forms/types/repeated.rst
> +When this option has a null value, it uses internally a callable comparable to::
"By default a strict comparison is done."  or something similar could be enough.

Instead you could give an example (not necessarily with code) where the option can be useful.

2017-02-28 19:33 UTC, HeahDude approved these changes
Very nice improvement to use the key as third argument 👍

2017-03-07 08:19 UTC, MetalArend commented
Should I rebase this on master, to be able to complete the Travis CI build?

2017-03-07 09:55 UTC, xabbuh commented
@MetalArend I restarted the build. It's passing now.

2017-03-07 13:05 UTC, HeahDude commented on reference/forms/types/repeated.rst
> +The callable receives two values to compare, and should return a boolean: true if the fields are considered equal, false otherwise. The callable also receives the currently compared key as a third va
Is it worth having "try", "false", and function like "password_hash" surrounded with back sticks?

2018-04-17 07:18 UTC, closed without merging