Update 'ide' example in framework.rst
symfony/symfony-docs pull request #7513
Opened 2017-02-19 17:09 UTC by harcod

The example 'ide' configuration was different from the actual format required for PhpStorm.  See README at https://github.com/aik099/PhpStormProtocol to verify the correct format as 

> phpstorm://open?url=file://%f&line=%l

2017-02-22 08:52 UTC, javiereguiluz approved these changes
👍 

I've asked in the Symfony Slack and some actual users of PHPStorm have said that the proposed change is correct.

Thanks @harcod.

2017-02-22 09:05 UTC, javiereguiluz requested changes
I'm sorry ... but there has been some confusion!!  The existing syntax works, but the proposed changes don't work!!

Then we'll need more reviews to accept this proposal.

2017-02-22 09:28 UTC, pierredup commented
The syntax `phpstorm://open?url=file://%f&line=%l` is only used by the plugin https://github.com/aik099/PhpStormProtocol.
Since PHPStorm 8 EAP 138.190, PHPStorm supports the protocol natively using the existing syntax used by the docs.

So IMO there is no change needed.

2017-02-22 11:31 UTC, xabbuh commented
👍 see also https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L134

Status: Reviewed

2017-02-22 13:13 UTC, xabbuh commented
> Since PHPStorm 8 EAP 138.190, PHPStorm supports the protocol natively using the existing syntax used by the docs.

Does that mean we should update the default value in the Symfony code instead?

2017-02-22 13:34 UTC, pierredup commented
I've created a PR to update the value in Symfony symfony/symfony#21712

2017-02-22 18:11 UTC, harcod commented
Updated docs as suggested by @pierredup in symfony/symfony#21712

2017-02-23 08:33 UTC, pierredup approved these changes
👍

2017-02-28 19:22 UTC, HeahDude approved these changes

2017-03-01 14:52 UTC, pierredup approved these changes
👍

2017-03-01 20:08 UTC, HeahDude commented on reference/configuration/framework.rst
> +following values: ``phpstorm``, ``sublime``,
This line can now be longer.

2017-03-01 20:13 UTC, HeahDude approved these changes
Thanks! 👍

2017-03-03 07:35 UTC, xabbuh commented
Thank you @harcod.

2017-03-03 07:36 UTC, closed without merging