Add docs about the validator TypeTestCase class
symfony/symfony-docs pull request #7578
Opened 2017-03-06 11:33 UTC by pierredup

This update ads the usage of the validator TypeTestCase class to use for testing when validation is required.

It also mentions the added methods in symfony/symfony#21780 to register custom extensions and types

2017-03-06 11:43 UTC, atailouloute commented on form/unit_testing.rst
> +In order to have this option registered, your test needs to extend from the
to extend the .. class would be better, no ? (Without from)

2017-03-06 14:26 UTC, OskarStark requested changes

2017-03-06 14:26 UTC, OskarStark commented on form/unit_testing.rst
> +------------------------------------
please keep the underline as long as the title

2017-03-06 15:53 UTC, xabbuh commented on form/unit_testing.rst
> +``getTypedExtensions``, ``getTypes`` and ``getTypeGuessers`` methods.
This should be part of a separate pull request as we will have to merge it into the `master` branch (the rest can be merged into the docs for Symfony 2.7).

2017-03-06 21:43 UTC, HeahDude reviewed
Thanks for that PR! Can you please separate the changes as @xabbuh asked?

2017-03-06 21:43 UTC, HeahDude commented on form/unit_testing.rst
> +If your forms uses the ``invalid_message`` or ``constraints`` option for validation, you need to
It should either be `If your form uses` or `If your forms use`.

2017-03-06 21:43 UTC, HeahDude commented on form/unit_testing.rst
> +register the validation extension which provides this options.
`this` => `these`

2017-03-06 21:43 UTC, HeahDude commented on form/unit_testing.rst
> +Luckily Symfony provides a custom test class which does this for you.
I would suggest `Luckily Symfony provides a base test class which takes care of it, just extend [class].`

And get rid of the following sentence, what do you think?

2017-03-06 21:43 UTC, HeahDude commented on form/unit_testing.rst
> +    // tests/AppBundle/Form/Type/TestedTypeTests.php
Please remove the last `s` in `TestedTypeTest.php`.

2017-03-07 10:06 UTC, pierredup commented
I created a separate PR for 2.7 #7587.

When that is merged, it should squash this diff to only leave the sentence for the new methods added symfony/symfony#21780

2017-03-08 08:25 UTC, pierredup commented
I removed the validator extension part in this docs, so it's not dependent on other changes, and can be merged to document the new methods added

2017-03-08 10:53 UTC, xabbuh commented on form/unit_testing.rst
> +``getTypedExtensions``, ``getTypes`` and ``getTypeGuessers`` methods.
One thing I forgot: Can you also add a `versionadded` directive that mentions the introduction of the new methods?

2017-03-10 06:47 UTC, HeahDude commented on form/unit_testing.rst
> +    The ``getTypedExtensions``, ``getTypes`` and ``getTypeGuessers`` was introduced in Symfony 3.3.
"The [...] methods were introduced [...]."

2017-03-15 13:34 UTC, roman-1983 approved these changes

2017-03-15 14:32 UTC, OskarStark approved these changes

2017-03-26 14:00 UTC, HeahDude approved these changes
👍

2017-04-15 12:56 UTC, closed without merging

2017-04-15 12:59 UTC, xabbuh commented
Thank you @pierredup. FYI, I have taken the proposed changes from symfony/symfony#22445 taken into account in 68bcaa0a7c11368325882236aa07c349258ab45e.