Update esi.rst
symfony/symfony-docs pull request #7641
Opened 2017-03-16 19:51 UTC by atailouloute

2017-03-17 07:19 UTC, javiereguiluz approved these changes
👍

2017-03-17 08:21 UTC, xabbuh requested changes

2017-03-17 08:21 UTC, xabbuh commented on http_cache/esi.rst
> +            xmlns:doctrine="http://symfony.com/schema/dic/doctrine"
This change looks wrong to me. Instead, the namespace should be changed to `framework`:

```
xmlns:framework="http://symfony.com/schema/dic/framework"
```

2017-03-17 10:27 UTC, atailouloute commented on http_cache/esi.rst
> +            xmlns:doctrine="http://symfony.com/schema/dic/doctrine"
@xabbuh Yes you are right (y), It's fixed

2017-03-17 11:02 UTC, xabbuh approved these changes

2017-04-01 06:31 UTC, xabbuh commented
Thank you for the many good catches and improvements @atailouloute! To ease the merging of all the small fixes I will combine your PRs in a single PR (see #7737) and merge that one instead.

2017-04-01 06:31 UTC, closed without merging