Update esi.rst
symfony/symfony-docs pull request #7653
Opened 2017-03-19 01:16 UTC by atailouloute

Fixing some portions of PHP code that are not surrounded with PHP tags

2017-03-19 01:55 UTC, Nek- requested changes

2017-03-19 01:55 UTC, Nek- commented on http_cache/esi.rst
>          <?php echo $view['actions']->render(
It's useless to have end/open blocks.

2017-03-19 12:32 UTC, javiereguiluz commented on http_cache/esi.rst
>          <?php echo $view['actions']->render(
It's "useless" most of the times ... but in this case this is an example of a PHP template, so you must open/close PHP tags whenever you add PHP code. However, I don't know which is the current practice in the docs regarding the `use ...` imports. Maybe we do an exception for those blocks? Let's ask to @wouterj and @xabbuh. Thanks!

2017-03-19 17:27 UTC, roman-1983 approved these changes

2017-03-20 10:51 UTC, atailouloute commented on http_cache/esi.rst
>          <?php echo $view['actions']->render(
In other template code examples, each piece of PHP code is surrounded by open/close tags as @javiereguiluz said? I just did the same and I am not sure about what's the correct practice in this case

2017-03-26 16:02 UTC, HeahDude approved these changes
👍 Code seems currently broken. This change looks good to me.

2017-04-01 06:31 UTC, xabbuh commented
Thank you for the many good catches and improvements @atailouloute! To ease the merging of all the small fixes I will combine your PRs in a single PR (see #7737) and merge that one instead.

2017-04-01 06:31 UTC, closed without merging