[Serializer] Document the CsvEncoder and the YamlEncoder
symfony/symfony-docs pull request #7654
Opened 2017-03-19 12:45 UTC by GuilhemN

Document the CsvEncoder and the YamlEncoder introduced in https://github.com/symfony/symfony/pull/19197 and https://github.com/symfony/symfony/pull/19326

2017-03-19 12:47 UTC, Nek- approved these changes
:+1:

2017-03-26 15:38 UTC, HeahDude requested changes

2017-03-26 15:38 UTC, HeahDude commented on serializer/encoders.rst
> +This encoder requires the :doc:`Yaml Component </components/yaml>`.
Missing a version added note for this one.

2017-03-26 15:39 UTC, HeahDude approved these changes
Ok I've missed it :)

2017-10-13 15:15 UTC, wouterj commented
Thanks @GuilhemN for documenting these new serializers! Unfortunately, we've waited so long with merging this PR, we cannot merge it in 3.2 (as it's no longer maintained). So I've merged this in 3.3.

I've also slightly changed the wording in b3f570e , because it didn't read nicely anymore now you've moved the json encoder above.

2017-10-13 15:15 UTC, closed without merging