Property access
symfony/symfony-docs pull request #7870
Opened 2017-05-04 05:41 UTC by iulyanp

Hello,

I changed the visibility of the `$children` property and use the `getLastName` method in order for the example to work correctly.

2017-05-04 07:56 UTC, javiereguiluz approved these changes
👍   these fixes look good to me. Thanks!

2017-05-04 08:08 UTC, apfelbox commented on components/property_access.rst
>              $this->lastName = $name;
You should change this to `return $this->lastName;` then.

2017-05-04 08:18 UTC, iulyanp commented on components/property_access.rst
>              $this->lastName = $name;
Thanks

2017-05-04 20:19 UTC, xabbuh requested changes

2017-05-04 20:19 UTC, xabbuh commented on components/property_access.rst
> +        public function getLastName()
I don't understand this change. This section is about modifying objects not reading from them.

2017-05-05 07:19 UTC, iulyanp commented on components/property_access.rst
> +        public function getLastName()
I think this looks better.

2017-05-05 08:02 UTC, xabbuh commented on components/property_access.rst
> +        }
I would move both methods between `setLastName()` and `__set()`. And to match the code style of the Symfony code the opening curly brace should be on its own line. However, we can easily make this change while merging your PR.

2017-05-05 08:02 UTC, xabbuh approved these changes
looks good to me

2017-05-05 15:32 UTC, Simperfit commented
This could be merged 👍 @javiereguiluz

2017-05-05 15:32 UTC, Simperfit approved these changes

2017-05-09 13:26 UTC, javiereguiluz commented
@iulyanp thanks a lot for contributing these fixes and congrats on your first Symfony Docs contribution.

2017-05-09 13:27 UTC, closed without merging