Updated code example for LDAP integration
symfony/symfony-docs pull request #7917
Opened 2017-05-18 14:04 UTC by pmlt

The LdapClient class mentioned in the code example has been deprecated.
The update example, uses the Ldap class directly, as is recommended in
the deprecation notice.

2017-05-21 16:53 UTC, javiereguiluz requested changes
Thanks for fixing this!

It seems that there are some indentation issues in the pull request. Maybe you are using tabs instead of spaces?

2017-05-22 17:05 UTC, pmlt commented
Sorry about that! I have corrected it by adding a commit to this PR; let me know if you want me to squash my commits and submit a new PR.

2017-05-26 07:55 UTC, xabbuh commented on security/ldap.rst
> +            ->setDefinition('ext_ldap_adapter', new Definition(Ldap::class, array(
should be `Adapter::class` instead of `Ldap::class` here

2017-05-26 07:55 UTC, xabbuh approved these changes

2017-05-26 14:24 UTC, pmlt commented
Indeed... sorry about that. Should be good now (I hope)...

2017-05-26 14:49 UTC, xabbuh commented
Thank you @pmlt.

2017-05-26 14:53 UTC, closed without merging