Added alternative syntax using getClickedButton()
symfony/symfony-docs pull request #7931
Opened 2017-05-21 12:53 UTC by ThomasLandauer

2017-05-21 17:26 UTC, javiereguiluz approved these changes

2017-05-22 10:14 UTC, xabbuh requested changes

2017-05-22 10:14 UTC, xabbuh commented on form/multiple_buttons.rst
> +    if ('saveAndAdd' === $form->getClickedButton()->getName()) {
We need to be careful here. Depending on how the form was submitted `getClickedButton()` may return `null`. Then, this example would run into an error as `getName()` could not be executed.

2017-05-22 10:20 UTC, ThomasLandauer commented
@xabbuh Yeah!! That's the very reason why I started to work on this section. I'm addressing the `null` problem in a separate pull request: https://github.com/symfony/symfony-docs/pull/7932

2017-07-25 17:33 UTC, HeahDude approved these changes

2017-09-03 16:32 UTC, merged