Added the command to install babel-preset for babel-loader
symfony/symfony-docs pull request #8058
Opened 2017-06-18 13:47 UTC by bogdaniel

While testing this bundle i was getting hit by an erorr that i can't find the babel preset es2017 which i solved it by installing.
I'm new to this webpack thing and to work like this with javascript. Some people might be in my position and try for hours to solve this. :D

2017-06-18 14:39 UTC, weaverryan requested changes
Small comment, but I like it!

2017-06-18 14:39 UTC, weaverryan commented on frontend/encore/babel.rst
> +This will install the preset that we will use later to configure the babel.
I think this is indeed a good clarification! But what about adding this information as comments in the code block below (right above the es2017 line. We can say something like:

// make sure to install any presets you want to use
// yarn add ...

2017-06-18 16:58 UTC, bogdaniel commented
I hope it is ok now :).

2017-07-09 15:10 UTC, javiereguiluz approved these changes
I propose a minor reword to make the comment easier to understand. But if you don't agree with it, please revert. Thanks!

2017-07-10 09:58 UTC, bogdaniel commented
@javiereguiluz yeap it's ok =D

2017-07-11 18:05 UTC, xabbuh commented
Thank you @bogdaniel.

2017-07-11 18:06 UTC, merged