Add some doc on missing options of framework bundle configuration
symfony/symfony-docs pull request #8061
Opened 2017-06-19 05:37 UTC by Nek-

This is the missing documentation following this commit : https://github.com/symfony/symfony/commit/ac9a527b81a061d91542b4048fb5e0d277b4dfd4

2017-06-19 07:54 UTC, xabbuh commented on reference/configuration/framework.rst
> +**type**: ``boolean`` **default**: ``0``
the default value should be `false`

2017-06-19 07:54 UTC, xabbuh commented on reference/configuration/framework.rst
> +This specifies whether the module will use strict session id mode. If this mode
[...] use the strict [...]

2017-06-19 07:55 UTC, xabbuh commented on reference/configuration/framework.rst
> +is enabled, the module does not accept uninitialized session ID. If
IDs

2017-06-19 07:55 UTC, xabbuh commented on reference/configuration/framework.rst
> +uninitialized session ID is sent from browser, new session ID is sent to
[...] an uninitialized [...]

2017-06-19 07:55 UTC, xabbuh commented on reference/configuration/framework.rst
> +uninitialized session ID is sent from browser, new session ID is sent to
[...] from the browser, a new session ID is generated.

2017-06-19 07:56 UTC, xabbuh commented on reference/configuration/framework.rst
> +This is how many seconds to wait between 2 session metadata updates, it will
two

2017-06-19 07:56 UTC, xabbuh commented on reference/configuration/framework.rst
> +This is how many seconds to wait between 2 session metadata updates, it will
And I would split this into two sentences: "[...] updates. It will [...]"

2017-06-19 07:56 UTC, xabbuh approved these changes

2017-06-19 08:21 UTC, Nek- commented on reference/configuration/framework.rst
> +**type**: ``boolean`` **default**: ``0``
I took the PHP default value. More accurate IMO. But I can change if you want.

2017-06-19 08:27 UTC, xabbuh commented on reference/configuration/framework.rst
> +**type**: ``boolean`` **default**: ``0``
since this is a boolean node having `0` will cause more troubles so I would indeed change it :)

2017-06-19 14:24 UTC, Nek- commented
@xabbuh fixed :). Thanks.

2017-06-20 10:45 UTC, javiereguiluz requested changes

2017-06-20 10:45 UTC, javiereguiluz commented on reference/configuration/framework.rst
> +This specifies whether the module will use the strict session id mode. If this
I don't know the meaning of *"the module"* in this context.

2017-06-20 10:45 UTC, javiereguiluz commented on reference/configuration/framework.rst
> +
Here we are missing the data type and its default value.

2017-06-20 10:45 UTC, javiereguiluz commented on reference/configuration/framework.rst
> +
This extra blank line can be removed.

2017-07-04 10:16 UTC, Nek- commented on reference/configuration/framework.rst
> +
Fixed 👍

2017-07-04 10:17 UTC, Nek- commented
@javiereguiluz everything fixed, I also changed the base branch to 2.7.

2017-07-04 11:58 UTC, Nek- commented
Status: Needs Review

2017-07-09 11:21 UTC, javiereguiluz approved these changes

2017-07-11 17:55 UTC, xabbuh commented
Thank you @Nek-.

2017-07-11 17:55 UTC, merged