Add new symfony4 site type to homestead documentation
symfony/symfony-docs pull request #8078
Opened 2017-06-22 19:34 UTC by michaelesmith

A new site type was added in https://github.com/laravel/homestead/pull/600 for index.php only configurations. This pr adds this information to the homestead documentation.

2017-06-22 19:38 UTC, xabbuh commented on setup/homestead.rst
> +using type: symfony2 and an index.php layout when using type: symfony4.
What is happening when the `symfony` layout (with neither 2 nor 4) is used as it was before?

2017-06-22 19:57 UTC, michaelesmith commented on setup/homestead.rst
> +using type: symfony2 and an index.php layout when using type: symfony4.
When `symfony` is used it defaults to `serve_symfony2.sh` configuration (this hasn't changed). I added the symfony2 for clarity when discussing the new `symfony4` type.

2017-07-06 15:24 UTC, javiereguiluz requested changes
The front controller of Symfony 4 has changed. Instead of `web/index.php`, it'll be `public/index.php`

2017-09-06 10:48 UTC, xabbuh approved these changes

2017-09-06 10:50 UTC, javiereguiluz approved these changes

2017-11-13 13:21 UTC, wouterj commented
Hi @michaelesmith!

I've rebased your PR on the 4.0 version of the docs and added some minor inline code blocks in a seperate commit. This is now merged with PR https://github.com/symfony/symfony-docs/pull/8640. You'll still receive your credits for your nice work! Thanks for documenting this new homestead feature.

2017-11-13 13:21 UTC, closed without merging