File example update
symfony/symfony-docs pull request #8081
Opened 2017-06-23 15:12 UTC by runawaycoin

Update code example to highlight where the $file comes from in second example

2017-07-05 13:51 UTC, OskarStark requested changes

2017-07-05 13:51 UTC, OskarStark commented on reference/forms/types/file.rst
> +            $file = $form['attachment']->getData()
please add the missing `;` at the end

2017-07-06 05:27 UTC, OskarStark approved these changes

2017-07-08 12:51 UTC, kalimerre approved these changes

2017-07-09 13:01 UTC, xabbuh approved these changes

2017-07-11 17:37 UTC, xabbuh commented
Thank you @runawaycoin.

2017-07-11 17:37 UTC, closed without merging