Create composer_prevent_upgrade_conflicts.rst
symfony/symfony-docs pull request #8278
Opened 2017-08-11 09:02 UTC by stoccc

As requested in https://github.com/symfony/symfony-docs/pull/7298#issuecomment-294297047 I added a page regarding php version constraints in composer.json. In fact, when installing Symfony you have to meet some production server requirements.

Without that, for first install that's ok (if you read symfony requirements you can choose the right Symfony version that's shipped with the right libraries version), but doing updates (just running composer update) may break things with libraries being updated that don't meet your server requirements (e.g. php version) or may do nothing (e.g. running composer update symfony/symfony if you have 2.8.12 installed won't install 2.8.15, despite of what is said here http://symfony.com/doc/current/setup/upgrade_patch.html because of the need of twig/twig 1.30.0 - so you would run "composer update symfony/symfony twig/twig" and so on for other such dependencies to obtain the patch update - that's not so confortable!).

Best regards.

2017-08-16 15:44 UTC, xabbuh commented
I am not convinced that this is a good match for the Symfony docs. IMO this is general Composer knowledge and we should only link to their docs (probably https://getcomposer.org/doc/06-config.md#platform). If that part of the Composer documentation is not good enough, effort should better be spent in improving Composer docs as that would benefit every project and not only Symfony.

2017-08-17 11:20 UTC, stoccc commented
@xabbuh sure, but reading just http://symfony.com/doc/master/setup/upgrade_patch.html and all the other available docs on symfony.com it seems that doing an upgrade is very very simple, until you do your first upgrade and see that it's not so simple... just because no one told you to specify a constraint on your composer.json in order to have your compatibility guaranteed. I suggested to add a note in setup.rst, but @wouterj suggested me to create a new file under /setup

2018-05-03 12:53 UTC, Jean85 requested changes
I'm against this kind of thing. Using the `platform` key in the `composer.json` is a workaround, not a good practice, so IMO we shouldn't advertise it in the docs.

The right practice should be having a dev environment that closely matches the production servers where the app will be deployed.

2018-05-24 07:27 UTC, javiereguiluz commented
@stoccc we finally merged #9803, so we're closing here ... but thanks again for your contribution and for helping us improve Symfony Docs!

2018-05-24 07:27 UTC, closed without merging

2018-05-24 07:59 UTC, stoccc commented
you're welcome @javiereguiluz I think  #9803 is a very good solution!