Update performance.rst
symfony/symfony-docs pull request #8332
Opened 2017-09-01 16:50 UTC by seferov

Remove deprecated suggestion

See: https://github.com/symfony/symfony/issues/20668

2017-09-03 13:10 UTC, wouterj requested changes
Great find! Thanks for adding this little note to the docs.

I've added 2 comments where I think this PR can be a little bit updated. If you agree and have some free time, please update your PR (by pushing to the `patch-3` branch on your fork). Otherwise, please comment and we'll take care of them! :)

2017-09-03 13:10 UTC, wouterj commented on performance.rst
> +Use Bootstrap Files (For < PHP 7)
I think we can leave the title as it was

2017-09-03 13:10 UTC, wouterj commented on performance.rst
> +    For PHP 7 and higher versions it is not necessary. It is deprecated for Symfony 4.0.
I believe we used `caution` directives for deprecations in the docs. I think we should also provide a little bit of context to this message, like this:

```rst
.. caution::

    The performance optimalizations in PHP 7 removed any overhead. As such,
    using the bootstrap file is discouraged when using PHP 7+ and was
    deprecated in Symfony 4.0. 
```

2017-09-03 16:52 UTC, javiereguiluz commented
@seferov thanks a lot for this proposal.

A quick message to our doc mergers: this article is going to be revamped soon. See #7960. I'll finish it next week. So, decide if it's worth it to merge this PR too. Thanks!

2017-09-03 19:27 UTC, seferov commented
@wouterj updated as you requested.

@javiereguiluz I just saw your proposal 👍

2017-09-04 07:47 UTC, xabbuh commented on performance.rst
> +    deprecated in Symfony 4.0.
This was deprecated in 3.3. 4.0 will no longer support the bootstrap files.

2018-01-29 11:54 UTC, javiereguiluz commented
Closing it in favor of #9161.

2018-01-29 11:54 UTC, closed without merging