Clarify comment about "Retrieving the User Object"
symfony/symfony-docs pull request #8542
Opened 2017-10-23 21:16 UTC by pathmissing

2017-10-23 21:16 UTC, pathmissing commented
References #8535

2017-10-24 07:54 UTC, javiereguiluz reviewed
If I remember this correctly, @weaverryan was against getting the user via class injection and he prefers to keep promoting the `$this->getUser()` shortcut or long alternative based on the token, etc. So, let' wait for more comments. Thanks!

2017-10-25 20:30 UTC, weaverryan commented
That’s correct! My vote is to only show the ->getUser() way, with a note (maybe inline comment in code?) that says you can also type-hint a UserInterface arg.

2017-10-26 09:43 UTC, pathmissing commented
Changed that. Any particular reason not to use type-hinting in this case? Or is it just because of the better style?

2017-10-30 10:43 UTC, javiereguiluz approved these changes

2017-11-02 00:47 UTC, weaverryan requested changes
Thanks @pathmissing for the fast changes! While reviewing, I noticed we need a few more - I'm glad you opened a PR around this section :).

To your question about why I prefer `$this->getUser()` over type-hinting `UserInterface`, it's mostly that the type-hinting option doesn't provide auto-completion on my custom User methods. Actually, neither does `$this->getUser()`, but you can (and I do) add your own base-class where getUser() has the proper `@return` for *your* User class to get auto-completion.

Thanks!

2017-11-02 00:47 UTC, weaverryan commented on security.rst
>          }
Bah, now that I look a bit more, this is a bit of a mess :/ still. I'd like to propose a few more changes:

1) In the above code, use the simpler `$this->denyAccessUnlessGranted()`.
2) Below, user the simpler `$user = $this->getUser()`.

3) Move the suggestion about UserInterface to below, and I'll suggest a wording tweak too :)
```php
$user = $this->getUser();
// or you can also type-hint a method argument with UserInterface: e.g. "UserInterface $user"
```

4) Below (you need to expand the code-blocks to see it), there is a `versionadded:: 3.2`. I think we should shorten that quite a bit:

```rst
 .. versionadded:: 3.2
     The ability to get the user by type-hinting an argument with UserInterface
     was introduced in Symfony 3.2.
```

2017-11-02 12:09 UTC, pathmissing commented
@weaverryan Thank you for proposing these changes, I implemented them in my latest commit. Creating a base class which returns your custom User for autocompletion is actually a really nice idea, which I am going to implement myself. Thanks for that :)

2017-11-05 20:39 UTC, weaverryan commented
Thank you Marcus!

2017-11-05 20:50 UTC, closed without merging