Clarifying usage of delivery_whitelist
symfony/symfony-docs pull request #8575
Opened 2017-11-01 19:08 UTC by tomhv

There was nothing to suggest that `delivery_whitelist` could not be used on its own. We had to find this out by trial an error.

Hopefully, this change (or better equivalent) will help other people.

Cheers.

2017-11-02 09:17 UTC, wouterj approved these changes
Looks fine by me!

status: reviewed

2017-11-02 09:37 UTC, marcverney requested changes

2017-11-02 11:53 UTC, javiereguiluz commented on email/dev_environment.rst
> +    The ``delivery_whitelist`` option can only be used in conjuction with the ``delivery_addresses`` option.
Can we reword this to make it easier to read? Something like this:

```
The ``delivery_whitelist`` option is ignored when the ``delivery_addresses``
option is not defined.
```

2017-11-03 19:40 UTC, tomhv commented on email/dev_environment.rst
> +    The ``delivery_whitelist`` option can only be used in conjuction with the ``delivery_addresses`` option.
What about this:

The ``delivery_whitelist`` option is ignored unless the ``delivery_addresses`` option is defined.

2017-11-03 19:41 UTC, javiereguiluz commented on email/dev_environment.rst
> +    The ``delivery_whitelist`` option can only be used in conjuction with the ``delivery_addresses`` option.
Nice and concise! I like it. Thanks!

2017-11-03 20:31 UTC, tomhv commented
I need to squash these commits into a single commit, right?

2017-11-04 09:41 UTC, javiereguiluz commented
@tomhv there's no need because we use a tool that squashes everything automatically. Cheers!

2017-11-05 20:26 UTC, weaverryan commented
Thank you @tomhv!

2017-11-05 20:34 UTC, closed without merging