Updated main configuration guide to Flex
symfony/symfony-docs pull request #8588
Opened 2017-11-03 14:37 UTC by wouterj

2017-11-03 14:49 UTC, javiereguiluz approved these changes
Nice changes here! Thanks Wouter.

2017-11-03 14:49 UTC, javiereguiluz commented on configuration.rst
> +parameters need to be defined in the ``.env.dist`` file. If you add or remove
`need to be defined in the ``.env.dist`` file` -> `need to be defined in the ``.env`` file` ?

2017-11-03 14:49 UTC, javiereguiluz commented on configuration.rst
> +The configuration for a package can be found in ``config/packages``. For
`can be found in config/packages` --> `can be found in config/packages/`  please always add a trailing slash when referencing directories so the reader never wonders if it's a dir or a file without extension. Thanks!

2017-11-05 20:31 UTC, weaverryan requested changes

2017-11-05 20:31 UTC, weaverryan commented on configuration.rst
> +The configuration for a package can be found in ``config/packages/``. For
> for each package...

2017-11-05 20:31 UTC, weaverryan commented on configuration.rst
> +package, ``config/services.yaml`` defines a ``locale`` parameter:
How about:

> For example, when you install the *translation* package, a `locale` parameter is added to `config/services.yaml`:

2017-11-05 20:31 UTC, weaverryan commented on configuration.rst
> +parameters need to be defined in the ``.env.dist`` file. If you add or remove
`parameters` -> `variables` (to make it a bit clear that these aren't parameters)

2017-11-05 20:31 UTC, weaverryan commented on configuration.rst
> +keys to ``.env``, add or remove them from ``.env`` too, so both files are
the second should be `.env.dist`.

2017-11-05 22:19 UTC, yceruto commented on configuration.rst
> +``config/packages/translation.yaml``:
``config/packages/framework.yaml`` same for xml and php versions.

2017-11-12 12:16 UTC, wouterj commented
Ready to merge!

2017-11-21 19:06 UTC, weaverryan commented
Wooo! Thank you for this BIG pr Wouter!

2017-11-21 19:07 UTC, closed without merging