Reworded the introduction of event listeners article
symfony/symfony-docs pull request #8603
Opened 2017-11-08 12:28 UTC by javiereguiluz

We have an article explaining the kernel events, so there's no need to link to the KernelEvents class source code.

2017-11-08 15:19 UTC, xabbuh approved these changes

2017-11-10 03:18 UTC, weaverryan requested changes

2017-11-10 03:18 UTC, weaverryan commented on event_dispatcher.rst
> +</components/event_dispatcher>`.
I like this... but this sentence is too long. I think we need a period after `HTTP Request`. And then maybe the next sentence needs a little bit of work.

2017-11-10 03:19 UTC, merged

2017-11-10 03:21 UTC, weaverryan commented
I just re-worded it to save time - see sha: 8c689eca353ff31b2a4977e2d2f446c0a5212fa4

Feel free to re-reword if it's not quite perfect :).