Add new serializer config path
symfony/symfony-docs pull request #8632
Opened 2017-11-13 06:16 UTC by yceruto

See https://github.com/symfony/symfony/pull/24833

2017-11-13 07:51 UTC, xabbuh commented on serializer.rst
> +        # config/packages/serializer.yaml
this should probably not be changed

2017-11-13 13:20 UTC, yceruto commented on serializer.rst
> +        # config/packages/serializer.yaml
Indeed, thanks.

2017-11-14 07:56 UTC, xabbuh approved these changes

2017-11-16 07:31 UTC, weaverryan requested changes

2017-11-16 07:31 UTC, weaverryan commented on serializer.rst
> +  directory of a bundle and in the ``config/serializer/`` directory of your project.
Should we mention the `config/serializer/` directory if your project first *before* talking about `Resources/config` in your bundle?

2017-11-19 14:26 UTC, yceruto commented
Closing this one in favor of https://github.com/symfony/symfony-docs/pull/8687

2017-11-19 14:26 UTC, closed without merging