Updated logging/* articles to Symfony 4
symfony/symfony-docs pull request #8683
Opened 2017-11-16 16:22 UTC by javiereguiluz

2017-11-17 14:05 UTC, weaverryan requested changes

2017-11-17 14:05 UTC, weaverryan commented on logging/monolog_regex_based_excludes.rst
> +        # config/packages/monolog.yaml
I think `config/packages/prod/monolog.yaml`  is more proper - that's really where the user should modify things.

That might affect other logs docs too. In other words, I think we had it wrong before.

2017-11-21 12:31 UTC, weaverryan commented
Status: Needs work

2017-11-26 23:56 UTC, wouterj commented on logging/monolog_console.rst
> +    private $logger;
This is becoming quite unreadable. Can we please at the class definition (`class .... { }`) lines?

2017-11-27 19:12 UTC, merged