[yaml] Fix `!php/*` tag should not contain `:` at the end for Symfony 4
symfony/symfony-docs pull request #8698
Opened 2017-11-18 19:55 UTC by jeromemacias

As mentioned in the [upgrade guide](https://github.com/symfony/symfony/blob/master/UPGRADE-4.0.md):

> The !php/object: tag was removed in favor of the !php/object tag (without the colon).
> The !php/const: tag was removed in favor of the !php/const tag (without the colon).

2017-11-20 14:28 UTC, javiereguiluz approved these changes
Nice! Jérôme, thanks for fixing this.

@xabbuh please review if this change was made only for Symfony 4 or also for Symfony 3.4. Thanks!

2017-11-21 09:09 UTC, xabbuh requested changes

2017-11-21 09:09 UTC, xabbuh commented on components/yaml.rst
> +    // !php/object O:8:"stdClass":1:{s:5:"foo";s:7:"bar";}
this should be `// !php/object 'O:8:"stdClass":1:{s:3:"foo";s:3:"bar";}'`

2017-11-21 09:09 UTC, xabbuh commented on components/yaml.rst
> +    $yaml = '!php/object O:8:"stdClass":1:{s:5:"foo";s:7:"bar";}';
should be `$yaml = '!php/object \'O:8:"stdClass":1:{s:3:"foo";s:3:"bar";}\'';`

2017-11-21 09:10 UTC, xabbuh commented
3.4 is correct, the old example won't work with Symfony 4, but the tag with colon was already deprecated in 3.4

2017-11-21 09:16 UTC, xabbuh approved these changes

2017-11-21 09:16 UTC, jeromemacias commented
@xabbuh Changes done

2017-11-21 14:21 UTC, weaverryan commented
Thank you Jérôme!

2017-11-21 14:21 UTC, closed without merging