Updated the translation/* articles to Symfony 4
symfony/symfony-docs pull request #8733
Opened 2017-11-22 15:16 UTC by javiereguiluz

2017-11-23 16:44 UTC, yceruto commented
Could you to update the framework reference to add the default path option? https://github.com/symfony/symfony-docs/pull/8634/files#diff-c0c158a40398b72fa4f0c9d0accbc169

2017-11-23 16:48 UTC, javiereguiluz commented
@yceruto sorry but I can't. I don't see the default_path in my branch or in 4.0. Is this only on master?

2017-11-23 16:55 UTC, yceruto commented
@javiereguiluz are you asking by Symfony repo or docs? I don't understand the question :/

https://github.com/symfony/symfony/blob/3.4/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L680

https://github.com/symfony/symfony-docs/pull/8634/files#diff-c0c158a40398b72fa4f0c9d0accbc169 It needs to be added to the framework reference?

2017-11-23 17:08 UTC, javiereguiluz commented
yes, I was referring to the docs ... but I'm probably wrong.

2017-11-24 01:59 UTC, weaverryan commented
@javiereguiluz He already did the work for you :). @yceruto just wants you to import his work from another PR: https://github.com/symfony/symfony-docs/pull/8634/files#diff-c0c158a40398b72fa4f0c9d0accbc169

2017-11-24 02:01 UTC, weaverryan requested changes
Minor changes, then 👍 from me

2017-11-24 02:01 UTC, weaverryan commented on translation.rst
> +install the translator before using it:
I'm not mentioning this in 4.0: I'm assuming they have Flex installed and have that dir structure. If we don't assume this, then the docs become a mess.

2017-11-24 02:01 UTC, weaverryan commented on translation.rst
> +The previous creates an initial config file where you can define the default
> The previous command...

2017-11-24 02:01 UTC, weaverryan commented on translation.rst
> +locale of the app and the :ref:`fallback locales <translation-fallback>` used
> ... fallback locales that will be used if Symfony...

2017-11-27 17:52 UTC, weaverryan commented
Status: Needs work

2017-11-27 19:56 UTC, merged