Update without_class.rst
symfony/symfony-docs pull request #8780
Opened 2017-11-29 20:40 UTC by tabbi89

`$form->isValid()` no validation is done here this method only returns bool flag if any errors occurred during validation or false if a form was not submitted. Validation happens when executing `handleRequest()` or `submit()`.

2017-11-29 21:16 UTC, yceruto requested changes
:+1:

2017-11-29 21:19 UTC, yceruto approved these changes

2017-11-30 11:12 UTC, xabbuh approved these changes

2017-11-30 11:42 UTC, javiereguiluz approved these changes

2017-11-30 11:49 UTC, xabbuh commented
Thank you @tabbi89.

2017-11-30 11:49 UTC, merged