Add new serializer empty_data feature doc
symfony/symfony-docs pull request #8914
Opened 2017-12-20 20:05 UTC by Nek-

This is the documentation related to the following feature: https://github.com/symfony/symfony/pull/25493

2018-01-19 12:03 UTC, fabpot requested changes

2018-01-19 12:03 UTC, fabpot commented on components/serializer.rst
> +of theses parameters the serializer will throw an exeception because it can't create the object.
typo `exeception`

2018-02-01 14:08 UTC, Nek- commented
@fabpot fixed

2018-02-20 15:53 UTC, javiereguiluz approved these changes
@Nek- thanks for contributing this doc. I liked it a lot and everything is well explained. I just made a minor reword to focus more on the general use case ("Handling Constructor Arguments") instead of the "value object" detail. Thanks!

2018-05-16 10:56 UTC, dunglas commented on components/serializer.rst
> +If the constructor of a class defines arguments, as usually happens with
It's not exact: the serializer deals well with constructor arguments, if they are present in the object to deserialize.

The `default_constructor_arguments` is useful only when the value has not been provided in the data to deserialize.

2018-06-04 17:29 UTC, Nek- commented
Fixed and rebased. 👍

2018-06-27 13:42 UTC, javiereguiluz commented
@Nek- I'm sorry it took us so long to merge. Thanks!

2018-06-27 13:44 UTC, merged