issue-13589: adjust docs for custom-false-values for checkbox type
symfony/symfony-docs pull request #9031
Opened 2018-01-10 10:54 UTC by leberknecht

refs #13589 on symfony/symfony repo

2018-03-18 19:07 UTC, javiereguiluz commented
@vudaltsov we'd need your review about this proposal related to forms. Thanks a lot!

2018-03-18 22:33 UTC, vudaltsov commented
@javiereguiluz , thanx for pinging me on this :)

I agree with the contents of this PR, but I would also dedicate a paragraph to the `false_values` option in the `Field Options` section.

2018-03-18 23:13 UTC, vudaltsov requested changes
Let's add a section under `Field Options`.

2018-05-17 10:01 UTC, linaori approved these changes

2018-05-18 06:24 UTC, xabbuh requested changes

2018-05-18 08:36 UTC, leberknecht commented on reference/forms/types/checkbox.rst
> +|             | - `false_values`_                                                      |
Doh! Indeed, sorry. Added.

2018-05-18 08:37 UTC, xabbuh commented on reference/forms/types/options/false_values.rst.inc
> +~~~~~
this line must contain as many `~` characters as the length of the headline

2018-05-18 14:01 UTC, xabbuh commented on reference/forms/types/options/false_values.rst.inc
> +An array of values to be interpreted as `false`.
we need to backticks here

2018-05-18 14:03 UTC, xabbuh commented on reference/forms/types/checkbox.rst
> +|             | - `false_values`_                                                      |
Oh and maybe we should sort the options alphabetically (i.e. put `false-values` before `value`). This must then also be taken into account below then.

2018-05-18 15:03 UTC, leberknecht commented on reference/forms/types/options/false_values.rst.inc
> +An array of values to be interpreted as `false`.
"doh!" again :D fixed

2018-05-18 15:19 UTC, xabbuh approved these changes

2018-05-18 20:40 UTC, vudaltsov approved these changes

2018-05-24 09:04 UTC, javiereguiluz commented
@leberknecht thanks for this contribution! Sadly I couldn't merge it with the proprietary tool we use to merge pull requests in Symfony repos. I tried to solve it but I couldn't (for some unknown reasons, the conflict was huge with tens of conflicting files). So, I ended up replicating your changes in this other pull request: #9812. I'm really sorry but I wanted to assure you that I tried to maintain your commits and pull request but I couldn't. I'm sorry.

2018-05-24 09:04 UTC, closed without merging

2018-05-24 12:03 UTC, leberknecht commented
:D No worries!