Add missing allow_if_all_abstain parameter
symfony/symfony-docs pull request #9125
Opened 2018-01-24 11:03 UTC by Nightbr

Missing documentation on access_decision_manager

2018-01-24 11:44 UTC, jmsche requested changes

2018-01-24 11:44 UTC, jmsche commented on security/voters.rst
> +                'allow_if_all_abstain' => true
I would add a comma at the end of the line

2018-01-25 11:36 UTC, javiereguiluz approved these changes
Even if setting `allow_if_all_abstain` to `true` won't be the best decision in all cases, the name of the option is self-explanatory and readers won't have a problem adapting it to their needs.

2018-01-25 11:39 UTC, javiereguiluz commented
@Nightbr thanks for this! I've merged it in the 2.7 branch instead, so GitHub may make it look closed instead of merged ... but it's merged.

2018-01-25 11:40 UTC, closed without merging

2018-01-26 18:28 UTC, xabbuh commented
I think we should have set it to `false` here. Above the config examples we always talk about permission is only granted if *all*  voters grant access. However, setting `allow_if_all_abstain` to `true` will have the opposite effect if no voter makes (is able to make) a decision.