Swap $key and $index parameters in ChoiceType
symfony/symfony-docs pull request #9173
Opened 2018-01-30 08:58 UTC by technetium

I've noticed the second parameter in the callback function for the
options in the ChoiceType represents the index and the third the
key.

This patch brings the documentation in line with the code.

2018-03-23 09:55 UTC, xabbuh commented on reference/forms/types/choice.rst
> +        'choice_label' => function($category, $index, $key) {
`function($category, $key, $value)`

2018-03-23 09:57 UTC, xabbuh commented on reference/forms/types/choice.rst
> +        'choice_attr' => function($category, $index, $key) {
`function($category, $key, $value)`

2018-03-23 09:59 UTC, xabbuh commented on reference/forms/types/choice.rst
> +        'group_by' => function($category, $index, $key) {
`function($category, $key, $value)`

2018-03-23 09:59 UTC, xabbuh commented on reference/forms/types/options/choice_attr.rst.inc
> +        'choice_attr' => function($val, $index, $key) {
`function($category, $key, $value)`

2018-03-23 09:59 UTC, xabbuh commented on reference/forms/types/options/choice_label.rst.inc
> +        'choice_label' => function ($value, $index, $key) {
`function($category, $key, $value)`

2018-03-23 09:59 UTC, xabbuh commented on reference/forms/types/options/group_by.rst.inc
> +        'group_by' => function($val, $index, $key) {
`function($category, $key, $value)`

2018-03-23 11:32 UTC, vudaltsov requested changes
Agree with @xabbuh, 2 and 3 arguments should be named `$key` and `$value`, the first argument should be named according to choice data.

2018-05-28 06:50 UTC, javiereguiluz commented
I'm afraid this PR stalled and now it has some conflicts. So I've opened #9835 to finish it. Thanks @technetium for opening this and thanks to reviewers.

2018-05-28 06:50 UTC, closed without merging