Add documentation about manipulating console output
symfony/symfony-docs pull request #9304
Opened 2018-02-21 05:18 UTC by pierredup

Add documentation about manipulating console output (symfony/symfony#24363)

2018-02-21 05:24 UTC, fabpot requested changes

2018-02-21 05:24 UTC, fabpot commented on console/manipulating_output.rst
> +A section can be manipulated individually, and multiple sections can appended to the output.
`can be`?

2018-02-21 05:24 UTC, fabpot commented on console/manipulating_output.rst
> +This will return an instance of of the :class:`Symfony\\Component\\Console\\Output\\ConsoleSectionOutput`
double `of`

2018-02-21 05:24 UTC, fabpot commented on console/manipulating_output.rst
> +
double blank line

2018-02-21 05:24 UTC, fabpot commented on console/manipulating_output.rst
> +Clearing s Section
`a`?

2018-02-21 05:24 UTC, fabpot commented on console/manipulating_output.rst
> +:method:`Symfony\\Component\\Console\\Output\\ConsoleSectionOutput::overwrite` method.
`clear`?

2018-04-24 23:30 UTC, ndench approved these changes
Looks good to me. Thanks for the contribution.

2018-05-18 01:29 UTC, ndench approved these changes
Very useful. Thanks!

2018-05-27 15:50 UTC, javiereguiluz commented
@pierredup thanks a lot for contributing these docs! (and for implementing the feature too ... it's amazing!) I like the contents, but I'd prefer another organization, so I'm going to merge this PR "as is" and then I'll create a different PR to reorganize contents. Cheers!

2018-05-27 15:53 UTC, closed without merging