write how to use the stopwatch in symfony profiler
symfony/symfony-docs pull request #9320
Opened 2018-02-23 14:28 UTC by SimonHeimberg

2018-02-23 14:29 UTC, SimonHeimberg commented
Or does this belogn into https://symfony.com/doc/current/profiler.html ?

Learned from https://stackoverflow.com/questions/26436987/symfony-stopwatch-events-not-appearing-in-profiler-timeline

2018-03-13 22:22 UTC, wouterj requested changes
Yes, I do like to make this a sub article in the profiler guide. This is not so much about the Stopwatch component, but more about the usage of that component in the framework. As such, it belongs to the guides.

Are you willing to create a new article, or shall we take of this PR (keeping your commit for credits)? If you want to create the article, create a new file in `/profiler/` and reference it in `/profiler.rst`.

2018-03-13 22:22 UTC, wouterj commented on components/stopwatch.rst
> +In a Controller, do:
This should be a double colon (`::`) in order to mark the next block as PHP code block.

2018-03-13 22:22 UTC, wouterj commented on components/stopwatch.rst
> +Or inject `Symfony\Component\Stopwatch\Stopwatch` by autowiring.
Please use ``:class:`Symfony\\Component\\Stopwatch\\Stopwatch` `` to (a) render it correctly and (b) directly reference it's API documentation.

I think the line below may also be added directly to this paragraph.

2018-09-12 08:08 UTC, SimonHeimberg commented
I am not a great author, but I tried a separate article anyway in #10332.

2018-11-14 22:37 UTC, ndench commented
I think this should be closed in favour of #10332.

2018-11-28 09:42 UTC, xabbuh commented
closing here in favour of #10332

2018-11-28 09:42 UTC, closed without merging