[WIP] add example for using a voter to restrict switch_user
symfony/symfony-docs pull request #9353
Opened 2018-02-26 19:00 UTC by jwmickey

2018-03-31 22:44 UTC, atailouloute commented on security/impersonating_user.rst
> +    namespace AppBundle\Security\Voter;
`namespace App\Security\Voter;`to be coherent with SF4 structure

2018-03-31 22:44 UTC, atailouloute commented on security/impersonating_user.rst
> +                return self::ACCESS_GRANTED;
It should be `return true;` no?

2018-03-31 22:44 UTC, atailouloute commented on security/impersonating_user.rst
> +            ->setArgument('$roleHierarchy', '@security.role_hierarchy');
This should be `new Reference('security.role_hierarchy')`

2018-04-04 02:49 UTC, jwmickey commented
Thank you for reviewing this PR @atailouloute, I have added your recommendations.

2018-04-10 11:39 UTC, xabbuh commented on security/impersonating_user.rst
> +            $roles = $this->roleHierarchy->getReachableRoles($token->getRoles());
I would leave out the role hierarchy here. It IMO adds more complexity than needed to understand the example.

2018-04-10 11:40 UTC, xabbuh commented
I think we should add a headline before the new section to make it stand out more. And we should then also add a `versionadded` directive.

2018-04-24 23:04 UTC, ndench approved these changes
Thanks for the contribution. This is a cool idea, at my old job we just gave ROLE_SUPER_ADMIN to all the employees, which always felt gross. If only we'd thought of doing this!

2018-05-17 10:10 UTC, linaori requested changes

2018-05-17 10:10 UTC, iltar commented on security/impersonating_user.rst
> +of a full ACL implementation, you can use a security voter.  For example, you
2 spaces should be one `voter.  For example`

2018-05-17 10:10 UTC, iltar commented on security/impersonating_user.rst
> +    the role hierarchy.  The reason for this is to avoid accidentally granting access to an
double spaces: `hierarchy.  The reason`

2018-05-17 10:10 UTC, iltar commented on security/impersonating_user.rst
> +Thanks to autowiring, we only need to configure the role hierarchy argument when registering
`we only need to configure`. Correct me if I'm wrong, but I believe the Symfony docs point towards "you", rather than "we".

2018-05-18 01:27 UTC, ndench approved these changes
Sweet example.

2019-01-04 08:37 UTC, javiereguiluz commented
@jwmickey thanks a lot for contributing this nice example (and thanks to all reviewers!). I apologize for having taken so long to merge it.

I tried to merge but there were lots of conflicts ... so I created #10842 to replace this and that is now merged. Of course I kept your original commits so you'll get full credit of your contribution.

So, let's close this now that #10842 is merged. Thanks!

2019-01-04 08:37 UTC, closed without merging

2019-01-04 14:47 UTC, jwmickey commented
Thanks @javiereguiluz, glad this was able to be included!