[WCM] Adding MigratingSessionHandler docs
symfony/symfony-docs pull request #9496
Opened 2018-03-26 10:18 UTC by rossmotley

Adding `MigratingSessionHandler` documentation for https://github.com/symfony/symfony/pull/26096

2018-05-17 10:14 UTC, linaori requested changes

2018-05-17 10:14 UTC, iltar commented on components/http_foundation/session_configuration.rst
> +* After verifying everything, switch from the migrating handler to the new handler
Missing a full stop at the end

` * After verifying everything, switch from the migrating handler to the new handler.`

2018-05-17 10:27 UTC, linaori approved these changes

2018-05-18 01:23 UTC, ndench approved these changes

2018-05-18 06:18 UTC, xabbuh commented
Would it make sense to move the detailed description to a new guide and only link to it from this page?

2018-05-18 06:26 UTC, iltar commented
@xabbuh it looks like the page is becoming quite big already with this addition, it might be an option

2018-05-22 16:06 UTC, javiereguiluz approved these changes

2018-05-24 08:44 UTC, javiereguiluz commented
Thanks @rossmotley. This was a really nice first contribution to Symfony Docs! Thank you.

2018-05-24 08:44 UTC, merged