[Routing] i18n routing.
symfony/symfony-docs pull request #9515
Opened 2018-03-28 20:39 UTC by frankdejonge

2018-03-28 20:40 UTC, frankdejonge commented
I've chosen to use the PHP configurator DSL as the example. I hadn't seen it used previously in the examples. This might be something we'll need to look into in a broader sense.

2018-03-28 20:45 UTC, frankdejonge commented
Status: Needs work

2018-03-29 12:47 UTC, nicolas-grekas approved these changes

2018-04-19 07:38 UTC, DylanDelobel commented
If this one is merged, should close #9510

2018-04-19 08:41 UTC, xabbuh requested changes

2018-04-19 08:41 UTC, xabbuh commented on routing.rst
> +             * @Route("/blog", name="blog_list")
The annotation example look wrong to me. It should have the same routes as the YAML, XML, and PHP examples.

2018-04-19 08:41 UTC, xabbuh commented on routing.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
should be stripped to match the length of the headline

2018-04-19 08:41 UTC, xabbuh commented on routing.rst
> +should be used during the request. Defining routes this way also eliminated the
"eliminates"?

2018-04-19 08:41 UTC, xabbuh commented on routing.rst
> +When you've defined localized routes Symfony will use the current request locale
[...] routes, Symfony [...]

2018-04-19 08:41 UTC, xabbuh commented on routing.rst
> +locale you must pass the ``_locale`` in the parameters array::
"for alternative locales" or "for an alternative locale"

2018-04-24 13:02 UTC, michaelperrin commented
This paragraph should be removed with this new documentation: http://symfony.com/doc/master/routing.html#translating-routes

2018-05-18 05:29 UTC, maxbeckers commented on routing.rst
> +When a localized route is matched Symfony will automatically know which locale
`When a localized route is matched, Symfony will automatically know, which ...` and perhaps `matches` instead of `is matched`?

2018-05-27 17:42 UTC, javiereguiluz commented
Frank, thanks for contributing these docs. Thank you also for implementing this fantastic feature! The community loves it and it's definitely one of the best new features of Symfony 4.1. By the way, congrats on your first Symfony Docs contribution too!

2018-05-27 17:42 UTC, merged

2018-05-28 11:39 UTC, frankdejonge commented
@javiereguiluz thank you! 👍