New section about JSON file manifest strategy
symfony/symfony-docs pull request #9548
Opened 2018-04-04 13:45 UTC by jeremyjumeau

@see https://symfony.com/blog/new-in-symfony-3-3-manifest-based-asset-versioning

2018-04-19 10:28 UTC, tomtomau requested changes
Looks great - thanks for your contribution!

Could you additionally update [frontend/encore/versioning.rst](https://github.com/jeremyjumeau/symfony-docs/blob/master/frontend/encore/versioning.rst) to link through to this section to "read more" about asset versioning?

I know when I was getting started with Encore it would have been helpful 👍

2018-04-19 10:28 UTC, tomtomau commented on components/asset.rst
> +<https://webpack.js.org/>`_, which generate a JSON file mapping all source file names to their corresponding output file. For example::
which **generates**

2018-04-19 17:25 UTC, jeremyjumeau commented
Thanks for your feedback! I will update the "learn more" section of Encore Component too!

2018-04-20 08:10 UTC, jeremyjumeau reviewed
@tomtomau do you think we should add a link to *Encore Versioning* documentation in the asset's doc "Learn More" section?

```
Learn more
----------

* :doc:`frontend/encore/versioning`
```

2018-05-17 13:36 UTC, javiereguiluz approved these changes

2018-05-17 14:20 UTC, closed without merging