Fixed ChoiceType trim option
symfony/symfony-docs pull request #9598
Opened 2018-04-15 08:00 UTC by HeahDude

Ref symfony/symfony#26932.

2018-04-18 08:54 UTC, javiereguiluz approved these changes
Nice! Thanks Jules.

2018-04-18 19:36 UTC, HeahDude commented
Thank you for the rewarding 👍

2018-04-20 10:07 UTC, xabbuh requested changes

2018-04-20 10:07 UTC, xabbuh commented on reference/forms/types/choice.rst
> +~~~~
I think we should move the description to its own file to be able to reuse it in other form types. This is currently missing in some documents (see the failing build).

2018-05-05 10:07 UTC, wouterj commented
Ping @HeahDude can you please fix this PR according @xabbuh's comment?

2018-05-07 07:15 UTC, xabbuh commented on reference/forms/types/choice.rst
> +|             | - `choice_type_trim`_                                                        |
here we would still have to use `trim`

2018-05-07 08:08 UTC, HeahDude commented on reference/forms/types/choice.rst
> +|             | - `choice_type_trim`_                                                        |
Was not sure ^^. Fixed, thanks!

2018-05-07 08:56 UTC, xabbuh commented on reference/forms/types/options/choice_type_trim.rst.inc
> +the given choice values exactly (and they could contain white spaces).
"whitespaces" (without the space)?

2018-05-07 08:56 UTC, xabbuh approved these changes

2018-05-07 19:26 UTC, HeahDude commented on reference/forms/types/options/choice_type_trim.rst.inc
> +the given choice values exactly (and they could contain white spaces).
Agreed, fixed. Thanks again!

2018-05-08 18:07 UTC, wouterj commented
Thanks Jules.

2018-05-08 18:08 UTC, merged