Update code style of Guard auth
symfony/symfony-docs pull request #9753
Opened 2018-05-09 12:17 UTC by Saphyel

I just converted array() into []

2018-05-10 14:36 UTC, ricknox commented on security/guard_authentication.rst
> +        public function onAuthenticationFailure(Request $request, AuthenticationException $exception): JsonResponse
As far as I know the documentation, return type declarations are not used.
@javiereguiluz Can you give an opinion on this?

2018-05-10 14:37 UTC, ricknox commented on security/guard_authentication.rst
> +        public function start(Request $request, AuthenticationException $authException = null): JsonResponse
The same question as before, unsure if return type declarations are been used.

2018-05-10 15:02 UTC, ghost requested changes
Thank you for the inconsistency correction. However, in the Symfony Docs we still use the long array() syntax.

2018-05-14 07:00 UTC, xabbuh commented
Thank you for your work @Saphyel. But unfortunately, @ricknox is right and I need to close your PR as we indeed still use the long array syntax in the docs. I hope to see you soon again with some other changes. :)

2018-05-14 07:00 UTC, closed without merging