Fixed the params in ChoiceType methods
symfony/symfony-docs pull request #9835
Opened 2018-05-28 06:50 UTC by javiereguiluz

This finishes #9173.

2018-05-28 07:07 UTC, vudaltsov requested changes

2018-05-28 07:07 UTC, vudaltsov commented on reference/forms/types/options/choice_label.rst.inc
> +        'choice_label' => function ($category, $key, $value) {
Same here `($choiceValue, $key, $value)`.

2018-05-28 07:07 UTC, vudaltsov commented on reference/forms/types/options/group_by.rst.inc
> +        'group_by' => function($vategory, $key, $value) {
Same here `($choiceValue, $key, $value)`.

2018-05-28 07:07 UTC, vudaltsov commented on reference/forms/types/options/group_by.rst.inc
>              if ($value <= new \DateTime('+3 days')) {
Here the comparison should be against the first argument `$choiceValue`. I will check that for 2.8. But it's definitely true for 4.0. The first argument of the callback is the model data. The third `$value` is just a string from request.

2018-05-28 07:44 UTC, javiereguiluz commented on reference/forms/types/options/choice_attr.rst.inc
> +        'choice_attr' => function($category, $key, $value) {
I'm going to do that change ... but then `'choice_attr' => function($choiceValue, $key, $value)` is going to look confusing. choiceValue and value? What's the difference?

2018-05-28 08:49 UTC, vudaltsov commented on reference/forms/types/choice.rst
empty line

2018-05-28 08:53 UTC, vudaltsov requested changes
Sorry, found some other things that could be fixed in this PR. And some other improvements I will do in a new one.

2018-05-28 08:53 UTC, vudaltsov commented on reference/forms/types/options/choice_label.rst.inc
>              if ($value == true) {
I think that is makes more sense to check `true === $choiceValue` here.

2018-05-29 14:00 UTC, javiereguiluz commented
@vudaltsov I thought you were going to create a new PR instead of this one ... so I was waiting :)  I'm going to finish and merge this so you can create a new PR. Thanks!

2018-05-29 14:06 UTC, javiereguiluz commented
This is now merged! @vudaltsov when you create your PR, please make any change needed to create variables easy to understand. E.g. `$choiceValue` -> is the value chosen by the user or the value shown in the choice list? Better use `$selectedValue` or `$selectedIndex`, etc. Thanks!

2018-05-29 14:06 UTC, closed without merging

2018-05-29 14:25 UTC, vudaltsov commented
I think that `$choiceValue` is understandable enough because that's the value from the `choices` option. We can rename it only when we know what it is in terms of model data (like `$category`).

2018-05-29 14:40 UTC, yceruto commented
@vudaltsov what about just `$choice`? that's how it is called internally for all cases:
https://github.com/symfony/symfony/blob/3a2eb0d9514f0b322ab31a128aa48b9f89e28d50/src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php#L121

https://github.com/symfony/symfony/blob/3a2eb0d9514f0b322ab31a128aa48b9f89e28d50/src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php#L130

https://github.com/symfony/symfony/blob/3a2eb0d9514f0b322ab31a128aa48b9f89e28d50/src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php#L140

https://github.com/symfony/symfony/blob/3a2eb0d9514f0b322ab31a128aa48b9f89e28d50/src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php#L144

https://github.com/symfony/symfony/blob/3a2eb0d9514f0b322ab31a128aa48b9f89e28d50/src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php#L203

2018-05-29 14:41 UTC, vudaltsov commented
@yceruto , okay! I will do that in my PR.

2018-05-29 15:57 UTC, javiereguiluz commented
I still think it's not understandable. I can't understand anything here --> `function ($choice, $index, $value)`

Please, let's pick variable names that the reader cannot mistake. For example, which of the following names best describe the previous arguments?

```php
function ($selectedChoice, $choiceIndex, $choiceValue)
function ($availableChoice, $selectedIndex, $selectedValue)
function ($availableChoice, $choiceIndex, $choiceValue)
etc.
```

2018-05-29 16:31 UTC, vudaltsov commented
The problem with `$choiceValue` is that we have an option `choice_value` which is about `$viewValue` and that might be misleading. While `data` indicates that this is more of a model thing, the actual choice data.