Popper js is required
symfony/symfony-docs pull request #9980
Opened 2018-06-30 16:38 UTC by Etilawin

If you don't add popper js you will probably have the following message while compiling with yarn

This dependency was not found:
* popper.js in ./node_modules/bootstrap/dist/js/bootstrap.js

2018-06-30 16:42 UTC, royklutman requested changes
Please change `yarn add popper --dev` to `yarn add popper.js --dev` and popper to Popper.js in the description above the code block.

2018-07-02 06:54 UTC, javiereguiluz approved these changes
In #9918 I told @Eoras 
that we should probably remove Popper.js when installing Bootstrap (https://github.com/symfony/symfony-docs/pull/9918#discussion_r196133195). It's clear now that I was wrong. I'm sorry and I thank you for fixing it. Thanks!

2018-07-02 07:24 UTC, HeahDude approved these changes

2018-07-02 09:38 UTC, Etilawin commented
I juste remarques other minor fixes (for the $primary: $darken... Etc...
Because if you do that before important the fonction you will have a nice error once more I think
I'll take a closer look and update this pull request

2018-07-02 10:38 UTC, Etilawin commented
Nothing to add

2018-07-02 10:39 UTC, Etilawin commented
Didn't want to close sorry

2018-07-02 10:39 UTC, Etilawin commented
Didn't want to close sorry, not used to github yet

2018-07-02 13:30 UTC, javiereguiluz commented
@Etilawin thanks for fixing this! We merged it in 3.4 (the oldest maintained branch where this fix makes sense) and we'll merge in the upper branches automatically later. Congrats on your first Symfony Docs contribution!

2018-07-02 13:30 UTC, closed without merging