[OptionsResolver] Documenting nested options feature
symfony/symfony-docs pull request #9995
Opened 2018-07-02 23:02 UTC by yceruto

Document https://github.com/symfony/symfony/pull/27291 even if it isn't approved, I'd like to explain it better here.

2018-07-08 20:13 UTC, OskarStark commented on components/options_resolver.rst
> +    an array of values to resolver it on runtime.
s/resolver/resolve

2018-07-09 01:09 UTC, yceruto commented on components/options_resolver.rst
> +    an array of values to resolver it on runtime.
Fixed, thanks.

2018-10-10 11:03 UTC, fabpot requested changes

2018-10-10 11:03 UTC, fabpot commented on components/options_resolver.rst
> +Nested option
Nested Option

2018-10-10 11:03 UTC, fabpot commented on components/options_resolver.rst
> +and ``path``. Instead of define it as a simple array of values, you can pass
defining

2018-10-10 11:03 UTC, fabpot commented on components/options_resolver.rst
> +a closure as the default value of the ``spool`` option with an :class:`Symfony\\Component\\OptionsResolver\\OptionsResolver`
with a

2018-10-10 11:03 UTC, fabpot commented on components/options_resolver.rst
> +In same way, parent options can access to the child option as follows::
can access the child

2018-10-10 11:03 UTC, fabpot commented on components/options_resolver.rst
> +    The fact that an option is defined as nested, means that you must to pass
no comma here.
you must pass
at runtime

2018-10-10 14:20 UTC, yceruto commented
@fabpot comments addressed, thanks!

2018-10-12 13:58 UTC, yceruto commented
@javiereguiluz the code was merged. We can take care of this :) Do you have any suggestion? Thanks!

2018-10-12 17:48 UTC, OskarStark commented on components/options_resolver.rst
> +                // ...
So many of them 🙈🙈😊

2018-10-12 18:58 UTC, yceruto commented on components/options_resolver.rst
> +                // ...
I've removed some // ... :), thanks.

2018-10-12 18:59 UTC, OskarStark commented on components/options_resolver.rst
> +                // ...
thank you ;-)

2018-10-12 19:00 UTC, OskarStark approved these changes

2018-11-19 16:45 UTC, yceruto commented
Please, don't forget this before final release of 4.2.

2018-12-10 13:20 UTC, yceruto commented
Rebased on master.

2018-12-13 16:44 UTC, yceruto commented
Someone could review this doc please. 4.2 is out there asking for this new feature :)

2018-12-14 15:36 UTC, javiereguiluz commented
Thanks Yonel. I'm sorry it took us so long to merge this. I just did in 4.2 branch. Thanks!

2018-12-14 15:36 UTC, closed without merging

2018-12-14 16:00 UTC, yceruto commented
Thank you Javier!